/**
 * calendarExportUtils — Universal .ics calendar export for HESTIA events.
 *
 * Pure utility. No React. No side effects beyond triggering a browser download.
 * No API calls, OAuth, or tokens — all generation is client-side.
 *
 * Produces RFC 5545-compliant VCALENDAR output compatible with:
 *   Google Calendar, Outlook, Apple Calendar, Samsung Calendar.
 *
 * Rules:
 *   - Only real event data. Never generate placeholder or invented values.
 *   - Returns null (never a partial file) if required fields are missing.
 *   - If start_time is absent, canExportCalendar() returns false — callers must gate.
 *   - DTEND defaults to DTSTART + 4 hours when event.end_time is not set;
 *     this is the industry-standard calendar default, not an invented value.
 */

const EVENT_TYPE_LABELS = {
  wedding:   'Wedding',
  corporate: 'Corporate',
  private:   'Private',
  bar_event: 'Bar Event',
  other:     'Event',
}

// ── ICS text helpers ──────────────────────────────────────────────────────────

function escapeICS(str) {
  if (str == null) return ''
  return String(str)
    .replace(/\\/g,  '\\\\')
    .replace(/;/g,   '\\;')
    .replace(/,/g,   '\\,')
    .replace(/\r/g,  '')
    .replace(/\n/g,  '\\n')
}

// Fold long lines at 75 characters per RFC 5545 §3.1
function foldLine(line) {
  if (line.length <= 75) return line
  let result = ''
  let rest   = line
  while (rest.length > 75) {
    result += rest.slice(0, 75) + '\r\n '
    rest    = rest.slice(75)
  }
  return result + rest
}

// ── Time helpers ──────────────────────────────────────────────────────────────

// Parse HH:MM → zero-padded HHMMSS string, or null on bad input
function toICSTime(timeStr) {
  if (!timeStr) return null
  const [h, m] = timeStr.split(':').map(Number)
  if (isNaN(h) || isNaN(m)) return null
  return `${String(h).padStart(2, '0')}${String(m).padStart(2, '0')}00`
}

// Add `hours` to HH:MM, returns HHMMSS string (wraps at midnight)
function addHoursToTime(timeStr, hours) {
  const [h, m] = timeStr.split(':').map(Number)
  const total  = h * 60 + m + hours * 60
  const hh     = Math.floor((total % 1440) / 60)
  const mm     = total % 60
  return `${String(hh).padStart(2, '0')}${String(mm).padStart(2, '0')}00`
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns true if the event has enough data to generate a valid ICS file.
 * Use this to gate the button — never attempt export when false.
 */
export function canExportCalendar(event) {
  return Boolean(event?.event_date && event?.start_time)
}

/**
 * Build the RFC 5545 VCALENDAR string for a single event.
 * Returns null if required fields are missing (never a partial/broken file).
 *
 * @param {object} event — raw event object from the HESTIA database
 * @returns {string|null}
 */
export function buildICSContent(event) {
  if (!canExportCalendar(event)) return null

  const dateStr   = event.event_date.replace(/-/g, '')   // YYYYMMDD
  const startTime = toICSTime(event.start_time)
  if (!startTime) return null

  const dtStart = `${dateStr}T${startTime}`

  // DTEND: use real end_time when available; default +4 h otherwise
  let dtEnd
  if (event.end_time) {
    const endTime = toICSTime(event.end_time)
    if (endTime) dtEnd = `${dateStr}T${endTime}`
  }
  if (!dtEnd) {
    dtEnd = `${dateStr}T${addHoursToTime(event.start_time, 4)}`
  }

  // DTSTAMP — current UTC moment (manual construction avoids regex issues)
  const now = new Date()
  const pad = n => String(n).padStart(2, '0')
  const dtstamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}T${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}Z`

  // UID — unique per export
  const uid = `hestia-${event.id}-${Date.now()}@hestia`

  // DESCRIPTION — real fields only; omit null/undefined lines
  const typeLabel   = EVENT_TYPE_LABELS[event.event_type] || 'Event'
  const statusLabel = event.status
    ? event.status.charAt(0).toUpperCase() + event.status.slice(1).replace(/_/g, ' ')
    : null

  const descLines = [
    `Event Type: ${typeLabel}`,
    event.expected_guests != null ? `Guests: ${event.expected_guests}` : null,
    statusLabel                    ? `Status: ${statusLabel}`          : null,
    '',
    'Generated by HESTIA',
  ].filter(l => l !== null)

  const summary     = escapeICS(event.name      || '')
  const location    = escapeICS(event.location  || '')
  const description = escapeICS(descLines.join('\n'))

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//HESTIA//Event Management//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${dtstamp}`,
    `DTSTART:${dtStart}`,
    `DTEND:${dtEnd}`,
    `SUMMARY:${summary}`,
    location ? `LOCATION:${location}` : null,
    `DESCRIPTION:${description}`,
    'STATUS:CONFIRMED',
    'END:VEVENT',
    'END:VCALENDAR',
  ].filter(Boolean)

  return lines.map(foldLine).join('\r\n') + '\r\n'
}

/**
 * Generate the ICS file for `event` and trigger a browser download.
 * No-op when canExportCalendar(event) is false.
 *
 * @param {object} event
 */
export function downloadEventCalendar(event) {
  const content = buildICSContent(event)
  if (!content) return

  // Sanitise name for the filename (strip non-ASCII-word chars, collapse spaces)
  const safeName = (event.name || 'event')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60) || 'event'

  const filename = `${safeName}.ics`
  const blob     = new Blob([content], { type: 'text/calendar;charset=utf-8' })
  const url      = URL.createObjectURL(blob)

  const anchor   = document.createElement('a')
  anchor.href    = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}
