// Read-only canonical library of 50 essential classic cocktails.
// Schema is distinct from venue cocktail proposals and from cocktails.js (Academy/KnowledgeLibrary).
// libraryType: 'core_classic' | readOnly: true — never modified at runtime.
// Ingredient amounts use ml for measured pours; amount: null for unmeasured tops/rinses.

export const CLASSIC_COCKTAIL_COUNT = 50

export const CLASSIC_COCKTAIL_LIBRARY = [

  // ── SPIRIT FORWARD / STIRRED (11) ──────────────────────────────────────────

  {
    id: 'old-fashioned',
    name: 'Old Fashioned',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Whisky',
    baseSpirit: 'Bourbon',
    story: 'The oldest known cocktail format — spirit, sugar, bitters, water — first printed in 1806 and popularised in Louisville by the early 19th century. The name emerged when drinkers began asking for cocktails made "the old-fashioned way," before the era of flavoured liqueurs and juices.',
    ingredients: [
      { name: 'Bourbon',              amount: 60, unit: 'ml' },
      { name: 'Demerara syrup (2:1)', amount:  5, unit: 'ml' },
      { name: 'Angostura bitters',    amount:  2, unit: 'dashes' },
    ],
    method: 'Combine syrup and bitters in a rocks glass. Add a large ice block. Add bourbon. Stir until well chilled. Express an orange peel over the surface and drop it in.',
    glassware: 'Rocks Glass',
    garnish: 'Orange peel',
    tags: ['spirit-forward', 'stirred', 'IBA', 'whisky', 'classic', 'three-ingredient'],
    notes: 'Rye is the historically accurate base; bourbon is the modern American standard. Some versions use a sugar cube muddled with bitters and a splash of water.',
  },

  {
    id: 'negroni',
    name: 'Negroni',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Invented in Florence around 1919 when Count Camillo Negroni asked bartender Fosco Scarselli to strengthen his Americano by replacing soda with gin. Equal parts of three ingredients in perfect bitter-sweet tension — the definitive aperitivo cocktail.',
    ingredients: [
      { name: 'Gin',           amount: 30, unit: 'ml' },
      { name: 'Sweet vermouth', amount: 30, unit: 'ml' },
      { name: 'Campari',       amount: 30, unit: 'ml' },
    ],
    method: 'Stir all ingredients with ice until well chilled and diluted. Strain into a rocks glass over a large ice block.',
    glassware: 'Rocks Glass',
    garnish: 'Orange peel',
    tags: ['spirit-forward', 'stirred', 'IBA', 'gin', 'bitter', 'aperitivo', 'equal-parts'],
    notes: 'The Sbagliato swaps gin for Prosecco. The Boulevardier swaps gin for bourbon. The White Negroni replaces both Campari and vermouth with French alternatives.',
  },

  {
    id: 'manhattan',
    name: 'Manhattan',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Whisky',
    baseSpirit: 'Rye',
    story: 'Emerged in New York in the 1870s–1880s, one of the first cocktails made with vermouth. The Manhattan defined the spirit-vermouth-bitters template that spawned the Martini and dozens of variants. Rye was the original base; bourbon is a common modern substitution.',
    ingredients: [
      { name: 'Rye whiskey',    amount: 60, unit: 'ml' },
      { name: 'Sweet vermouth', amount: 30, unit: 'ml' },
      { name: 'Angostura bitters', amount: 2, unit: 'dashes' },
    ],
    method: 'Stir all ingredients with ice until well chilled. Strain into a chilled coupe or Nick & Nora.',
    glassware: 'Coupe',
    garnish: 'Brandied cherry or lemon peel',
    tags: ['spirit-forward', 'stirred', 'IBA', 'whisky', 'classic', 'new-york'],
    notes: 'The Perfect Manhattan uses equal parts sweet and dry vermouth. The Rob Roy substitutes Scotch for rye.',
  },

  {
    id: 'dry-martini',
    name: 'Dry Martini',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Descended from the 19th-century Martinez, the Dry Martini crystallised into its modern form by the 1920s as dry vermouth replaced sweet and the gin-to-vermouth ratio crept higher. Possibly the most debated cocktail in existence.',
    ingredients: [
      { name: 'London dry gin',  amount: 60, unit: 'ml' },
      { name: 'Dry vermouth',    amount: 15, unit: 'ml' },
    ],
    method: 'Stir gin and vermouth with ice until well chilled and diluted. Strain into a chilled Nick & Nora or cocktail glass.',
    glassware: 'Nick & Nora',
    garnish: 'Lemon peel or green olive',
    tags: ['spirit-forward', 'stirred', 'IBA', 'gin', 'classic', 'aperitivo'],
    notes: 'The ratio (3:1 to 15:1) is a matter of personal preference and era. The Vesper adds vodka and Lillet Blanc. The Dirty Martini adds olive brine.',
  },

  {
    id: 'vieux-carre',
    name: 'Vieux Carré',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Whisky',
    baseSpirit: 'Rye',
    story: 'Created by Walter Bergeron at the Hotel Monteleone in New Orleans around 1938, named after the French Quarter. Uniquely balances American rye with French cognac and Italian vermouth — a liquid portrait of New Orleans\'s layered cultural heritage.',
    ingredients: [
      { name: 'Rye whiskey',          amount: 22, unit: 'ml' },
      { name: 'Cognac',               amount: 22, unit: 'ml' },
      { name: 'Sweet vermouth',       amount: 22, unit: 'ml' },
      { name: 'Bénédictine',          amount:  7, unit: 'ml' },
      { name: 'Angostura bitters',    amount:  1, unit: 'dash' },
      { name: 'Peychaud\'s bitters',  amount:  1, unit: 'dash' },
    ],
    method: 'Stir all ingredients with ice until chilled. Strain into a rocks glass over ice or a chilled Nick & Nora.',
    glassware: 'Rocks Glass',
    garnish: 'Lemon peel',
    tags: ['spirit-forward', 'stirred', 'new-orleans', 'whisky', 'cognac', 'complex'],
    notes: 'Served on the rocks at the Hotel Monteleone. Some modern bartenders prefer it up in a Nick & Nora for a cleaner presentation.',
  },

  {
    id: 'toronto',
    name: 'Toronto',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Whisky',
    baseSpirit: 'Rye',
    story: 'First published in Robert Vermeire\'s Cocktails: How to Mix Them (1922). A stark, bitter rye cocktail built around Fernet-Branca that faded into obscurity until the craft cocktail revival of the 2000s restored it to menus worldwide.',
    ingredients: [
      { name: 'Rye whiskey',      amount: 60, unit: 'ml' },
      { name: 'Fernet-Branca',    amount:  7, unit: 'ml' },
      { name: 'Simple syrup',     amount:  5, unit: 'ml' },
      { name: 'Angostura bitters', amount: 1, unit: 'dash' },
    ],
    method: 'Stir all ingredients with ice. Strain into a chilled Nick & Nora or coupe.',
    glassware: 'Nick & Nora',
    garnish: 'Orange peel',
    tags: ['spirit-forward', 'stirred', 'bitter', 'whisky', 'modern-classic'],
    notes: 'Fernet quantity can range from 5–15 ml depending on the desired amaro intensity. Higher amounts reward drinkers who appreciate Fernet on its own.',
  },

  {
    id: 'bamboo',
    name: 'Bamboo',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Sherry',
    baseSpirit: 'Sherry',
    story: 'Attributed to Louis Eppinger at the Grand Hotel Yokohama in the 1890s — one of the earliest documented low-ABV cocktails. Built on sherry and vermouth rather than a base spirit, it anticipated the low-ABV movement by over a century.',
    ingredients: [
      { name: 'Dry sherry (fino or manzanilla)', amount: 45, unit: 'ml' },
      { name: 'Dry vermouth',                    amount: 45, unit: 'ml' },
      { name: 'Orange bitters',                  amount:  2, unit: 'dashes' },
    ],
    method: 'Stir all ingredients with ice until well chilled. Strain into a chilled Nick & Nora.',
    glassware: 'Nick & Nora',
    garnish: 'Lemon peel',
    tags: ['spirit-forward', 'stirred', 'low-abv', 'sherry', 'aperitivo', 'historic'],
    notes: 'The drink can lean dryer (fino + extra-dry vermouth) or richer (amontillado + sweet vermouth). Both equal-parts and 2:1 ratios appear in period recipes.',
  },

  {
    id: 'hanky-panky',
    name: 'Hanky Panky',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created by Ada Coleman, head bartender at The Savoy\'s American Bar from 1903 to 1925 — one of the first female head bartenders at a prestigious London venue. Reportedly invented for actor Sir Charles Hawtrey, who exclaimed "By Jove! That is the real hanky-panky!"',
    ingredients: [
      { name: 'London dry gin',  amount: 45, unit: 'ml' },
      { name: 'Sweet vermouth',  amount: 45, unit: 'ml' },
      { name: 'Fernet-Branca',   amount:  7, unit: 'ml' },
    ],
    method: 'Stir all ingredients with ice. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Orange peel',
    tags: ['spirit-forward', 'stirred', 'historic', 'gin', 'savoy', 'bitter'],
    notes: 'Published in The Savoy Cocktail Book (1930). A close relative of the Negroni family but with Fernet providing a more medicinal, mentholated backbone.',
  },

  {
    id: 'bijou',
    name: 'Bijou',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Published by Harry Johnson in his 1900 Bartenders\' Manual. The name means "jewel" in French — referencing the three gem-coloured spirits: gin (diamond), sweet vermouth (ruby), and green Chartreuse (emerald). One of the most underappreciated pre-Prohibition classics.',
    ingredients: [
      { name: 'London dry gin',    amount: 30, unit: 'ml' },
      { name: 'Sweet vermouth',    amount: 30, unit: 'ml' },
      { name: 'Green Chartreuse',  amount: 15, unit: 'ml' },
      { name: 'Orange bitters',    amount:  1, unit: 'dash' },
    ],
    method: 'Stir all ingredients with ice. Strain into a chilled Nick & Nora or coupe.',
    glassware: 'Nick & Nora',
    garnish: 'Lemon peel or cherry',
    tags: ['spirit-forward', 'stirred', 'historic', 'gin', 'chartreuse', 'pre-prohibition'],
    notes: 'Green Chartreuse gives this significant herbal intensity. Some recipes use equal thirds of all three base ingredients; others use 2:1:1.',
  },

  {
    id: 'white-negroni',
    name: 'White Negroni',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created by Wayne Collins in Bordeaux around 2001, substituting Lillet Blanc and Suze for the Italian ingredients of a Negroni. A paler, more floral and citrus-forward riff that became a modern classic in its own right.',
    ingredients: [
      { name: 'Gin',        amount: 45, unit: 'ml' },
      { name: 'Lillet Blanc', amount: 22, unit: 'ml' },
      { name: 'Suze',       amount: 22, unit: 'ml' },
    ],
    method: 'Stir all ingredients with ice. Strain into a chilled Nick & Nora or a rocks glass over ice.',
    glassware: 'Nick & Nora',
    garnish: 'Grapefruit peel',
    tags: ['spirit-forward', 'stirred', 'modern-classic', 'gin', 'bitter', 'floral'],
    notes: 'Suze is a gentian-based bitter liqueur from France. Salers or other gentian amari can substitute. The drink is lighter and more floral than a Negroni.',
  },

  {
    id: 'mezcal-negroni',
    name: 'Mezcal Negroni',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Spirit Forward',
    family: 'Mezcal',
    baseSpirit: 'Mezcal',
    story: 'Popularised in the early 2010s at New York bars like Death & Co and Leyenda. Replacing gin with mezcal adds a smoky, earthy dimension that transforms the Negroni\'s bitter-sweet tension into something more complex and terrain-driven.',
    ingredients: [
      { name: 'Mezcal',         amount: 30, unit: 'ml' },
      { name: 'Sweet vermouth', amount: 30, unit: 'ml' },
      { name: 'Campari',        amount: 30, unit: 'ml' },
    ],
    method: 'Stir all ingredients with ice. Strain into a rocks glass over a large ice block.',
    glassware: 'Rocks Glass',
    garnish: 'Orange peel',
    tags: ['spirit-forward', 'stirred', 'modern-classic', 'mezcal', 'smoky', 'bitter', 'equal-parts'],
    notes: 'Best with an espadín mezcal rather than a heavily peated style. Some versions add a few drops of mole bitters to bridge the smoky and bitter dimensions.',
  },

  // ── SHAKEN SOURS (14) ──────────────────────────────────────────────────────

  {
    id: 'daiquiri',
    name: 'Daiquiri',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Rum',
    baseSpirit: 'White Rum',
    story: 'Named after a beach near Santiago de Cuba. Codified by American engineer Jennings Cox around 1898 and introduced to US bars by Naval officer Lucius Johnson. Ernest Hemingway was a devoted customer at El Floridita in Havana, where the frozen version was born.',
    ingredients: [
      { name: 'White rum',            amount: 60, unit: 'ml' },
      { name: 'Fresh lime juice',     amount: 22, unit: 'ml' },
      { name: 'Simple syrup (2:1)',   amount: 15, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Double strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Lime wheel or none',
    tags: ['sour', 'shaken', 'IBA', 'rum', 'classic', 'citrus', 'three-ingredient'],
    notes: 'The ratio is the template: 2:¾:½ spirit-citrus-sugar. Adjust syrup to lime ripeness — fresh-squeezed lime is non-negotiable.',
  },

  {
    id: 'margarita',
    name: 'Margarita',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Tequila',
    baseSpirit: 'Tequila',
    story: 'The most consumed cocktail in the United States, with disputed origins ranging from Rancho La Gloria (1938) to an Acapulco party in 1948. The structure follows the Sidecar template — spirit, triple sec, citrus — transplanted to tequila.',
    ingredients: [
      { name: 'Blanco tequila',   amount: 50, unit: 'ml' },
      { name: 'Fresh lime juice', amount: 25, unit: 'ml' },
      { name: 'Cointreau',        amount: 20, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe or over ice in a rocks glass.',
    glassware: 'Coupe',
    garnish: 'Lime wedge, salt rim optional',
    tags: ['sour', 'shaken', 'IBA', 'tequila', 'classic', 'citrus'],
    notes: 'Salt rim amplifies sweetness and suppresses bitterness — it is a matter of preference, not tradition. Tommy\'s Margarita uses agave syrup in place of Cointreau.',
  },

  {
    id: 'whiskey-sour',
    name: 'Whiskey Sour',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Whisky',
    baseSpirit: 'Bourbon',
    story: 'One of the earliest recorded sours, first published by Jerry Thomas in his 1862 Bartender\'s Guide. The sour template — spirit, citrus, sugar — is one of five fundamental cocktail structures. Egg white became a standard variation in American bars by the early 20th century.',
    ingredients: [
      { name: 'Bourbon',          amount: 60, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 22, unit: 'ml' },
      { name: 'Simple syrup (2:1)', amount: 15, unit: 'ml' },
      { name: 'Egg white',        amount:  1, unit: 'optional' },
    ],
    method: 'If using egg white: dry shake first without ice, then add ice and shake hard. If not: shake hard with ice. Strain into a rocks glass over ice or a chilled coupe.',
    glassware: 'Rocks Glass',
    garnish: 'Orange half-wheel, Angostura drops on foam',
    tags: ['sour', 'shaken', 'IBA', 'whisky', 'classic', 'citrus'],
    notes: 'The New York Sour floats a red wine pour on top. The Amaretto Sour (modern version) adds a split of cask-strength bourbon.',
  },

  {
    id: 'pisco-sour',
    name: 'Pisco Sour',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Pisco',
    baseSpirit: 'Pisco',
    story: 'Created by American bartender Victor Morris at his bar in Lima, Peru, around 1920, and later refined with egg white by Mario Bruiget. Now Peru\'s national cocktail and a legally protected cultural heritage item under Peruvian law.',
    ingredients: [
      { name: 'Pisco',            amount: 60, unit: 'ml' },
      { name: 'Fresh lime juice', amount: 30, unit: 'ml' },
      { name: 'Simple syrup (2:1)', amount: 20, unit: 'ml' },
      { name: 'Egg white',        amount:  1, unit: 'whole' },
    ],
    method: 'Dry shake all ingredients without ice. Add ice and shake hard. Double strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Angostura bitters drops on foam',
    tags: ['sour', 'shaken', 'IBA', 'pisco', 'peru', 'foam', 'classic'],
    notes: 'Peruvian pisco (quebranta grape) is the traditional base. Chilean pisco uses a different distillation method and is considered a separate drink by Peruvians.',
  },

  {
    id: 'bees-knees',
    name: 'Bee\'s Knees',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'A Prohibition-era classic — honey and lemon were used to mask the harshness of bathtub gin. The phrase "bee\'s knees" was 1920s slang for "the best." It resurfaced in the craft cocktail revival as a showcase for quality gin and local honey varieties.',
    ingredients: [
      { name: 'London dry gin',      amount: 60, unit: 'ml' },
      { name: 'Fresh lemon juice',   amount: 22, unit: 'ml' },
      { name: 'Honey syrup (1:1)',   amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Double strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Lemon twist',
    tags: ['sour', 'shaken', 'prohibition', 'gin', 'honey', 'classic'],
    notes: 'Honey syrup 1:1 (honey:water) is standard — neat honey emulsifies poorly in the shaker. Buckwheat honey gives more depth than clover.',
  },

  {
    id: 'gold-rush',
    name: 'Gold Rush',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Whisky',
    baseSpirit: 'Bourbon',
    story: 'Created by TJ Siegel at Milk & Honey, New York, around 2000. Effectively a Bee\'s Knees built on bourbon. Its minimal, precise construction became a template for the Milk & Honey school of bartending — exact ratios, quality ice, no fuss.',
    ingredients: [
      { name: 'Bourbon',            amount: 60, unit: 'ml' },
      { name: 'Fresh lemon juice',  amount: 22, unit: 'ml' },
      { name: 'Honey syrup (1:1)', amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Double strain into a rocks glass over a large ice block.',
    glassware: 'Rocks Glass',
    garnish: 'None',
    tags: ['sour', 'shaken', 'modern-classic', 'whisky', 'honey', 'milk-and-honey'],
    notes: 'Often served over a single large ice block to slow dilution and maintain the precise balance of the original recipe.',
  },

  {
    id: 'clover-club',
    name: 'Clover Club',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Named after a Philadelphia men\'s dining club that met at the Bellevue-Stratford Hotel from the 1880s — predating Prohibition. One of the original foamy gin cocktails, it was a key drink in the early 2000s craft revival, particularly at the Brooklyn bar named in its honour.',
    ingredients: [
      { name: 'London dry gin',    amount: 50, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 20, unit: 'ml' },
      { name: 'Raspberry syrup',   amount: 15, unit: 'ml' },
      { name: 'Egg white',         amount:  1, unit: 'whole' },
    ],
    method: 'Dry shake all ingredients without ice. Add ice and shake hard. Double strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Three fresh raspberries',
    tags: ['sour', 'shaken', 'pre-prohibition', 'gin', 'foam', 'raspberry', 'historic'],
    notes: 'Raspberry syrup from fresh raspberries gives the best colour and flavour. Grenadine can substitute but significantly alters the flavour profile.',
  },

  {
    id: 'amaretto-sour',
    name: 'Amaretto Sour',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Liqueur',
    baseSpirit: 'Amaretto',
    story: 'The 1970s original was sickly-sweet. Jeffrey Morgenthaler\'s 2012 reconstruction — adding overproof bourbon to the amaretto and introducing egg white — transformed it into a serious cocktail and helped rehabilitate an entire category.',
    ingredients: [
      { name: 'Amaretto',                amount: 45, unit: 'ml' },
      { name: 'Cask-strength bourbon',   amount: 15, unit: 'ml' },
      { name: 'Fresh lemon juice',       amount: 30, unit: 'ml' },
      { name: 'Simple syrup',            amount:  5, unit: 'ml' },
      { name: 'Egg white',               amount:  1, unit: 'whole' },
    ],
    method: 'Dry shake without ice. Add ice and shake hard. Double strain into a rocks glass over ice.',
    glassware: 'Rocks Glass',
    garnish: 'Brandied cherry, Angostura drops on foam',
    tags: ['sour', 'shaken', 'modern-classic', 'liqueur', 'foam'],
    notes: 'The bourbon addition provides backbone and prevents the drink from becoming cloying. Morgenthaler\'s blog post about this recipe is widely cited in the craft cocktail canon.',
  },

  {
    id: 'new-york-sour',
    name: 'New York Sour',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Whisky',
    baseSpirit: 'Bourbon',
    story: 'Emerged in Chicago in the 1880s as the "Continental Sour" before becoming popular in New York. The defining feature — a claret float — was originally a fashionable garnish for whiskey sours. Largely forgotten until the craft cocktail revival restored it.',
    ingredients: [
      { name: 'Bourbon',          amount: 60, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 22, unit: 'ml' },
      { name: 'Simple syrup (2:1)', amount: 15, unit: 'ml' },
      { name: 'Egg white',        amount:  1, unit: 'optional' },
      { name: 'Dry red wine',     amount: 15, unit: 'ml' },
    ],
    method: 'Shake all ingredients except wine (dry shake with egg white first if using). Strain into a rocks glass over ice. Float red wine gently over the back of a bar spoon.',
    glassware: 'Rocks Glass',
    garnish: 'Orange half-wheel',
    tags: ['sour', 'shaken', 'historic', 'whisky', 'layered', 'wine-float'],
    notes: 'A lighter-bodied red floats more easily — Beaujolais, Pinot Noir, or Lambrusco work well. Tannic reds are harder to layer and can dominate the palate.',
  },

  {
    id: 'blood-and-sand',
    name: 'Blood & Sand',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Whisky',
    baseSpirit: 'Scotch',
    story: 'Published in the Savoy Cocktail Book (1930), named after the Rudolph Valentino bullfighting film of 1922. Remarkable for its equal-parts formula — Scotch, Cherry Heering, sweet vermouth, and orange juice — an unusual combination that achieves surprising balance.',
    ingredients: [
      { name: 'Blended Scotch',    amount: 22, unit: 'ml' },
      { name: 'Cherry Heering',    amount: 22, unit: 'ml' },
      { name: 'Sweet vermouth',    amount: 22, unit: 'ml' },
      { name: 'Fresh orange juice', amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Orange peel or cherry',
    tags: ['sour', 'shaken', 'savoy', 'whisky', 'scotch', 'equal-parts', 'historic'],
    notes: 'Equal parts is the original spec. Blood orange juice instead of regular orange makes a dramatic seasonal variation with deeper colour and bittersweet notes.',
  },

  {
    id: 'aviation',
    name: 'Aviation',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created by Hugo Ensslin at the Hotel Wallick, New York, around 1916. The original recipe included crème de violette for a sky-blue hue. Harry Craddock omitted it in the Savoy Cocktail Book (1930), and it was largely unavailable until Rothman & Winter relaunched their version in 2007.',
    ingredients: [
      { name: 'Gin',                 amount: 50, unit: 'ml' },
      { name: 'Maraschino liqueur',  amount: 15, unit: 'ml' },
      { name: 'Crème de violette',   amount:  7, unit: 'ml' },
      { name: 'Fresh lemon juice',   amount: 20, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Double strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Brandied cherry',
    tags: ['sour', 'shaken', 'pre-prohibition', 'gin', 'floral', 'violet', 'maraschino'],
    notes: 'Crème de violette is essential for the correct colour and floral note. Without it the drink is still good but is no longer properly an Aviation.',
  },

  {
    id: 'corpse-reviver-no2',
    name: 'Corpse Reviver No. 2',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Published in the Savoy Cocktail Book (1930) with the note: "Four of these taken in swift succession will unrevive the corpse again." Designed as a morning-after restorative in the tradition of pick-me-up cocktails. The absinthe rinse is critical to the drink\'s character.',
    ingredients: [
      { name: 'Gin',          amount: 22, unit: 'ml' },
      { name: 'Cointreau',    amount: 22, unit: 'ml' },
      { name: 'Lillet Blanc', amount: 22, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 22, unit: 'ml' },
      { name: 'Absinthe',     amount: null, unit: 'rinse' },
    ],
    method: 'Rinse a chilled coupe with absinthe and discard. Shake remaining ingredients with ice. Strain into the prepared coupe.',
    glassware: 'Coupe',
    garnish: 'Orange peel or cherry',
    tags: ['sour', 'shaken', 'savoy', 'gin', 'equal-parts', 'absinthe', 'historic'],
    notes: 'Original recipe calls for Kina Lillet. Modern Lillet Blanc is less bitter — a dash of gentian bitters approximates the original quinine character.',
  },

  {
    id: 'sidecar',
    name: 'Sidecar',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Cognac',
    baseSpirit: 'Cognac',
    story: 'Originated in Paris or London around World War I, with Robert Vermeire and Harry MacElhone each publishing early recipes circa 1922. The Sidecar established the cognac-Cointreau-lemon Daisy template that gave rise to the Margarita, Kamikaze, and dozens of other drinks.',
    ingredients: [
      { name: 'Cognac',           amount: 50, unit: 'ml' },
      { name: 'Cointreau',        amount: 20, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 20, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Sugar rim, orange peel',
    tags: ['sour', 'shaken', 'IBA', 'cognac', 'classic', 'paris', 'citrus'],
    notes: 'The London school uses equal parts (1:1:1). The Paris school uses 2:1:1 spirit-heavy. Sugar rim is traditional but optional.',
  },

  {
    id: 'between-the-sheets',
    name: 'Between the Sheets',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Sour',
    family: 'Cognac',
    baseSpirit: 'Cognac',
    story: 'A Prohibition-era variant of the Sidecar, first published by Harry MacElhone at Harry\'s New York Bar in Paris around 1930. Adds rum and drops the sugar rim. The titillating name was part of a tradition of provocatively titled cocktails common in that era.',
    ingredients: [
      { name: 'Cognac',           amount: 30, unit: 'ml' },
      { name: 'White rum',        amount: 30, unit: 'ml' },
      { name: 'Cointreau',        amount: 30, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 15, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Lemon peel',
    tags: ['sour', 'shaken', 'historic', 'cognac', 'rum', 'paris', 'prohibition'],
    notes: 'The equal-parts cognac-rum base creates a more complex and slightly lighter version of the Sidecar, with the rum adding tropical and molasses notes.',
  },

  // ── MODERN CLASSICS (9) ────────────────────────────────────────────────────

  {
    id: 'cosmopolitan',
    name: 'Cosmopolitan',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Vodka',
    baseSpirit: 'Citrus Vodka',
    story: 'Popularised by Toby Cecchini at The Odeon in New York (1988), who refined a recipe circulating in Miami\'s bar scene. Became a cultural phenomenon via Sex and the City (1998–2004) — the most influential vodka cocktail in history.',
    ingredients: [
      { name: 'Citrus vodka',     amount: 45, unit: 'ml' },
      { name: 'Cointreau',        amount: 15, unit: 'ml' },
      { name: 'Fresh lime juice', amount: 15, unit: 'ml' },
      { name: 'Cranberry juice',  amount: 30, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Flamed orange peel',
    tags: ['shaken', 'modern-classic', 'vodka', '1990s', 'IBA', 'iconic'],
    notes: 'Cranberry is for colour and a whisper of tartness — the drink should be pink, not red. Freshly squeezed lime is non-negotiable for balance.',
  },

  {
    id: 'espresso-martini',
    name: 'Espresso Martini',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Vodka',
    baseSpirit: 'Vodka',
    story: 'Created by Dick Bradsell at Fred\'s Club in London around 1983 when a model asked for something "to wake me up and then f*** me up." Bradsell combined vodka with fresh espresso, producing a foam head he described as looking like an after-dinner coffee. Underwent a global revival in the early 2020s.',
    ingredients: [
      { name: 'Vodka',           amount: 50, unit: 'ml' },
      { name: 'Fresh espresso',  amount: 30, unit: 'ml' },
      { name: 'Coffee liqueur',  amount: 10, unit: 'ml' },
      { name: 'Simple syrup',    amount:  5, unit: 'ml' },
    ],
    method: 'Pull a fresh espresso and let it cool briefly. Combine all ingredients in a shaker with ice. Shake very hard for a full foam. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Three coffee beans',
    tags: ['shaken', 'modern-classic', 'vodka', 'coffee', 'IBA', 'foam', 'london', 'after-dinner'],
    notes: 'Foam quality depends entirely on shaking vigour and cold espresso. Room-temperature espresso kills the foam. Shake longer and harder than you think necessary.',
  },

  {
    id: 'aperol-spritz',
    name: 'Aperol Spritz',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Aperitivo',
    baseSpirit: 'Aperol',
    story: 'The spritz tradition began in northeastern Italy in the early 19th century when Austrian soldiers diluted local wines with water or soda. Aperol (created 1919) replaced wine as the base. The 3:2:1 formula was codified and became one of the most consumed cocktails in the world following Campari Group\'s global marketing campaign from 2009 onward.',
    ingredients: [
      { name: 'Prosecco',    amount: 90, unit: 'ml' },
      { name: 'Aperol',      amount: 60, unit: 'ml' },
      { name: 'Soda water',  amount: 30, unit: 'ml' },
    ],
    method: 'Build in a large wine glass over ice. Add Prosecco, then Aperol, then a splash of soda. Stir gently once.',
    glassware: 'Wine Glass',
    garnish: 'Orange slice',
    tags: ['built', 'modern-classic', 'aperitivo', 'low-abv', 'sparkling', 'italian', 'IBA'],
    notes: 'The IBA ratio is 3:2:1 Prosecco:Aperol:soda. Served very cold in a large format glass. The drink should remain cold — it deteriorates quickly as it warms.',
  },

  {
    id: 'paper-plane',
    name: 'Paper Plane',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Whisky',
    baseSpirit: 'Bourbon',
    story: 'Created by Sam Ross at Milk & Honey, New York, around 2008 — named after the M.I.A. song. An equal-parts cocktail balancing bourbon, Aperol, Amaro Nonino, and lemon. One of the defining drinks of the 2000s craft era and a touchstone of the Milk & Honey school.',
    ingredients: [
      { name: 'Bourbon',        amount: 22, unit: 'ml' },
      { name: 'Aperol',         amount: 22, unit: 'ml' },
      { name: 'Amaro Nonino',   amount: 22, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'None',
    tags: ['shaken', 'modern-classic', 'whisky', 'amaro', 'equal-parts', 'milk-and-honey'],
    notes: 'Amaro Nonino is not easily substituted — its honeyed, orange-peel-bitter character is essential to the balance. Any change to one ingredient changes the whole drink.',
  },

  {
    id: 'last-word',
    name: 'Last Word',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created at the Detroit Athletic Club around 1916, published in Ted Saucier\'s Bottoms Up (1951). Murray Stenson of Zig Zag Café, Seattle, rediscovered it around 2004. It became one of the defining cocktails of the craft revival and a template for equal-parts modern exploration.',
    ingredients: [
      { name: 'Gin',                  amount: 22, unit: 'ml' },
      { name: 'Green Chartreuse',     amount: 22, unit: 'ml' },
      { name: 'Maraschino liqueur',   amount: 22, unit: 'ml' },
      { name: 'Fresh lime juice',     amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'Brandied cherry',
    tags: ['shaken', 'modern-classic', 'gin', 'equal-parts', 'chartreuse', 'maraschino', 'revival'],
    notes: 'The Final Ward substitutes rye for gin and lemon for lime. The Naked & Famous is a mezcal riff on this same equal-parts template.',
  },

  {
    id: 'penicillin',
    name: 'Penicillin',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Whisky',
    baseSpirit: 'Blended Scotch',
    story: 'Created by Sam Ross at Milk & Honey, New York, around 2005. A honey-ginger-lemon sour on blended Scotch, finished with a float of Islay single malt for smokiness. One of the most widely studied examples of a contemporary cocktail that achieved genuine classic status.',
    ingredients: [
      { name: 'Blended Scotch',          amount: 60, unit: 'ml' },
      { name: 'Fresh lemon juice',       amount: 22, unit: 'ml' },
      { name: 'Honey-ginger syrup',      amount: 22, unit: 'ml' },
      { name: 'Islay single malt Scotch', amount: 7, unit: 'ml' },
    ],
    method: 'Shake blended Scotch, lemon, and honey-ginger syrup with ice. Strain into a rocks glass over ice. Float Islay Scotch on top.',
    glassware: 'Rocks Glass',
    garnish: 'Candied ginger, lemon peel',
    tags: ['shaken', 'modern-classic', 'whisky', 'scotch', 'smoky', 'honey', 'milk-and-honey', 'float'],
    notes: 'Honey-ginger syrup: simmer equal parts honey and water with fresh ginger slices, strain. Laphroaig 10 is commonly used for the float.',
  },

  {
    id: 'naked-and-famous',
    name: 'Naked & Famous',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Mezcal',
    baseSpirit: 'Mezcal',
    story: 'Created by Joaquín Simó at Death & Co, New York, in 2011. A mezcal riff on the Last Word, replacing gin with mezcal, Chartreuse with Aperol, and maraschino with Amaro Nonino. Demonstrates how changing the base spirit within a proven equal-parts template creates a new classic.',
    ingredients: [
      { name: 'Mezcal',        amount: 22, unit: 'ml' },
      { name: 'Aperol',        amount: 22, unit: 'ml' },
      { name: 'Amaro Nonino',  amount: 22, unit: 'ml' },
      { name: 'Fresh lime juice', amount: 22, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake hard. Strain into a chilled coupe.',
    glassware: 'Coupe',
    garnish: 'None',
    tags: ['shaken', 'modern-classic', 'mezcal', 'smoky', 'equal-parts', 'death-and-co'],
    notes: 'Smoky mezcal and bitter Amaro Nonino create a more complex and earthier version of the Paper Plane template. The four flavours pull in different directions but land in equilibrium.',
  },

  {
    id: 'jungle-bird',
    name: 'Jungle Bird',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Rum',
    baseSpirit: 'Dark Rum',
    story: 'Created by Jeffrey Ong at the Aviary Bar in the Kuala Lumpur Hilton in 1978 as a welcome drink for arriving guests. Unusual for including Campari in a tiki drink. Largely forgotten until Jeff Berry\'s Beachbum Berry Remixed (2010) sparked a global revival.',
    ingredients: [
      { name: 'Dark rum (Jamaican)',   amount: 45, unit: 'ml' },
      { name: 'Campari',              amount: 22, unit: 'ml' },
      { name: 'Fresh pineapple juice', amount: 45, unit: 'ml' },
      { name: 'Fresh lime juice',     amount: 15, unit: 'ml' },
      { name: 'Demerara syrup (2:1)', amount: 15, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake. Strain into a rocks glass or tiki mug over crushed ice.',
    glassware: 'Rocks Glass',
    garnish: 'Pineapple wedge, mint sprig',
    tags: ['shaken', 'modern-classic', 'rum', 'tiki', 'campari', 'tropical', 'malaysia'],
    notes: 'Blackstrap rum (such as Cruzan) makes it richer and more assertive. The Campari bitterness cuts through tropical sweetness to create the characteristic balance.',
  },

  {
    id: 'bramble',
    name: 'Bramble',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Modern Classic',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created by Dick Bradsell at Fred\'s Club in London in 1984 — inspired by memories of blackberry picking in his childhood on the Isle of Wight. Defined the "crushed ice" British cocktail aesthetic and became one of the most copied bar recipes of the 1980s and 1990s.',
    ingredients: [
      { name: 'London dry gin',       amount: 50, unit: 'ml' },
      { name: 'Fresh lemon juice',    amount: 25, unit: 'ml' },
      { name: 'Simple syrup',         amount: 12, unit: 'ml' },
      { name: 'Crème de mûre',        amount: 15, unit: 'ml' },
    ],
    method: 'Shake gin, lemon, and syrup with ice. Strain into a rocks glass filled with crushed ice. Drizzle crème de mûre over the top so it bleeds down through the drink.',
    glassware: 'Rocks Glass',
    garnish: 'Lemon slice, fresh blackberries',
    tags: ['shaken', 'modern-classic', 'gin', 'blackberry', 'london', 'crushed-ice'],
    notes: 'The float of crème de mûre should not be stirred in — it creates a gradated visual effect and the blackberry flavour intensifies as the drinker reaches the bottom.',
  },

  // ── HIGHBALLS / BUILT (8) ──────────────────────────────────────────────────

  {
    id: 'gin-and-tonic',
    name: 'Gin & Tonic',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Originated with the British East India Company in colonial India, where tonic water containing quinine was consumed as a malaria prophylactic. Adding gin, lime, and sugar made it palatable. Brought to Britain, it became one of the defining drinks of the Empire and remains the most ordered gin serve globally.',
    ingredients: [
      { name: 'Gin',          amount:   50, unit: 'ml' },
      { name: 'Tonic water',  amount: null, unit: 'to top (~150 ml)' },
    ],
    method: 'Fill a highball glass with ice. Add gin. Top with cold tonic water. Stir gently once. Express a citrus peel over the surface.',
    glassware: 'Highball',
    garnish: 'Lime wedge or cucumber slice',
    tags: ['built', 'highball', 'IBA', 'gin', 'british', 'classic', 'low-prep'],
    notes: 'Premium tonic water (Fever-Tree, 1724, Fentimans) makes a measurable flavour difference. The gin-tonic ratio (1:3 to 1:4) is a matter of preference and gin ABV.',
  },

  {
    id: 'mojito',
    name: 'Mojito',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Rum',
    baseSpirit: 'White Rum',
    story: 'Rooted in a 16th-century Cuban drink called El Draque. The modern form is associated with La Bodeguita del Medio in Havana, where Ernest Hemingway was a regular. A quintessential built cocktail balancing rum, citrus, sugar, and carbonation with fresh mint.',
    ingredients: [
      { name: 'White rum',       amount: 50,   unit: 'ml' },
      { name: 'Fresh lime juice', amount: 25,  unit: 'ml' },
      { name: 'Simple syrup',    amount: 15,   unit: 'ml' },
      { name: 'Fresh mint',      amount:  8,   unit: 'leaves' },
      { name: 'Soda water',      amount: null, unit: 'to top' },
    ],
    method: 'Gently press mint with syrup and lime juice in a highball glass (do not tear). Add rum and ice. Top with soda. Stir gently. Slap mint garnish to release aroma.',
    glassware: 'Highball',
    garnish: 'Mint sprig, lime wheel',
    tags: ['built', 'highball', 'IBA', 'rum', 'cuba', 'mint', 'classic'],
    notes: 'Mint should be pressed, not muddled — tearing releases chlorophyll and turns the drink bitter. Spearmint is standard; apple mint gives a softer, sweeter character.',
  },

  {
    id: 'moscow-mule',
    name: 'Moscow Mule',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Vodka',
    baseSpirit: 'Vodka',
    story: 'Created in 1941 as a joint marketing venture between John Martin (who had purchased Smirnoff) and Jack Morgan (owner of Cock \'n\' Bull ginger beer). The copper mug was a marketing device. The drink helped establish vodka in the American market.',
    ingredients: [
      { name: 'Vodka',          amount:   50, unit: 'ml' },
      { name: 'Fresh lime juice', amount: 15, unit: 'ml' },
      { name: 'Ginger beer',    amount: null, unit: 'to top (~120 ml)' },
    ],
    method: 'Fill a copper mug or highball glass with ice. Add vodka and lime juice. Top with cold ginger beer. Stir gently.',
    glassware: 'Highball',
    garnish: 'Lime wedge, mint sprig',
    tags: ['built', 'highball', 'IBA', 'vodka', 'ginger', 'classic', 'american'],
    notes: 'The copper mug is pure marketing — any highball glass works. Use ginger beer (not ginger ale) for the correct spice intensity.',
  },

  {
    id: 'dark-and-stormy',
    name: 'Dark & Stormy',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Rum',
    baseSpirit: 'Dark Rum',
    story: 'Officially trademarked by Gosling Brothers Ltd of Bermuda, who specify it must be made with Gosling\'s Black Seal rum. Evolved from the British naval tradition of mixing rum with ginger beer. The trademark makes it the only cocktail where the brand of spirit is legally mandated.',
    ingredients: [
      { name: 'Dark rum (Gosling\'s Black Seal)', amount:  60, unit: 'ml' },
      { name: 'Fresh lime juice',                amount:  15, unit: 'ml' },
      { name: 'Ginger beer',                     amount: null, unit: 'to top (~120 ml)' },
    ],
    method: 'Fill a highball glass with ice. Add lime juice. Top with cold ginger beer. Float dark rum on top over the back of a bar spoon.',
    glassware: 'Highball',
    garnish: 'Lime wedge',
    tags: ['built', 'highball', 'IBA', 'rum', 'ginger', 'bermuda', 'classic'],
    notes: 'The float creates the storm effect — dark rum resting on top is traditional. Some versions simply build and stir; the flavour is the same but the visual is lost.',
  },

  {
    id: 'paloma',
    name: 'Paloma',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Tequila',
    baseSpirit: 'Tequila',
    story: 'Mexico\'s most consumed tequila cocktail, far more popular domestically than the Margarita. Attributed variously to Don Javier Delgado Corona of La Capilla bar in the town of Tequila. The traditional version uses Squirt grapefruit soda; the craft version uses fresh juice.',
    ingredients: [
      { name: 'Blanco tequila',       amount: 50,   unit: 'ml' },
      { name: 'Fresh grapefruit juice', amount: 60, unit: 'ml' },
      { name: 'Fresh lime juice',     amount: 15,   unit: 'ml' },
      { name: 'Simple syrup',         amount: 10,   unit: 'ml' },
      { name: 'Soda water',           amount: null, unit: 'to top' },
    ],
    method: 'Build in a highball glass over ice. Add tequila, grapefruit juice, lime, syrup. Top with soda. Stir gently.',
    glassware: 'Highball',
    garnish: 'Grapefruit wedge, salt rim optional',
    tags: ['built', 'highball', 'tequila', 'grapefruit', 'mexico', 'classic'],
    notes: 'The traditional version uses Squirt or Jarritos grapefruit soda in place of fresh juice + soda. Both are valid — the fresh version offers more control over sweetness.',
  },

  {
    id: 'french-75',
    name: 'French 75',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Reportedly created at Harry\'s New York Bar in Paris in 1915, named after the French 75 mm field gun — the drink was said to have a kick like the artillery piece. A rare cocktail built on Champagne as the lengthening agent. The New Orleans version uses cognac instead of gin.',
    ingredients: [
      { name: 'Gin',                                amount:   45, unit: 'ml' },
      { name: 'Fresh lemon juice',                  amount:   15, unit: 'ml' },
      { name: 'Simple syrup',                       amount:   10, unit: 'ml' },
      { name: 'Champagne or dry sparkling wine',    amount: null, unit: 'to top (~60 ml)' },
    ],
    method: 'Shake gin, lemon, and syrup with ice. Double strain into a coupe. Top with cold Champagne.',
    glassware: 'Coupe',
    garnish: 'Lemon twist',
    tags: ['shaken', 'sparkling', 'highball', 'IBA', 'gin', 'champagne', 'french', 'historic'],
    notes: 'The cognac version is the New Orleans standard (Bar Arnaud\'s). The gin version is the international standard. Both are correct depending on regional tradition.',
  },

  {
    id: 'el-diablo',
    name: 'El Diablo',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Tequila',
    baseSpirit: 'Tequila',
    story: 'First appeared in Trader Vic\'s Book of Food and Drink (1946) as "Mexican El Diablo." One of the earliest published tequila cocktails in the American market, predating widespread tequila popularity by decades. The blackcurrant-ginger combination is unique among tequila highballs.',
    ingredients: [
      { name: 'Blanco tequila',   amount:   45, unit: 'ml' },
      { name: 'Crème de cassis',  amount:   15, unit: 'ml' },
      { name: 'Fresh lime juice', amount:   15, unit: 'ml' },
      { name: 'Ginger beer',      amount: null, unit: 'to top' },
    ],
    method: 'Build in a highball glass over ice. Add tequila, cassis, lime. Top with cold ginger beer. Stir gently.',
    glassware: 'Highball',
    garnish: 'Lime wedge',
    tags: ['built', 'highball', 'tequila', 'ginger', 'blackcurrant', 'tiki', 'historic'],
    notes: 'The crème de cassis adds deep berry notes that transform a standard tequila-ginger highball into something genuinely unusual and complex.',
  },

  {
    id: 'tom-collins',
    name: 'Tom Collins',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Highball',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Published in Jerry Thomas\'s 1876 Bartender\'s Guide, though likely older. Originally made with Old Tom (sweetened) gin, which gave the drink its name. A Collins is any sour built with soda water — the John Collins uses genever, the Vodka Collins substitutes vodka, and so on through the spirit family.',
    ingredients: [
      { name: 'London dry gin',   amount:   50, unit: 'ml' },
      { name: 'Fresh lemon juice', amount:  25, unit: 'ml' },
      { name: 'Simple syrup',     amount:   15, unit: 'ml' },
      { name: 'Soda water',       amount: null, unit: 'to top' },
    ],
    method: 'Combine gin, lemon, and syrup in a highball glass. Add ice. Top with soda. Stir gently once. Do not shake — maintain carbonation.',
    glassware: 'Highball',
    garnish: 'Orange slice, cherry',
    tags: ['built', 'highball', 'IBA', 'gin', 'classic', 'citrus', 'low-prep'],
    notes: 'Do not shake — carbonation is lost and the long, refreshing texture that defines a Collins disappears. Build directly in the glass.',
  },

  // ── TROPICAL / TIKI (4) ────────────────────────────────────────────────────

  {
    id: 'pina-colada',
    name: 'Piña Colada',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Tropical',
    family: 'Rum',
    baseSpirit: 'White Rum',
    story: 'Puerto Rico\'s national drink, with disputed origin between Ramón Marrero at the Caribe Hilton in San Juan (1954) and Ramón Portas Mingot at Barrachina Restaurant (1963). The frozen version became a global phenomenon once blenders became standard bar equipment in the 1970s.',
    ingredients: [
      { name: 'White rum',       amount: 50, unit: 'ml' },
      { name: 'Coconut cream',   amount: 30, unit: 'ml' },
      { name: 'Pineapple juice', amount: 90, unit: 'ml' },
    ],
    method: 'Blend all ingredients with a cup of crushed ice until smooth. Pour into a large chilled glass.',
    glassware: 'Wine Glass',
    garnish: 'Pineapple wedge, cherry, cocktail umbrella',
    tags: ['blended', 'tropical', 'IBA', 'rum', 'coconut', 'pineapple', 'puerto-rico', 'classic'],
    notes: 'Coco López (sweetened coconut cream) is the traditional ingredient. Unsweetened coconut cream with added sugar gives more control over sweetness. The drink should not be cloying.',
  },

  {
    id: 'mai-tai',
    name: 'Mai Tai',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Tropical',
    family: 'Rum',
    baseSpirit: 'Rum',
    story: 'Created by Trader Vic (Victor Bergeron) at his Oakland restaurant in 1944. Reportedly served to two Tahitian friends who exclaimed "Mai Tai — Roa Ae!" meaning "out of this world — the best." Bastardised for decades with cheap syrups, then restored by the craft tiki revival.',
    ingredients: [
      { name: 'Aged Jamaican rum',             amount: 30, unit: 'ml' },
      { name: 'Aged Martinique rum (agricole)', amount: 30, unit: 'ml' },
      { name: 'Fresh lime juice',              amount: 30, unit: 'ml' },
      { name: 'Orange curaçao',               amount: 15, unit: 'ml' },
      { name: 'Orgeat',                        amount: 15, unit: 'ml' },
    ],
    method: 'Combine all ingredients in a shaker with ice. Shake. Strain into a rocks glass or tiki mug over crushed ice.',
    glassware: 'Rocks Glass',
    garnish: 'Spent lime half, mint sprig',
    tags: ['shaken', 'tropical', 'tiki', 'IBA', 'rum', 'orgeat', 'classic', 'trader-vic'],
    notes: 'The split rum base — Jamaican funk and Martinique agricole grassiness — is essential to the drink\'s complexity. Single-rum versions miss the agricultural contrast.',
  },

  {
    id: 'zombie',
    name: 'Zombie',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Tropical',
    family: 'Rum',
    baseSpirit: 'Rum',
    story: 'Created by Donn Beach (Don the Beachcomber) around 1934. The original recipe was closely guarded for decades until Jeff Berry researched and reconstructed it in the 1990s. Donn limited customers to two per visit. The drink defined the high-proof, multi-rum tiki format.',
    ingredients: [
      { name: 'White Puerto Rican rum',             amount: 45, unit: 'ml' },
      { name: 'Gold Jamaican rum',                  amount: 30, unit: 'ml' },
      { name: 'Demerara rum (151-proof)',            amount: 30, unit: 'ml' },
      { name: 'Fresh lime juice',                   amount: 20, unit: 'ml' },
      { name: 'Don\'s Mix (grapefruit:cinnamon 2:1)', amount: 15, unit: 'ml' },
      { name: 'Falernum',                           amount: 15, unit: 'ml' },
      { name: 'Grenadine',                          amount:  7, unit: 'ml' },
      { name: 'Angostura bitters',                  amount:  1, unit: 'dash' },
    ],
    method: 'Blend all ingredients with crushed ice for 5 seconds. Pour into a zombie glass or tiki mug. Add more crushed ice.',
    glassware: 'Highball',
    garnish: 'Mint bouquet, spent lime half',
    tags: ['blended', 'tropical', 'tiki', 'rum', 'high-abv', 'classic', 'donn-beach'],
    notes: 'Don\'s Mix: blend 2 parts fresh grapefruit juice with 1 part cinnamon syrup. This is a very high-ABV drink — the two-per-customer limit is historically appropriate and practically sound.',
  },

  {
    id: 'singapore-sling',
    name: 'Singapore Sling',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Tropical',
    family: 'Gin',
    baseSpirit: 'Gin',
    story: 'Created by Ngiam Tong Boon at the Long Bar of Raffles Hotel, Singapore, around 1915. Designed to allow women to drink in public without the appearance of consuming alcohol — the pink colour resembled fruit juice. The original recipe was lost; the current Raffles version may not precisely match the original.',
    ingredients: [
      { name: 'Gin',                amount:   30, unit: 'ml' },
      { name: 'Cherry Heering',     amount:   15, unit: 'ml' },
      { name: 'Cointreau',          amount:    7, unit: 'ml' },
      { name: 'Bénédictine',        amount:    7, unit: 'ml' },
      { name: 'Fresh pineapple juice', amount: 90, unit: 'ml' },
      { name: 'Fresh lime juice',   amount:   15, unit: 'ml' },
      { name: 'Grenadine',          amount:   10, unit: 'ml' },
      { name: 'Angostura bitters',  amount:    1, unit: 'dash' },
      { name: 'Soda water',         amount: null, unit: 'to top' },
    ],
    method: 'Shake all ingredients except soda with ice. Strain into a highball or hurricane glass over ice. Top with soda.',
    glassware: 'Highball',
    garnish: 'Pineapple slice, cherry',
    tags: ['shaken', 'tropical', 'IBA', 'gin', 'singapore', 'historic', 'raffles'],
    notes: 'Cherry Heering and Bénédictine are the flavour pillars — do not substitute. The Raffles recipe is the reference point but its historical accuracy is disputed.',
  },

  // ── POPULAR CLASSICS (4) ───────────────────────────────────────────────────

  {
    id: 'tequila-sunrise',
    name: 'Tequila Sunrise',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Popular Classic',
    family: 'Tequila',
    baseSpirit: 'Tequila',
    story: 'The modern version — tequila, orange juice, grenadine — was created by Bobby Lozoff and Billy Rice at The Trident in Sausalito, California in 1972. The Rolling Stones ordered it throughout their 1972 American tour, cementing its cultural status. An earlier Arizona Biltmore version used cassis.',
    ingredients: [
      { name: 'Blanco tequila',   amount:   50, unit: 'ml' },
      { name: 'Fresh orange juice', amount: null, unit: 'to fill (~120 ml)' },
      { name: 'Grenadine',        amount:   15, unit: 'ml' },
    ],
    method: 'Fill a highball glass with ice. Add tequila and orange juice. Do not stir. Slowly pour grenadine down the inside of the glass — it will sink and create the gradient.',
    glassware: 'Highball',
    garnish: 'Orange slice, cherry',
    tags: ['built', 'popular-classic', 'tequila', 'orange', 'grenadine', '1970s', 'IBA'],
    notes: 'Do not stir after adding grenadine — the gradient represents sunrise colours and will mix as the drink is consumed.',
  },

  {
    id: 'sex-on-the-beach',
    name: 'Sex on the Beach',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Popular Classic',
    family: 'Vodka',
    baseSpirit: 'Vodka',
    story: 'Created by Ted Pizio in Florida in 1987 during a contest to sell the most peach schnapps. The evocative name was a deliberate sales tactic. Became one of the defining cocktails of the 1980s beach bar scene and remains one of the most ordered cocktails globally by volume.',
    ingredients: [
      { name: 'Vodka',           amount: 45, unit: 'ml' },
      { name: 'Peach schnapps',  amount: 30, unit: 'ml' },
      { name: 'Orange juice',    amount: 60, unit: 'ml' },
      { name: 'Cranberry juice', amount: 60, unit: 'ml' },
    ],
    method: 'Build in a highball glass over ice. Add vodka, peach schnapps, orange juice, cranberry juice. Stir gently.',
    glassware: 'Highball',
    garnish: 'Orange slice, cherry',
    tags: ['built', 'popular-classic', 'vodka', 'fruity', 'IBA', '1980s'],
    notes: 'Proportions vary — more cranberry deepens the colour; less gives a brighter orange tone. Fresh orange juice improves the result significantly.',
  },

  {
    id: 'harvey-wallbanger',
    name: 'Harvey Wallbanger',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Popular Classic',
    family: 'Vodka',
    baseSpirit: 'Vodka',
    story: 'Created by Donato "Duke" Antone in Los Angeles around 1952, named after a surfer called Harvey who allegedly knocked himself into a wall after too many. Became a US phenomenon in the 1970s following a Galliano marketing campaign — effectively a Screwdriver with a Galliano float.',
    ingredients: [
      { name: 'Vodka',                  amount:   45, unit: 'ml' },
      { name: 'Fresh orange juice',     amount: null, unit: 'to fill (~120 ml)' },
      { name: 'Galliano L\'Autentico', amount:   15, unit: 'ml' },
    ],
    method: 'Fill a highball glass with ice. Add vodka and orange juice. Float Galliano on top.',
    glassware: 'Highball',
    garnish: 'Orange slice, cherry',
    tags: ['built', 'popular-classic', 'vodka', 'orange', 'galliano', '1970s'],
    notes: 'Galliano\'s herbal, vanilla-anise flavour is what defines this drink. Without the float it is simply a Screwdriver.',
  },

  {
    id: 'long-island-iced-tea',
    name: 'Long Island Iced Tea',
    libraryType: 'core_classic',
    readOnly: true,
    category: 'Popular Classic',
    family: 'Multi-Spirit',
    baseSpirit: 'Vodka',
    story: 'Claimed by Robert "Rosebud" Butt at Oak Beach Inn, Long Island, New York, around 1972, where he created it for a cocktail contest. Despite its ingredients, a correctly proportioned Long Island Iced Tea does taste like iced tea, due to the lemon-cola combination.',
    ingredients: [
      { name: 'Vodka',          amount:   15, unit: 'ml' },
      { name: 'Gin',            amount:   15, unit: 'ml' },
      { name: 'White rum',      amount:   15, unit: 'ml' },
      { name: 'Blanco tequila', amount:   15, unit: 'ml' },
      { name: 'Triple sec',     amount:   15, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 25, unit: 'ml' },
      { name: 'Simple syrup',   amount:   10, unit: 'ml' },
      { name: 'Cola',           amount: null, unit: 'to top' },
    ],
    method: 'Combine all ingredients except cola in a shaker with ice. Shake. Strain into a highball glass over ice. Top with a splash of cola for colour.',
    glassware: 'Highball',
    garnish: 'Lemon wedge',
    tags: ['shaken', 'popular-classic', 'multi-spirit', 'high-abv', 'IBA', '1970s'],
    notes: 'The cola is for colour only — it creates the iced tea appearance. The lemon and syrup provide balance. A well-made LIIT should be refreshing, not cloying.',
  },
]
