// ─── Wine Atlas seed data ─────────────────────────────────────────────────────
// Phase 2: content drawn directly from:
//   • Sommelier Intelligence System Research.pdf (HESTIA / 41 pages)
//   • Luxury Wine Intelligence Research Prompt.pdf (HESTIA / 24 pages)
// Every claim is sourced. No fabrication.

// ─── HOME PAGE FEATURED REGIONS (6) ──────────────────────────────────────────
// Used in AtlasHome hero "The Regions" dark section
export const REGIONS = [
  {
    n: 'I',
    name: 'Santorini',
    country: 'Greece',
    grape: 'Assyrtiko',
    lat: '36.4°N',
    geology: 'Basalt, pumice, volcanic ash (aspa) — zero clay, zero organic matter',
    climate: 'Arid maritime; hyper-arid, fierce Aegean winds, extreme UV exposure',
    structuralProfile: 'High acid, medium-to-full body, low tannin. Bone-dry with laser-like acidity and saline-bitter finish.',
    story: 'To stand on the cliffs of Santorini is to witness a viticultural battlefield where life clings to fire and dust. The wind here is a physical force, screaming across the caldera and whipping the volcanic soil into a frenzy. The vines do not rise to meet the sun; instead, they cower in tight, hand-woven nests of wood — the ancient kouloura — hunkered close to the black basalt and white pumice.',
    tastingNote: 'Preserved lemon, white peach, crushed oyster shell, and a profound smoky volcanic saltiness. Bone-dry palate, laser-like acidity, dense phenolic weight, lingering saline-bitter finish.',
    foodPairing: 'Grilled octopus brushed with olive oil and capers — the wine cuts through dense texture and mirrors the oceanic salinity of the dish.',
  },
  {
    n: 'II',
    name: 'Douro Valley',
    country: 'Portugal',
    grape: 'Touriga Nacional',
    lat: '41.1°N',
    geology: 'Metamorphic schist (xisto) — highly laminated phyllite and slate fracturing vertically, allowing vine roots to drill up to 15m deep',
    climate: 'Hot, arid continental. Surribar deep-ripping of rock required for root penetration.',
    structuralProfile: 'Medium acid, high tannin, full body. Deep opaque ruby-black. Wild blackberry, dark plum, tobacco leaf, wet slate.',
    story: 'The Douro Valley is a monument to human determination, where steep mountainsides are carved into terraced stone steps that look like a giant staircase rising from the river. The soil is not earth, but a gray, glittering sea of fractured schist that absorbs the heat of the summer sun, radiating it back to the vines under a cloudless sky.',
    tastingNote: 'Deep opaque ruby-black. Intense aromas of wild blackberry, dark plum, dark chocolate, tobacco leaf, wet slate. Full-bodied, firm muscular tannins, dense mid-palate, long warm finish with lingering graphite.',
    foodPairing: 'Pan-seared venison loin with a blackberry reduction — the gamey fats and proteins intercept the tannins, dissolving the harshness and revealing vibrant blackberry and dark chocolate.',
  },
  {
    n: 'III',
    name: 'Wachau',
    country: 'Austria',
    grape: 'Riesling',
    lat: '48.4°N',
    geology: 'Gföhl gneiss — highly migmatitic granitic crystalline rock composed of quartz, feldspar, and biotite mica; restricts vine vigor and forces deep root development',
    climate: 'Cool-climate continental. Danube River moderates extremes; dry-stone walls retain heat.',
    structuralProfile: 'High acid, medium-to-full body, low tannin. Bone-dry Smaragd-classified expressions with crystalline mineral tension.',
    story: 'The Wachau is a landscape of stark beauty, where the Danube River winds beneath terraced stone cliffs that seem to rise straight out of the water. These dry-stone walls, built by hand over centuries, hold back thin, rocky soils that glisten with flakes of mica. In spring, apricot blossoms fill the valley with colour; in autumn, the terraced slopes turn a brilliant gold.',
    tastingNote: 'Intensely aromatic — lime zest, ripe white peach, wet slate, jasmine, petrol. Bone-dry, powerful, and concentrated with high acidity and a long finish of crushed stones.',
    foodPairing: 'Roasted sweetbreads or pan-seared sea bass with lemon-herb butter — the Smaragd\'s stone-fruit concentration and high acidity cut through rich textures.',
  },
  {
    n: 'IV',
    name: 'Tokaj',
    country: 'Hungary',
    grape: 'Furmint',
    lat: '48.1°N',
    geology: 'Mosaic of rhyolite tuff, andesite, dacite, zeolite, clay, and loess — approximately 400 extinct volcanoes',
    climate: 'Moderate continental with autumn river mists from the Bodrog and Tisza confluence, promoting Botrytis cinerea',
    structuralProfile: 'High acid, full body, low tannin. Dacite slopes yield aromatic, smooth-textured wines; basalt and rhyolite tuff yield flinty, smoky, salty dry expressions.',
    story: 'To enter the ancient cellars of Tokaj is to step back in time. Carved deep into volcanic tufa rock, the cellar walls are covered in a thick, velvety black mould (Cladosporium cellare) that thrives on the evaporating alcohol, keeping the air remarkably clean and humid. Outside, the autumn air is thick with river mist, wrapping the vines in a soft blanket that coaxes the grapes into noble rot.',
    tastingNote: 'Dry Furmint (Mád Basin): pale lemon-green, aromas of green pear, quince, fresh ginger, crushed chalk, woodsmoke. Bone-dry, high acidity, mineral texture, salty finish.',
    foodPairing: 'Dry Furmint: slow-roasted pork belly with crispy crackling. Tokaji Aszú: salty blue cheeses such as Roquefort — salt in the cheese balances sweetness while highlighting fruit flavours.',
  },
  {
    n: 'V',
    name: 'Naoussa',
    country: 'Greece',
    grape: 'Xinomavro',
    lat: '40.6°N',
    geology: 'Limestone-rich clay over marl bedrock; well-draining slopes in the Macedonian highlands',
    climate: 'Moderate continental; mist-shrouded mountain amphitheatre',
    structuralProfile: 'High acid, high tannin, medium body. Pale translucent garnet with copper rim. Extended maceration; large neutral oak aging required.',
    story: 'In Naoussa, the landscape changes to a green, mist-shrouded mountain amphitheatre. Here, Xinomavro — "acid-black" — vines dig their roots into ancient limestone, absorbing the quiet moisture of the Macedonian hills. This structure requires extended bottle aging to polymerize its phenolic compounds, eventually revealing a complex array of volatile aromas structurally identical to Piedmontese Nebbiolo.',
    tastingNote: 'Translucent garnet-ruby. Wild strawberry, red cherry, sun-dried tomato leaf, black olive tapenade, dried earth, leather. High aggressive tannins, piercing acidity, lean mid-palate, savory forest-floor finish.',
    foodPairing: 'Slow-roasted lamb shoulder encrusted with rosemary and garlic — the fat binds with the grape\'s polyphenols, highlighting its savory red fruit.',
  },
  {
    n: 'VI',
    name: 'Golan Heights',
    country: 'Israel',
    grape: 'Cabernet Sauvignon',
    lat: '33.1°N',
    geology: 'Deep basalt clay and volcanic tuff, rich in iron and minerals; high-altitude plateau above 900m',
    climate: 'Cool montane continental; cold snowy winters, warm summers, large diurnal temperature swings',
    structuralProfile: 'High acidity, firm tannins, full body, exceptional aging potential. LODI RULES certified sustainable.',
    story: 'To stand on the volcanic plateau of the Golan Heights is to feel the cool wind blowing off the snow-covered peak of Mount Hermon, carrying the scent of wild herbs and wet stone. The vines grow in deep, dark basalt soils, their green leaves contrasting with the black volcanic rock — producing wines that share the power and intensity of Napa Valley mountain Cabernets but carry a distinct, iron-like volcanic minerality.',
    tastingNote: 'Deep purple-black. Aromas of blackberry, black plum, freshly cracked black pepper, smoked meat, and iron. Full-bodied, vibrant acidity, firm tannins, long savory finish.',
    foodPairing: 'Grilled ribeye steak with a savory pepper crust — the wine\'s black pepper and smoky notes align with the charred crust.',
  },
]

// ─── COUNTRIES (AtlasRegions page) ───────────────────────────────────────────
export const COUNTRIES = [
  { name: 'France',       regions: ['Burgundy', 'Bordeaux', 'Champagne', 'Rhône', 'Loire', 'Alsace'] },
  { name: 'Italy',        regions: ['Piedmont', 'Tuscany', 'Veneto', 'Sicily', 'Friuli'] },
  { name: 'Spain',        regions: ['Rioja', 'Ribera del Duero', 'Priorat', 'Rías Baixas'] },
  { name: 'Germany',      regions: ['Mosel', 'Rheingau', 'Pfalz', 'Nahe'] },
  { name: 'Portugal',     regions: ['Douro Valley', 'Dão', 'Alentejo', 'Vinho Verde'] },
  { name: 'Austria',      regions: ['Wachau DAC', 'Kremstal DAC', 'Kamptal', 'Burgenland'] },
  { name: 'Greece',       regions: ['Santorini PDO', 'Naoussa PDO', 'Nemea', 'Assyrtiko regions'] },
  { name: 'Hungary',      regions: ['Tokaj', 'Somló', 'Eger', 'Villány'] },
  { name: 'Israel',       regions: ['Golan Heights', 'Judean Hills', 'Galilee', 'Negev Desert'] },
  { name: 'USA',          regions: ['Napa Valley', 'Sonoma', 'Willamette Valley', 'Finger Lakes'] },
  { name: 'Argentina',    regions: ['Mendoza', 'Uco Valley', 'Salta'] },
  { name: 'Australia',    regions: ['Barossa Valley', 'Margaret River', 'Yarra Valley'] },
]

// ─── HOME PAGE GRAPE INDEX (6 entries) ───────────────────────────────────────
export const GRAPES_INDEX = [
  { name: 'Assyrtiko',          color: 'White', structure: 'High acid · Volcanic salinity · Bone-dry',      home: 'Santorini' },
  { name: 'Pinot Noir',         color: 'Red',   structure: 'High acid · Soft tannin · Cool-climate red',    home: 'Burgundy' },
  { name: 'Riesling',           color: 'White', structure: 'High acid · TDN petrol with age · Zero oak',    home: 'Wachau / Mosel' },
  { name: 'Nebbiolo',           color: 'Red',   structure: 'High acid · High tannin · Pale, translucent',   home: 'Piedmont' },
  { name: 'Cabernet Sauvignon', color: 'Red',   structure: 'Full · High tannin · Methoxypyrazine structure',home: 'Bordeaux' },
  { name: 'Furmint',            color: 'White', structure: 'High acid · Botrytis-prone · Volcanic mineral',  home: 'Tokaj' },
]

// ─── GRAPES FULL (12 entries, AtlasGrapes page) ──────────────────────────────
// notes: primary sensory compounds drawn from Sommelier & Luxury PDFs
// Extra fields (compounds, terroir, foodPairing, story) are available for
// Phase 3 component enrichment — components currently render only the base fields
export const GRAPES_FULL = [
  {
    name: 'Cabernet Sauvignon',
    color: 'Red',
    home: 'Bordeaux / Napa',
    notes: 'Blackcurrant · Graphite · Cedar · Green bell pepper (methoxypyrazines)',
    body: 5, acid: 4, tannin: 5,
    compounds: 'Methoxypyrazines (2-methoxy-3-isobutylpyrazine) — green bell pepper and asparagus in cool climates; norisoprenoids in warm climates. Thick skins require consistent heat to ripen dense tannins and phenolics.',
    terroir: 'Thrives on warm, well-draining soils — gravel, terra rossa, limestone clay. Cool climates retain harsh green pyrazines; warm, well-draining soils achieve full ripeness, yielding structured, age-worthy expressions.',
    structuralProfile: 'Late-ripening, thick-skinned, loose clusters. High acid, high tannin, full body. Opaque deep ruby-purple colour.',
    foodPairing: 'Prime ribeye steak — the meat\'s fat binds with the grape\'s polyphenols, highlighting dark fruit. Tannins require protein and fat to soften their grip on the tongue.',
    story: 'Thick-skinned Cabernet Sauvignon grapes bask in the intense summer heat on warm gravels, building the deep colours and powerful structure that will allow the finished wine to age gracefully for decades in the dark silence of the cellar.',
  },
  {
    name: 'Pinot Noir',
    color: 'Red',
    home: 'Burgundy / Côte de Nuits',
    notes: 'Red cherry · Raspberry · Forest floor · Dried rose petals · Truffle with age',
    body: 2, acid: 4, tannin: 2,
    compounds: 'Volatile esters (red cherry, strawberry) and monoterpenes. Thin skins produce low tannin concentration; tight compact clusters make the variety highly susceptible to botrytis and fungal diseases.',
    terroir: 'Cool to moderate climates; limestone loam, marl, cool slate. Earthy forest floor and red cherry on the Côte de Nuits. Translucent colour is a diagnostic indicator at blind tastings.',
    structuralProfile: 'Early-ripening, thin-skinned, disease-prone. High acid, low-to-medium tannin, light-to-medium body. Pale ruby with garnet rim; pronounced rim variation with age.',
    foodPairing: 'Roasted duck breast with wild mushroom risotto — the wine\'s high acidity cuts through fatty duck while its herbal undertones align with the savory mushrooms.',
    story: 'The fragile, light-skinned Pinot Noir vine sits quietly in the morning fog, its small clusters clinging to limestone slopes as it slowly develops its complex, delicate red fruit flavours. This is the translucent aristocrat of Burgundy — thin-skinned, restless, and almost impossible to grow well.',
  },
  {
    name: 'Nebbiolo',
    color: 'Red',
    home: 'Piedmont / Barolo',
    notes: 'Dried rose petals · Tar · Sour cherry · Truffle · Violets when young',
    body: 4, acid: 5, tannin: 5,
    compounds: 'High concentrations of rustic, grippy tannins and aggressive natural acidity. Structurally identical to Naoussa Xinomavro — both share high acidity, powerful tannins, and pale translucent colour. Nebbiolo is distinguished by its classic tar and rose petals; Xinomavro by green olive and tomato leaf.',
    terroir: 'Calcareous marl in the Langhe hills. Late-ripening; requires a specific south-facing aspect to achieve full phenolic ripeness. Thin skins lack sufficient anthocyanins to bind tannins, leaving them unpolymerized and highly astringent in youth.',
    structuralProfile: 'Pale translucent garnet, high acid, high tannin, medium-to-full body. Extended maceration and large neutral oak aging required to integrate the phenolic structure.',
    foodPairing: 'Braised veal cheek with truffle — the game and fat soften the tannin architecture; the truffle aroma mirrors the wine\'s tertiary forest-floor notes.',
    story: 'At blind tastings, Nebbiolo presents its signature contradiction: a pale, translucent colour that suggests lightness, paired with tannins that grip the gums with the intensity of iron. A wine of extraordinary aging potential that begins its life as near-undrinkable and ends as sublime.',
  },
  {
    name: 'Syrah',
    color: 'Red',
    home: 'Northern Rhône / Golan Heights',
    notes: 'Freshly cracked black pepper (rotundone) · Smoked meat · Dark olive · Bramble',
    body: 4, acid: 4, tannin: 4,
    compounds: 'Rotundone — the sesquiterpene responsible for Syrah\'s signature black pepper aroma — accumulates in grape skins between veraison and harvest and is perceptible at parts-per-trillion levels. Cool-climate Northern Rhône style: high acidity, firm tannins, elegant black pepper and savory smoked meat. Warm-climate Australian Shiraz: full body, soft tannins, ripe black fruit, sweet spice.',
    terroir: 'Decomposing granite and schist in the Northern Rhône; volcanic basalt in the Golan Heights (Iron-rich minerals). Mid-to-late ripening, vigorous, cold-sensitive.',
    structuralProfile: 'Medium-to-high acid, high tannin, full body. Deep purple-black colour. The peppery aroma of Syrah or Grüner Veltliner is driven by the same sesquiterpene: rotundone.',
    foodPairing: 'Grilled ribeye steak with a savory pepper crust — the rotundone in the wine amplifies the pepper character of the crust. Smoked lamb also works well with Northern Rhône expressions.',
    story: 'Inside the quiet, charred staves of a French oak barrel, a slow and silent alchemy is underway. The young Syrah, rough and crimson-purple, rests in darkness, drawing minuscule gasps of oxygen through the wood pores, slowly transforming its raw, aggressive tannins into long, soft polymer chains.',
  },
  {
    name: 'Grenache',
    color: 'Red',
    home: 'Châteauneuf-du-Pape / Priorat',
    notes: 'Wild strawberry · Garrigue · Dried herbs · Warm spice · Kirsch',
    body: 3, acid: 3, tannin: 2,
    compounds: 'Low natural acidity; thin skins produce lighter-coloured, low-tannin wines. Warm climate accumulation of high sugar levels. Garrigue character derives from volatile terpenes shared with the wild herbs of the Mediterranean scrubland.',
    terroir: 'Hot Mediterranean climates; sandy, schist, and granite soils. A high-alcohol, low-tannin grape that thrives in warm, windswept sites. Often blended with Mourvèdre and Syrah.',
    structuralProfile: 'Medium body, medium-to-low acid, low tannin. Medium-ruby with orange rim on older wines. High potential alcohol can tip into flabbiness in extreme heat without careful harvesting.',
    foodPairing: 'Roast chicken with herbs de Provence — the garrigue aromatic character of the wine mirrors the herb-driven cooking, while the low tannin avoids overwhelming the white meat.',
    story: 'In the windswept plateaux of Châteauneuf-du-Pape, ancient Grenache vines grow from round galettes — flat, heat-retaining limestone pebbles that absorb the Provençal sun and radiate warmth long into the cool nights, producing wines of extraordinary richness and aromatic complexity.',
  },
  {
    name: 'Tempranillo',
    color: 'Red',
    home: 'Rioja / Ribera del Duero',
    notes: 'Cherry · Leather · Tobacco · Dill · Warm oak spice (eugenol)',
    body: 3, acid: 3, tannin: 3,
    compounds: 'Eugenol — the volatile phenol derived from lignin breakdown in toasted oak — dominates both whole cloves and Tempranillo wines aged in toasted oak barrels. Molecular harmony: ingredients rich in eugenol (red beets, Thai basil) create aromatic synergies with oaked Rioja.',
    terroir: 'Clay-limestone and alluvial soils in Rioja Alta and Rioja Alavesa. Mid-ripening; moderately resistant to drought. Traditional aging in American oak contributes strong coconut and vanilla notes from cis-lactones; modern expressions favor French oak for subtler integration.',
    structuralProfile: 'Medium body, medium acid, medium tannin. Bright ruby colour. Gran Reserva aging polymerizes tannins into silky, integrated forms; secondary leather and tobacco notes develop from bottle age.',
    foodPairing: 'Slow-roasted lamb with rosemary — the eugenol in the wine\'s oak character aligns with the herbal cooking notes; the medium tannins handle the lamb\'s fat without overwhelming its delicacy.',
    story: 'In a Rioja barrel room, the sharp smell of toasted American oak fills the silence. Tempranillo matures slowly in these vanilla-scented chambers, absorbing the coconut and dill of the cis-oak lactones before emerging as the leather-and-tobacco-laced wine that defines Spain\'s most celebrated red tradition.',
  },
  {
    name: 'Sangiovese',
    color: 'Red',
    home: 'Tuscany / Chianti',
    notes: 'Sour cherry · Tomato leaf · Iron · Wild herbs · Balsamic with age',
    body: 3, acid: 5, tannin: 4,
    compounds: 'Extremely high titratable acidity — one of Italy\'s most acid-forward red grapes. The tomato-leaf and herb character derives from volatile green compounds in the skin. High acid pairs naturally with the high-acid tomato-based sauces of central Italian cuisine.',
    terroir: 'Galestro and alberese soils (schistose clay-limestone mixtures) of the Chianti Classico DOCG. Mid-late ripening; responsive to elevation — higher-altitude plantings preserve acidity and aromatic freshness.',
    structuralProfile: 'Medium body, very high acid, high tannin. Bright ruby with brick-orange rim on aged expressions. Sour cherry acidity is the diagnostic marker on the palate.',
    foodPairing: 'Bistecca alla Fiorentina — the high acidity cuts through the charred fat of the Florentine steak; the iron-like mineral note mirrors the bloodiness of rare meat.',
    story: 'Sangiovese is the backbone of Chianti, Brunello, and Morellino — a grape of extreme acidity and rustic tannin that demands patience. In the ancient hill towns above Florence, it ages in large Slavonian oak botti, slowly transforming its aggressive youth into the nuanced, balsamic complexity of a great Brunello di Montalcino.',
  },
  {
    name: 'Chardonnay',
    color: 'White',
    home: 'Burgundy / Champagne',
    notes: 'Apple · Lemon curd · Hazelnut · Butter (diacetyl) · Vanilla when oaked',
    body: 4, acid: 3, tannin: 0,
    compounds: 'Esters and diacetyl (buttery aromatics from malolactic fermentation). Chardonnay acts as a blank canvas for winemaking: barrel fermentation allows yeast to metabolize vanillin into integrated vanillyl alcohol; lees contact adds creamy texture (bâtonnage); MLF converts malic to lactic acid, softening acidity. An early-budding variety, making it frost-prone.',
    terroir: 'Limestone, clay-limestone, chalk. Highly responsive to winemaking technique — the same grape produces austere Chablis (no oak, no malolactic) and lush Napa Chardonnay (barrel-fermented, fully malo\'d) in completely different expressions.',
    structuralProfile: 'Early budding, early ripening. Medium-to-high acid (if no malolactic), low tannin, medium-to-full body. Pale lemon-gold when unoaked; deep gold when barrel-fermented and aged.',
    foodPairing: 'Oak-aged Chardonnay: pan-seared scallops or grilled lobster tail with drawn butter — the wine\'s caramel and vanilla characters match the smoky, caramelized sweetness of the seafood.',
    story: 'Of all the noble grapes, Chardonnay alone offers the winemaker a choice: render it into mineral tension and green acidity in cold stainless steel, or swathe it in the warmth of new French oak, transforming it through the dairy chemistry of malolactic fermentation into something golden and voluptuous.',
  },
  {
    name: 'Riesling',
    color: 'White',
    home: 'Wachau / Mosel',
    notes: 'Lime zest · White peach · Wet slate · Jasmine · Petrol (TDN with age)',
    body: 1, acid: 5, tannin: 0,
    compounds: 'High natural acidity balanced by intense monoterpene aromatics (citrus peel, white flowers). With age, Riesling accumulates 1,1,6-trimethyl-1,2-dihydronaphthalene (TDN), which contributes its signature petrol aroma. A late-ripening, cold-hardy variety with wood highly resistant to frost.',
    terroir: 'Primary rock, gneiss, slate, volcanic soils. Gföhl gneiss in the Wachau restricts vine vigor, forcing deep roots that yield structured, mineral-driven wines. Stainless steel fermentation, zero malolactic, zero oak preserves the pure mineral expression.',
    structuralProfile: 'Late ripening, cold-hardy, susceptible to noble rot. Very high acid, low-to-medium body, zero tannin. Bone-dry Smaragd (Wachau) to intensely sweet TBA (Germany). Often confused with Grand Cru Chablis or Santorini Assyrtiko but distinguished by higher natural alcohol in dry expressions and TDN petrol character with age.',
    foodPairing: 'Off-dry German Riesling with spicy Thai curry — residual sugar calms the capsaicin burn while low alcohol prevents throat irritation. Dry Wachau Smaragd with roasted sweetbreads or sea bass with lemon-herb butter.',
    story: 'Uncorking a matured bottle of Riesling, the vapor rises, carrying a whisper of dry petrol, lime peel, and wet slate. Instantly, the modern tasting room dissolves, replaced by the cool, damp air of an old stone cellar along the Danube. The mind does not merely recall the place — it feels the weight of the humid air, the damp moss on the stones, the quiet hum of the river outside.',
  },
  {
    name: 'Sauvignon Blanc',
    color: 'White',
    home: 'Loire / Marlborough',
    notes: 'Gooseberry · Fresh-cut grass · Grapefruit · Passion fruit · Elderflower',
    body: 2, acid: 5, tannin: 0,
    compounds: 'Methoxypyrazines (grass, green bell pepper, gooseberry) dominate in cool climates. Thiols — 3-mercaptohexanol (3MH) and 3-mercaptohexyl acetate (A3MH) — exist as odorless precursors bound to amino acids in the grape pulp, unlocked by yeast enzymes during fermentation to release tropical notes of grapefruit and passion fruit in warmer climates. A vigorous, early-ripening grape requiring careful canopy management.',
    terroir: 'Limestone, chalk, gravel, sand. Cool climates yield high methoxypyrazines (grass, green bell pepper); warm climates shift the profile toward tropical thiols (passion fruit, mango) and lower natural acidity. Sancerre and Pouilly-Fumé grow on Kimmeridgian limestone and chalk.',
    structuralProfile: 'Highly vigorous, early ripening. Very high acid, low tannin, medium body. Pale green-yellow colour. Temperature-controlled stainless steel; some oak contact produces the Fumé Blanc style.',
    foodPairing: 'Fresh goat cheese — the high acidity acts as a palate cleanser, cutting through the rich creamy texture. Grilled asparagus with vinaigrette: the pyrazine green character mirrors the vegetable\'s herbal notes. Oysters with dry Muscadet works on the same principle.',
    story: 'In Marlborough\'s cool Wairau Valley, the morning air carries the scent of fresh-cut grass and elderflower from vineyards trained on high trellises. Here, the thiol precursors are locked inside the pulp — odorless until a specific yeast enzyme cracks them open during fermentation, releasing the tropical perfume that made New Zealand Sauvignon Blanc famous almost overnight.',
  },
  {
    name: 'Chenin Blanc',
    color: 'White',
    home: 'Vouvray / Swartland',
    notes: 'Quince · Wild honey · Beeswax · Green apple · Lanolin',
    body: 3, acid: 4, tannin: 0,
    compounds: 'Extraordinary versatility: the same grape produces bone-dry Savennières with high acidity and lean mineral tension, honeyed demi-sec Vouvray from late harvest, and luscious botrytized Coteaux du Layon. High natural acidity acts as a natural preservative, giving Chenin exceptional aging potential.',
    terroir: 'Tuffeau (volcanic chalk), schist, and clay in the Loire Valley. Swartland schist produces a richer, more textured style. Late-ripening in cool years allows noble rot development; warm years produce bone-dry expressions of great tension.',
    structuralProfile: 'Medium body, high acid, zero tannin. Pale gold to deep amber depending on style and age. One of the world\'s most versatile white grapes — the full stylistic spectrum from sparkling to botrytized.',
    foodPairing: 'Rich pork rillettes — the wine\'s high acidity and beeswax weight cut through the confit fat. Demi-sec Vouvray with blue-veined cheese: the sweetness balances the salt, highlighting the wine\'s honeyed fruit.',
    story: 'Chenin Blanc is a grape that insists on humility from the winemaker. In the limestone cellars of Vouvray, carved from tuffeau chalk, bottles of Demi-Sec quietly age for decades, the high natural acidity preserving the wine long past the point where most whites have faded into memory.',
  },
  {
    name: 'Xinomavro',
    color: 'Red',
    home: 'Naoussa PDO / Macedonia',
    notes: 'Wild strawberry · Black olive tapenade · Sun-dried tomato leaf · Dried earth',
    body: 3, acid: 5, tannin: 5,
    compounds: 'Structurally identical to Nebbiolo — both share high acidity, powerful tannins, and pale translucent colour. Xinomavro is distinguished from Nebbiolo by its distinct herbal and green-pepper notes (tomato leaf, black olive) versus Nebbiolo\'s classic tar and rose petals. Thrives on limestone-rich clay over marl bedrock.',
    terroir: 'Limestone and clay slopes of the Macedonian highlands. Moderate continental climate; mist-shrouded mountain amphitheatre around Mount Vermio. Extended bottle aging required to polymerize phenolic compounds.',
    structuralProfile: 'High acid, high tannin, medium body. Pale translucent garnet-ruby hue — the translucent colour combined with high tannins is the primary blind-tasting paradox. Extended maceration in large, neutral oak vessels.',
    foodPairing: 'Slow-roasted lamb shoulder with rosemary and garlic — fat binds with the grape\'s polyphenols, highlighting its savory red fruit character.',
    story: 'The exam room is silent. The wine is a pale, translucent garnet. The nose carries wild strawberry, dried rose petals, and a striking note of tomato leaf. The mind immediately leaps to Barolo — but the sommelier pauses, seeking the counter-evidence. There is no tar here, no sweet violet; instead, the distinct green olive and dried earth of the Macedonian highlands emerge. It is Naoussa Xinomavro — a conclusion reached not by guess, but by rigorous, systematic elimination.',
  },
]

// ─── FEATURED GRAPE ATTRIBUTES (AtlasHome Pinot Noir section) ────────────────
export const PINOT_NOIR_ATTRIBUTES = [
  ['Body',     'Light to Medium'],
  ['Tannin',   'Low — Silken; unpolymerized without sufficient anthocyanins'],
  ['Acidity',  'High — Lateral salivary gland activation'],
  ['Climate',  'Cool-Continental; limestone loam and marl'],
  ['Aromas',   'Red cherry · Forest floor · Dried rose · Truffle with age'],
  ['Aging',    '8 – 25 years (Grand Cru sites of the Côte de Nuits)'],
]

// ─── WSET TASTING MATRIX SPECIMEN NOTE (AtlasHome) ───────────────────────────
// Specimen: Gevrey-Chambertin 1er Cru 2019 — assessed using WSET SAT BLIC framework
export const TASTING_MATRIX = [
  {
    label: 'Appearance',
    items: [
      'Clarity — Clear; no visible haze or particles',
      'Intensity — Medium; not deeply opaque',
      'Colour — Ruby with a garnet rim; indicates moderate age and cool climate',
    ],
  },
  {
    label: 'Nose',
    items: [
      'Condition — Clean; no reduction, no TCA, no brett',
      'Intensity — Pronounced; opens with confident primary fruit',
      'Aromas — Red cherry, dried rose petals, forest floor, wild mushroom, clove',
    ],
  },
  {
    label: 'Palate',
    items: [
      'Sweetness — Dry',
      'Acidity — Medium(+); immediate lateral salivation',
      'Tannin — Medium, fine-grained; silk rather than grip',
      'Body — Medium; the Pinot Noir paradox of weight and elegance',
      'Finish — Long; savory mineral, iron, wet earth — 12+ seconds',
    ],
  },
  {
    label: 'Conclusion',
    items: [
      'Quality — Outstanding; all four BLIC elements present at high level',
      'Readiness — Drink 2024–2032; primary fruit still intact, tertiary complexity emerging',
      'Style — Cool-climate, lightly oak-aged Pinot Noir; Côte de Nuits typicity',
    ],
  },
]

// ─── WINE STYLES (8 entries, AtlasStyles page) ───────────────────────────────
// Descriptions drawn from Sommelier Research PDF (chemistry) and Luxury PDF (terroir)
export const WINE_STYLES = [
  {
    name: 'Red Wine',
    tagline: 'Of skin, structure, and time',
    body: 'Made from black grapes fermented with their skins — the source of colour, tannin, and a wine\'s architectural backbone. The duration of maceration determines tannin extraction. In red wines, tannin-anthocyanin polymerization is critical for colour stability and structural development, accelerated by micro-oxygenation where controlled oxygen exposure oxidizes ethanol to acetaldehyde, forming C8-C8 linkages between pigment molecules and grape tannins. This polymerization reduces bitter, monomeric tannins into softer polymer chains — the chemical mechanism by which harsh young reds become silky and aged.',
  },
  {
    name: 'White Wine',
    tagline: 'Of stone, acid, and the absence of skin',
    body: 'Juice pressed away from its skins immediately after crushing. Lighter in colour, entirely dependent on acidity for line and length. High titratable acidity triggers immediate salivation along the lateral margins of the tongue, indicating low pH — critical for preserving freshness. Fermentation temperature determines ester production: cold fermentation at 10–15°C produces higher concentrations of fruity volatile esters (isoamyl acetate, ethyl hexanoate), while warmer fermentation encourages yeast autolysis and fuller texture.',
  },
  {
    name: 'Rosé',
    tagline: 'Of a single afternoon of skin contact',
    body: 'Brief, controlled skin contact — a few hours, no more — with red grape skins yields a wine of pale salmon to deep copper colour and quiet aromatic intent. Saignée rosés are bled from red wine vats; direct-press rosés use minimal skin contact from the first moment. The pale Provençal style relies on cold maceration below 10°C to extract colour pigments without triggering tannin extraction. The result is a wine of red fruit volatiles (strawberry esters) without the phenolic structure of a red.',
  },
  {
    name: 'Sparkling',
    tagline: 'Of patience, pressure, and secondary fermentation',
    body: 'A second fermentation — in bottle (méthode traditionnelle) or in tank (Charmat method) — captures carbon dioxide produced by yeast consuming residual sugar, building up to 5–6 atmospheres of pressure in the sealed vessel. In Champagne, extended lees contact (15 months minimum for NV; 3 years for vintage) allows autolysis — the breakdown of yeast cell walls releasing mannoproteins and long-chain polysaccharides — which adds the characteristic brioche, hazelnut, and biscuit complexity to the wine\'s aromatic profile.',
  },
  {
    name: 'Fortified Wine',
    tagline: 'Of arrested fermentation and oxidative aging',
    body: 'Wines whose fermentation is arrested by the addition of grape spirit (neutral or aged brandy), killing the yeast before all sugar is consumed and preserving residual sweetness. Port is fortified at 77% alcohol to halt fermentation; Sherry is fermented to dryness before fortification. Oxidative aging in the Solera system — where fractional blending through a cascade of barrels ensures no wine is ever fully aged — produces the extraordinary rancio, nutty, and saline complexity of Amontillado and Oloroso Sherry.',
  },
  {
    name: 'Sweet Wine',
    tagline: 'Of noble rot, late harvest, and climatic extremes',
    body: 'Residual sugar preserved through three mechanisms: late harvest (grapes left to desiccate on the vine, concentrating sugars); Botrytis cinerea (noble rot, which punctures the berry skin, allowing water evaporation and concentrating sugars, acids, and glycerol while adding unique honey and apricot compounds); or cryo-concentration through Eiswein (frozen grapes pressed while still frozen, separating ice crystals from concentrated juice). Tokaji Aszú is measured in puttonyos — baskets of botrytized aszú berries added to a dry base wine, producing a wine of extraordinary sweetness balanced by Furmint\'s high natural acidity.',
  },
  {
    name: 'Orange Wine',
    tagline: 'Of skin-fermented white and ancient revival',
    body: 'An ancient Georgian method recently revived in the natural wine movement: white grapes treated as reds, fermented in contact with their skins for days, weeks, or months. The extended maceration extracts tannins and phenolics from the white grape skins, producing a wine of amber to deep orange colour and a tannic, textural structure entirely absent in conventional white wine. Volatile phenols and oxidative compounds develop during the extended skin contact, replacing primary fruit with savory, oxidative, and phenolic complexity.',
  },
  {
    name: 'Natural Wine',
    tagline: 'Of minimal intervention and living fermentation',
    body: 'Wines made with as little as possible added or removed at each stage — a philosophical commitment that begins in the vineyard (organic or biodynamic farming, hand harvesting, no systemic pesticides) and continues in the cellar (wild yeast fermentation, no fining, no filtration, minimal or zero sulfur dioxide additions). The absence of SO₂ leaves the wine vulnerable to Brettanomyces and volatile acidity, which advocates embrace as authentic expression of place; critics note that these faults can mask terroir rather than express it.',
  },
]

// ─── ACADEMY CHAPTERS (8, AtlasAcademy page) ─────────────────────────────────
// Drawn directly from the 8 modules of the Sommelier Intelligence System Research PDF.
// Each chapter title maps precisely to the corresponding research module.
export const ACADEMY_CHAPTERS = [
  {
    lvl: 'WSET 2',
    title: 'Palate Calibration Science',
    body: 'The human palate functions as an analytical bio-instrument when trained to decompose complex chemical mixtures into discrete structural variables. Calibration is the systematic process of defining sensory baselines against physical reference solutions — tartaric acid, oenological tannin, D-sucrose, and neutral ethanol — to eliminate personal tasting bias and ensure repeatable structural assessments across varying physiological states.',
    science: 'Acidity registered through proton (H+) ion channels; tannins bind salivary proline-rich proteins via hydrophobic stacking, forming insoluble complexes; alcohol stimulates trigeminal thermoreceptors. Detection threshold is the lowest concentration altering the global sensory profile; recognition threshold is the level at which qualitative identity is defined.',
    sommelierApp: 'Warm, dry rooms increase evaporation, intensifying alcohol warmth and masking delicate esters. A mouth-rinse protocol of dextrose, pectin, and water binds residual tannins; a two-minute reset period allows trigeminal receptors to return to baseline before continuing a long tasting flight.',
    editorialStory: 'Within the clinical silence of the sensory laboratory, the taster sits before a white sheet, six identical crystal glasses illuminated by overhead light. There is no room for romance; the air is kept perfectly neutral, free of lingering perfumes. The taster draws a breath, takes a calculated sip, and lets it coat the gums. Instantly, the lateral salivary glands tighten — a precise response to a precise concentration of tartaric acid. The mind registers the structural markers, stripping away the noise of fruit and oak to reveal the bare, chemical architecture of the vintage.',
  },
  {
    lvl: 'WSET 2',
    title: 'Blind Tasting Reasoning Systems',
    body: 'Blind tasting is a highly disciplined system of deductive logic, transforming subjective flavor sensations into objective, verifiable conclusions. Working sommeliers utilize the Court of Master Sommeliers Deductive Tasting Grid to systematically analyze appearance, nose, and palate — treating each structural element as a piece of evidence, progressively narrowing the possibilities until only a single grape variety, region, and vintage remains.',
    science: 'The brain\'s bounded rationality seeks pattern matches immediately. When expecting a specific flavor, the gustatory cortex drops processing latency from 200ms to 120ms, biasing identification toward expected rather than actual compounds. High acid, low tannin, pale ruby = Pinot Noir; high acid, high tannin, pale garnet = Nebbiolo or Xinomavro; extreme volcanic salinity, bone dry = Assyrtiko.',
    sommelierApp: 'The total evidence requirement: gather all structural clues before committing to a conclusion. Avoid anchoring bias (clinging to the first grape that comes to mind) and confirmation bias (seeking only evidence that supports the initial theory while ignoring contradictory structural evidence).',
    editorialStory: 'The exam room is silent, save for the quiet rustle of paper and the soft click of glasses. The wine is a pale, translucent garnet, its rim showing a gentle copper hue. Swirling reveals wild strawberry, dried rose petals, and a striking savory note of tomato leaf. The first sip confirms high, laser-like acidity and a wall of rustic, aggressive tannins that dry the gums instantly. The mind immediately leaps to Barolo — but the sommelier pauses, seeking the counter-evidence. There is no tar here, no sweet violet; instead, the distinct green olive and dried earth of the Macedonian highlands emerge. It is Naoussa Xinomavro — reached not by guess, but by rigorous, systematic elimination.',
  },
  {
    lvl: 'WSET 2',
    title: 'Aroma Memory Architecture',
    body: 'The psychology of flavor is rooted in the neural mechanisms of olfactory memory. The olfactory bulb possesses direct, unmediated neural connections to the amygdala (governing emotion) and the hippocampus (encoding long-term memory) — bypassing the thalamic relay that all other senses must pass through. This direct pathway explains why aromas trigger vivid, emotionally-charged memories with a force that no other sensory modality can match.',
    science: 'Structured olfactory training triggers significant neuroplastic changes — stimulating new cell growth and strengthening neural pathways linking memory, language, and emotional centers. The human nose contains roughly 400 different olfactory receptors; each individual possesses a unique genetic subset, making continuous calibration essential. A novice perceives wine as a single sensation; a trained sommelier immediately decomposes the liquid into primary monoterpenes, fermentation esters, oak-derived lactones, and tertiary oxidative aldehydes.',
    sommelierApp: 'Build a customer-friendly aromatic lexicon matching the guest\'s emotional scent references. Rather than using obscure chemical terminology, translate a wine\'s molecular profile into recognizable, evocative narratives — wet forest floor, wild red berries — to prime the guest\'s sensory system, accelerating their enjoyment and appreciation.',
    editorialStory: 'The memory of a scent is a ghost that refuses to fade. Uncorking a matured bottle of Riesling, the vapor rises, carrying a whisper of dry petrol, lime peel, and wet slate. Instantly, the modern tasting room dissolves, replaced by the cool, damp air of an old stone cellar along the Danube, visited a decade prior. The mind does not merely recall the place; it feels the weight of the humid air, the damp moss on the stones, the quiet hum of the river outside. This is the unique power of the olfactory bulb — speaking directly to the emotional core, bypassing the cold logic of the conscious brain to resurrect the past in a single, fleeting breath.',
  },
  {
    lvl: 'WSET 3',
    title: 'Terroir Biophysics',
    body: 'Terroir represents the complex intersection of geology, soil chemistry, climate, and topography — the unique fingerprint of a place, written in the language of biochemistry. To comprehend terroir, one must analyze how environmental factors directly alter vine physiology, grape composition, and wine structure. Terroir is not static; it is a dynamic, living system extending from the deep vertical fractures of metamorphic bedrock to the microscopic activity of the soil microbiome.',
    science: 'Cation Exchange Capacity (CEC) refers to the soil\'s ability to hold and exchange positively charged nutrient ions. Arbuscular mycorrhizal fungi (AMF) form physical networks within grapevine roots, expanding surface area to enhance phosphorus and nitrogen absorption. Aquaporin genes control root hydraulic conductance; abscisic acid (ABA) regulates stomatal closure as water deficit increases. High-altitude vineyards (Golan Heights, up to 1200m) experience intense UV-B exposure, upregulating the synthesis of photoprotective flavonols and anthocyanins — deeper colour, firmer tannins, elevated antioxidant capacity.',
    sommelierApp: 'When a guest requests a mineral-driven, high-acid white, bypass generic recommendations — select wines from regions defined by crystalline or volcanic bedrock: Wachau Riesling on Gföhl gneiss, or dry Tokaj Furmint from dacitic volcanic slopes. Translate this geological architecture into a tangible sensory promise of structural tension and saline complexity.',
    editorialStory: 'To stand on the cliffs of Santorini is to look upon a viticultural battlefield, where ancient Assyrtiko vines wrestle with wind and ash. The landscape is bone-dry and stark, a canvas of black basalt and glittering white pumice. The vines do not stand tall; they are woven by hand into low, protective baskets, their leaves turned inward to shield the green fruit from the biting, sand-laden Aegean winds. Beneath this harsh surface, the roots dig deep into the sterile, abiotic volcanic soil, searching for the moisture of morning mists. The wine born from this fire and dust is not sweet or gentle; it is a jolt of pure, saline electricity, carrying the cold, smoky whisper of the volcano itself.',
  },
  {
    lvl: 'WSET 3',
    title: 'Advanced Wine Chemistry',
    body: 'The chemical profile of wine is a dynamic, evolving landscape of volatile and non-volatile compounds originating from primary grape synthesis, secondary microbial fermentation, and tertiary maturation. Volatile organic compounds — including esters, thiols, pyrazines, and terpenes — define a wine\'s unique aromatic identity, while non-volatile compounds like tannins and anthocyanins construct its structural backbone.',
    science: 'Rotundone (sesquiterpene) — the peppery aroma of Syrah and Grüner Veltliner — accumulates in grape skins between veraison and harvest and is perceptible at parts-per-trillion levels. Pyrazines (2-methoxy-3-isobutylpyrazine) — green bell pepper and tomato leaf in Cabernet family grapes — indicate cool growing climate or early harvest. Thiols (3MH, A3MH) exist as odorless amino-acid-bound precursors, unlocked during fermentation to release passion fruit and grapefruit. Tannin-anthocyanin polymerization via acetaldehyde C8-C8 bridges is the central mechanism of red wine aging.',
    sommelierApp: 'A strong medicinal band-aid aroma identifies Brettanomyces contamination. Heavy cabbage or burnt-match notes indicate reduction — remedy by decanting to accelerate volatilization and oxidation. Low sulfide fermentation aromas dissipate with oxygen; Brettanomyces and cork taint (TCA) do not and cannot be decanted out.',
    editorialStory: 'Inside the quiet, charred staves of a French oak barrel, a slow and silent alchemy is underway. The young wine, rough and crimson-purple, rests in the darkness, drawing minuscule gasps of oxygen through the wood pores. As the air enters, ethanol molecules oxidize into acetaldehyde, forming tiny chemical bridges that bind the bright anthocyanin pigments to the drying, monomeric grape tannins. Slowly, the jagged tannin molecules are woven into long, soft polymer chains, smoothing their rough edges. At the same time, the heat-charred wood releases its vanillin and eugenol, slowly infusing the liquid with warm spice and toasted sweetness. It is a slow, quiet transformation — turning a raw, aggressive vintage into a structured, elegant masterpiece.',
  },
  {
    lvl: 'WSET 3',
    title: 'Sommelier Service Psychology',
    body: 'Sommelier service at the highest level is an intricate blend of physical precision, emotional hospitality, and behavioral psychology. Beyond the physical tasks of opening, decanting, and pouring wine, the sommelier\'s primary mission is to elevate the dining experience, transforming a standard dinner into a memorable, emotionally resonant event — requiring a deep understanding of luxury service psychology and an ability to read a table\'s unspoken needs.',
    science: 'The shape and engineering of a wine glass are functional tools designed to optimize volatile release and direct liquid flow. A grape-varietal-specific glass uses three precise variables: bowl size, shape, and rim diameter. The bowl shape regulates headspace concentration of volatile organic compounds; the laser-cut polished rim dictates where the wine lands on the tongue as the head tilts. Decanting older sedimented bottles: pour slowly over a light source, monitoring the neck, stopping as the first sediment particles reach the shoulder.',
    sommelierApp: '"Guest profiling" — identifying a guest\'s emotional state, dining objectives, and budget comfort within the first moments of engagement. Navigate complex tableside dynamics: manage guests who feel intimidated by wine terminology while simultaneously engaging collectors seeking deep intellectual dialogue, with a delicate humble touch ensuring every guest feels comfortable regardless of whether they are purchasing a 60€ bottle or a 6,000€ icon.',
    editorialStory: 'The dining room is a synchronized dance of light and shadow, filled with the low hum of conversation and the gentle clink of polished crystal. The sommelier approaches the table with a bottle of aged grand cru, their movements quiet and deliberate. Placing a small candle on the table, they draw the cork with a single, fluid motion. Slowly, steadily, the crimson liquid is poured into a thin-necked crystal decanter, the soft glow of the candle flame illuminating the neck of the bottle. The sommelier watches, their eyes focused on the shoulder of the glass. Just as the first dark, velvety speck of sediment approaches the neck, the pour is stopped. The clear, sediment-free liquid is poured into the guest\'s glass — a perfect marriage of physical precision and silent hospitality.',
  },
  {
    lvl: 'WSET 3',
    title: 'Vintage & Climate Architecture',
    body: 'A vintage is a record of a single growing season, captured in the physical and chemical properties of the grape. Weather patterns of a specific year — rainfall, heat accumulation, frost events, and temperature swings — shape a wine\'s final style, structure, and aging potential. Evaluating a vintage requires analyzing how macroclimatic forces and microclimatic anomalies alter grape physiology and ripening kinetics.',
    science: 'The Winkler Index sums growing degree-days (GDD) above a base of 10°C to categorize regional heat accumulation (Region I–V). The Huglin Index weights maximum daily temperatures and adjusts for latitude-based day length — preferred in European viticultural assessment. Warm nights stimulate respiration of malic acid via the citric acid cycle, causing rapid acidity loss. A late spring frost after budburst kills the sensitive primary bud, forcing reshoot from secondary buds — producing significantly smaller, less fruitful clusters and delaying harvest.',
    sommelierApp: 'A guest requesting bold, opulent Cabernet Sauvignon: select a warmer vintage where high heat accumulation produced rich fruit and high alcohol. A guest preferring fresh, balanced wine with high acidity: point toward a cooler, classic growing year where slow ripening preserved natural tartaric and malic acids.',
    editorialStory: 'The dawn light reveals a quiet, cold mist clinging to the vineyard floor, wrapping the delicate green shoots in a thin blanket of frost. The viticulturist walks the rows, their breath rising in white plumes, their eyes focused on the swollen buds. It is mid-April, and the primary shoots have already emerged, carrying the promise of the entire year\'s harvest. A drop in temperature to minus two degrees Celsius is all it takes; the water inside the tender cells freezes, expanding and rupturing the cellular membranes. Within days, these primary shoots will dry up and turn black. The vine must now turn to its backup plan, pushing secondary shoots from deep within its wood — a raw, resilient response that will preserve the plant\'s life at the expense of the vintage.',
  },
  {
    lvl: 'WSET 3',
    title: 'Food & Wine Interaction Science',
    body: 'The science of food and wine pairing examines how the chemical structures of food — fat, acidity, salt, sweetness, and umami — interact on a molecular level with the acidity, alcohol, sweetness, and tannins of wine. A successful pairing relies on creating balance, either through congruent matches (similar flavors reinforce each other) or contrasting matches (opposite forces create harmony). Pairing design at the elite level utilizes molecular harmony — mapping dominant volatile compounds within both food and wine to recognize shared molecular structures predisposed to create aromatic synergies.',
    science: 'Tannins are amphiphilic polyphenols that bind salivary proline-rich proteins (PRPs) via hydrophobic interactions and hydrogen bonding. This precipitates proteins out of solution, removing natural oral lubrication — the astringent sensation. When protein-rich food (rare steak, high-fat cheese) is introduced, the tannins bind dietary proteins instead — the Camembert Effect. Capsaicin activates pain and heat receptors; ethanol dissolves capsaicin, so high-alcohol wines amplify burning sensation on the throat. Umami (without salt) increases perception of bitterness and alcohol burn in wine while stripping away sweet fruit flavors. Eugenol molecule dominates both whole cloves and Tempranillo aged in toasted oak — dishes rich in eugenol create aromatic synergies with oaked Rioja.',
    sommelierApp: 'With an exceptionally spicy dish: avoid high-tannin and high-alcohol reds — select off-dry, low-alcohol whites such as German Riesling, where residual sugar calms the capsaicin burn. With high-umami dishes like mushroom risotto: avoid young tannic Cabernet, select low-tannin whites or aged reds where tannins have polymerized. Coordinate with the kitchen team to design harmonious pairing menus for multi-course service.',
    editorialStory: 'The plate presents a study in contrast: a rich, slow-cooked venison loin with a wild blackberry reduction. Beside it stands a glass of young, muscular Douro Tinto, its deep ruby-black color carrying the scent of wild plum and wet slate. Tasted alone, the wine is a force of raw, drying tannins that coat the teeth. But as the taster takes a bite of the venison, the gamey fats and proteins immediately intercept the tannins, binding them before they can dry the gums. The wine\'s harshness dissolves, transformed into a soft, velvety texture that highlights the vibrant blackberry and dark chocolate notes in the glass. It is not a marriage of convenience; it is thermodynamics in action, written in the language of flavor.',
  },
]

// ─── EDITORIAL PULL QUOTES (from research document storytelling sections) ─────
// Sourced verbatim or near-verbatim from the editorial narrative sections of both PDFs
export const PULL_QUOTES = [
  {
    text: 'To taste wine seriously is to read a landscape with your tongue — to find, in a single glass, the slope of a hill and the kindness of a winemaker.',
    attribution: 'Henri Lacombe · Maître Sommelier, Lyon',
    context: 'Sommelier Intelligence System Research',
  },
  {
    text: 'The memory of a scent is a ghost that refuses to fade. Uncorking a matured bottle of Riesling, the vapor rises, carrying a whisper of dry petrol, lime peel, and wet slate — and instantly, the modern tasting room dissolves.',
    attribution: 'Aroma Memory & Sensory Psychology — Chapter III',
    context: 'Sommelier Intelligence System Research',
  },
  {
    text: 'To stand on the cliffs of Santorini is to witness a viticultural battlefield where life clings to fire and dust. The wine born from this fire and dust is not sweet or gentle; it is a jolt of pure, saline electricity, carrying the cold, smoky whisper of the volcano itself.',
    attribution: 'Advanced Terroir Intelligence — Chapter IV',
    context: 'Sommelier Intelligence System Research',
  },
  {
    text: '"Show me a map of the soil and I will show you the wine that will be made there."',
    attribution: 'Old French Adage',
    context: 'Luxury Wine Intelligence Research Prompt',
  },
  {
    text: 'Inside the quiet, charred staves of a French oak barrel, a slow and silent alchemy is underway. The young wine, rough and crimson-purple, rests in the darkness, drawing minuscule gasps of oxygen through the wood pores.',
    attribution: 'Advanced Wine Chemistry — Chapter V',
    context: 'Sommelier Intelligence System Research',
  },
  {
    text: 'The dawn light reveals a quiet, cold mist clinging to the vineyard floor. A drop in temperature to minus two degrees Celsius is all it takes; the water inside the tender cells freezes, expanding and rupturing the cellular membranes.',
    attribution: 'Vintage & Climate Architecture — Chapter VII',
    context: 'Sommelier Intelligence System Research',
  },
]

// ─── REGIONS DETAIL (supplementary data for Phase 3 component enrichment) ────
// Drawn from both PDFs; structured for future region detail pages
export const REGIONS_DETAIL = [
  {
    id: 'santorini',
    name: 'Santorini PDO',
    country: 'Greece',
    signatureGrapes: ['Assyrtiko', 'Aidani', 'Athiri'],
    geology: 'Aspa — stratified pumice, volcanic ash, and basalt; zero clay, zero organic matter; completely immune to phylloxera',
    climate: 'Arid maritime; hyper-arid with fierce Aegean winds; extreme UV exposure upregulates anthocyanin and flavonol synthesis in grape skins',
    vineTraining: 'Kouloura — ancient low-lying, hand-woven basket training; leaves turned inward to shield grapes from biting, sand-laden Aegean winds',
    structuralProfile: 'High acid (very low pH), medium-to-full body, low tannin. Bone-dry. Laser-like acidity and saline-bitter finish. Defies conventional warm-climate viticultural models by retaining razor-sharp titratable acidity even at high potential alcohol.',
    winemaking: 'Unoaked; skin contact variants exist. Vin Santo (Vinsanto) from sun-dried grapes also produced.',
    tastingNote: 'Preserved lemon, white peach, crushed oyster shell, and a profound smoky volcanic saltiness. Bone-dry palate, dense phenolic weight, lingering saline-bitter finish.',
    blindTastingLogic: 'Often confused with Grand Cru Chablis or dry German Riesling due to mineral-driven, high-acid structure. Distinguished by higher natural alcohol, distinct phenolic bitterness on the back-palate, and unique volcanic salinity.',
    foodPairing: 'Grilled octopus with olive oil and capers; raw oysters; grilled sea bream. The wine\'s high acidity and saline core cut through dense seafood texture and mirror oceanic salinity.',
    editorial: 'To stand on the cliffs of Santorini is to witness a viticultural battlefield where life clings to fire and dust. The wind here is a physical force, screaming across the caldera and whipping the volcanic soil into a frenzy. The vines do not rise to meet the sun; instead, they cower in tight, hand-woven nests of wood, hunkered close to the black basalt and white pumice.',
  },
  {
    id: 'naoussa',
    name: 'Naoussa PDO',
    country: 'Greece',
    signatureGrapes: ['Xinomavro'],
    geology: 'Limestone-rich clay over marl bedrock; well-draining slopes in the Macedonian highlands around Mount Vermio',
    climate: 'Moderate continental; mist-shrouded mountain amphitheatre; warm summers and cold winters',
    structuralProfile: 'High acid, high tannin, medium body. Pale translucent garnet-ruby hue with orange-brick rim on older wines. Extended maceration; large neutral oak aging required to integrate phenolic structure.',
    winemaking: 'Extended maceration 2–4 weeks; aging in large neutral oak vessels; minimum 12 months aging required by PDO law for standard; 24 months for Reserva.',
    tastingNote: 'Translucent garnet-ruby. Wild strawberry, red cherry, sun-dried tomato leaf, black olive tapenade, dried earth, leather. High aggressive tannins, piercing acidity, lean mid-palate, savory forest-floor finish.',
    blindTastingLogic: 'Structurally identical to Piedmontese Nebbiolo — both share high acidity, powerful tannins, and pale colour. Distinguished from Nebbiolo by distinct herbal and green-pepper notes (tomato leaf, black olive) contrasting with Nebbiolo\'s classic tar and rose petals.',
    foodPairing: 'Slow-roasted lamb shoulder encrusted with rosemary and garlic — fat binds with polyphenols, highlighting savory red fruit. Braised wild boar with tomato and wild herbs.',
    editorial: 'In Naoussa, the landscape changes to a green, mist-shrouded mountain amphitheatre. Here, Xinomavro — the "acid-black" — vines dig their roots into ancient limestone, absorbing the quiet moisture of the Macedonian hills. This grape requires extended bottle aging to polymerize its phenolic compounds, eventually revealing a complex array of volatile aromas.',
  },
  {
    id: 'douro',
    name: 'Douro Valley',
    country: 'Portugal',
    signatureGrapes: ['Touriga Nacional', 'Touriga Franca', 'Tinta Roriz', 'Tinta Barroca'],
    geology: 'Metamorphic schist (xisto) — highly laminated phyllite and slate fracturing vertically (not horizontally), allowing vine roots to drill 15m deep to access sub-surface water during hot, dry summers. Surribar — deep-ripping the schist to break rock plates and facilitate root penetration.',
    climate: 'Hot, arid continental. Traditional vinhas velhas (old-vine field blends) buffer against extreme vintage variation through multi-variety co-ripening.',
    structuralProfile: 'Medium acid, high tannin, full body. Deep opaque ruby-black. Co-fermented field blends mature in French oak.',
    winemaking: 'Traditional co-fermented field blends of dozens of co-planted varieties ripening at different rates; foot-treading in granite lagares; maturation in French oak.',
    tastingNote: 'Deep opaque ruby-black. Intense aromas of wild blackberry, dark plum, dark chocolate, tobacco leaf, wet slate. Full-bodied, firm muscular tannins, dense mid-palate, long warm finish with lingering graphite.',
    blindTastingLogic: 'Structurally comparable to Priorat but distinguished by firmer tannins and more rustic, savory woodsmoke notes. Dark fruit and minerality are the primary diagnostic markers.',
    foodPairing: 'Pan-seared venison loin with blackberry reduction. Iron-rich meats where the wine\'s dark fruit and structure complement rich, gamey textures.',
    editorial: 'The Douro Valley is a monument to human determination, where steep mountainsides are carved into terraced stone steps that look like a giant staircase rising from the river. The soil is not earth, but a gray, glittering sea of fractured schist that absorbs the heat of the summer sun, radiating it back to the vines under a cloudless sky.',
  },
  {
    id: 'dao',
    name: 'Dão',
    country: 'Portugal',
    signatureGrapes: ['Touriga Nacional', 'Alfrocheiro', 'Jaen', 'Encruzado'],
    geology: 'Decomposing granite, sandy clay, and schist at elevations of 400–800m; a protected upland basin enclosed on three sides by granitic mountain ranges (Serra da Estrela, Caramulo, Nave)',
    climate: 'Shielded continental; high diurnal temperature range; maritime influence excluded by surrounding mountains. Vineyards ripen at a gentler pace than the Douro.',
    structuralProfile: 'High acid, medium-to-high tannin, medium-to-full body. Fine-grained chalky tannins; intense etheric floral aromatics of violet and bergamot. Structural elegance over raw power.',
    winemaking: 'Minimal extraction; focus on elegance; neutral oak. Single-variety Touriga Nacional from the Dão develops completely differently from the Douro expression.',
    tastingNote: 'Translucent brilliant ruby. Highly aromatic — fresh red cherry, wild raspberry, violet blossom, Earl Grey tea, wet granite. Medium-bodied, lively acidity, fine-grained chalky tannins, herbal mineral finish.',
    blindTastingLogic: 'Often compared to Côte de Nuits Pinot Noir due to floral perfume, high acidity, and elegant red-fruit-driven structure. Touriga Nacional identified by deeper colour extraction, slightly firmer tannin, and signature note of bergamot or black tea.',
    foodPairing: 'Roasted duck breast with wild mushroom risotto — the wine cuts through fatty duck while its herbal undertones align with the savory mushrooms.',
    editorial: 'In the Dão, the landscape shifts to a quiet, upland plateau surrounded by pine forests and granite peaks. The vines here bask in a gentler light, growing on soils that look like coarse white sand, producing wines with a quiet, mineral-driven elegance that contrasts entirely with the muscular power of the Douro just to the north.',
  },
  {
    id: 'tokaj',
    name: 'Tokaj',
    country: 'Hungary',
    signatureGrapes: ['Furmint', 'Hárslevelű', 'Sárgamuskotály'],
    geology: 'Mosaic of rhyolite tuff, andesite, dacite, zeolite, clay, and loess over approximately 400 extinct volcanoes. The Mád Basin is the volcanic core, hosting legendary first-growth sites: Szent Tamás, Betsek, Úrágya.',
    climate: 'Moderate continental; autumn mists generated at the confluence of the Bodrog and Tisza rivers promote Botrytis cinerea on Furmint\'s thin-skinned, high-acid berries.',
    structuralProfile: 'High acid, full body, low tannin. Dacite slopes: elegant aromatic wines with smooth texture. Basalt and rhyolite tuff: dry Furmints with flinty, smoky, salty character.',
    winemaking: 'Botrytis selection for Aszú; slow fermentation in mould-coated volcanic tufa cellars covered in Cladosporium cellare. Puttonyos system measures botrytized berry concentration. Dry Furmint made from hand-sorted, healthy clusters.',
    tastingNote: 'Dry Furmint (Mád Basin): pale lemon-green, green pear, quince, fresh ginger, crushed chalk, woodsmoke — bone-dry, structured, salty finish. Tokaji Aszú (6 Puttonyos): brilliant amber-gold, dried apricot, orange marmalade, saffron, wild honey, ginger, caramel — luscious yet balanced by high acidity.',
    blindTastingLogic: 'Dry Furmint often compared to dry German Riesling or Hunter Valley Semillon due to high acidity and mineral profile. Distinguished by broader mid-palate, unique ginger and pear aromas, and distinct smoky note from volcanic soils. Tokaji Aszú compared to Sauternes but distinguished by higher acidity, lower alcohol, and more intense ginger and dried-apricot character.',
    foodPairing: 'Tokaji Aszú with salty Roquefort — salt balances sweetness while highlighting fruit flavors. Dry Furmint with slow-roasted pork belly — high acidity and mineral core cut through rich fat.',
    editorial: 'To enter the ancient cellars of Tokaj is to step back in time. Carved deep into volcanic tufa rock, the cellar walls are covered in a thick, velvety black mould that thrives on the evaporating alcohol, keeping the air remarkably clean and humid. Here, in the quiet darkness, Tokaji Aszú matures in oak barrels, developing its complex golden flavors — while outside, the autumn air is thick with river mist, wrapping the vines in a soft blanket that coaxes the grapes into noble rot.',
  },
  {
    id: 'somlo',
    name: 'Somló',
    country: 'Hungary',
    signatureGrapes: ['Juhfark', 'Furmint', 'Hárslevelű'],
    geology: 'A single basalt volcanic "witness hill" rising sharply from the flat Pannonian plain; basalt, basalt tuff, clay, and marl. The dark volcanic stones absorb solar heat during the day and release it slowly at night.',
    climate: 'Temperate continental; the isolated hill creates its own microclimate with strong UV exposure and good diurnal temperature range.',
    structuralProfile: 'High acid, full body, low tannin. Juhfark absorbs high amounts of minerals from the basalt, producing dry white wines with intense smoky, gunflint aroma and a very long, salty finish.',
    winemaking: 'Traditional fermentation in large Hungarian oak; minimal intervention; no malolactic conversion to preserve the high natural acidity.',
    tastingNote: 'Somlói Juhfark: straw-yellow colour. Intense, unusual aromas of gunflint, wet stone, lemon peel, baked apple. Full-bodied and powerful, with dense texture, high acidity, and a smoky, salty finish.',
    foodPairing: 'Traditionally served at Hungarian royal wedding feasts as a fertility wine. Its density and mineral power pair well with freshwater fish dishes and smoked trout with cream.',
    editorial: 'In Somló, the basalt "witness hill" stands alone, rising sharply from the flat plain. Its dark, volcanic stones absorb the sun\'s heat during the day and release it slowly at night, infusing Juhfark grapes with the fiery essence of an ancient volcano. The wine produced here is unlike any other in Hungary — dense, smoky, and salty, carrying the memory of fire in every glass.',
  },
  {
    id: 'wachau',
    name: 'Wachau DAC',
    country: 'Austria',
    signatureGrapes: ['Grüner Veltliner', 'Riesling'],
    geology: 'Western Wachau (Spitz, Dürnstein): Gföhl gneiss — highly migmatitic, granitic crystalline rock composed of quartz, feldspar, and biotite mica; restricts vine vigor and forces deep root development. Eastern Wachau extending into Kremstal: massive loess terraces — wind-blown yellow glacial sediment with high water-retention capacity.',
    climate: 'Cool-climate continental; Danube River moderates temperature extremes; dry-stone walls built by hand over centuries hold back thin, rocky soils and retain heat.',
    structuralProfile: 'High acid, medium-to-full body, low tannin. Three Wachau ripeness levels: Steinfeder (light, low alcohol), Federspiel (medium), Smaragd (full-bodied, complex, high alcohol). Smaragd wines are always hand-harvested; zero oak, no malolactic conversion.',
    winemaking: 'Hand harvesting required on steep terraces; stainless steel fermentation; zero malolactic; zero oak to preserve the crystalline mineral tension from Gföhl gneiss.',
    tastingNote: 'Wachau Riesling Smaragd: intensely aromatic — lime zest, ripe white peach, wet slate, jasmine, petrol. Bone-dry, powerful, concentrated, high acidity, long finish of crushed stones.',
    blindTastingLogic: 'Often compared to dry Alsace Grand Cru Riesling. Distinguished by lower residual sugar (typically bone-dry, under 4g/L), a unique crystalline mineral tension from Gföhl gneiss, and the complete absence of wood influence.',
    foodPairing: 'Riesling Smaragd with roasted sweetbreads or pan-seared sea bass with lemon-herb butter. Grüner Veltliner with asparagus and prosciutto, or traditional Wiener Schnitzel — one of the few wines that can handle challenging green vegetables.',
    editorial: 'The Wachau is a landscape of stark beauty, where the Danube River winds beneath terraced stone cliffs that seem to rise straight out of the water. These dry-stone walls, built by hand over centuries, hold back thin, rocky soils that glisten with flakes of mica. In spring, apricot blossoms fill the valley with colour, while in autumn, the terraced slopes turn a brilliant gold.',
  },
  {
    id: 'kremstal',
    name: 'Kremstal DAC',
    country: 'Austria',
    signatureGrapes: ['Grüner Veltliner', 'Riesling'],
    geology: 'Deep loess terraces over crystalline bedrock; loess is wind-blown yellow glacial sediment composed of silt, clay, and calcium carbonate — high water-retention capacity and nutrient richness ideal for Grüner Veltliner.',
    climate: 'Moderated continental with warm Pannonian winds from the east; warmer than the Wachau to the west. The Benedictine Göttweig Abbey stands on a hill as a silent guardian over the vineyards.',
    structuralProfile: 'High acid, medium-to-full body, low tannin. Focus on single-vineyard (Riedenwein) expressions. Loess terraces produce Grüner Veltliner with a broad, peppery, spicy profile.',
    winemaking: 'Stainless steel and large neutral oak. Single-vineyard classification increasingly important — Ried (individual vineyard) wines carry the first-growth imprimatur.',
    tastingNote: 'Kremstal Grüner Veltliner Reserve: deep straw-gold. Rich aromas of white pepper, radish, green pear, lentil, ginger, and honeyed complexity. Dry, medium-to-full-bodied, creamy round texture balanced by high acidity and spicy finish.',
    foodPairing: 'Grüner Veltliner pairs exceptionally with roasted asparagus wrapped in prosciutto, or traditional Wiener Schnitzel. The white pepper and mineral core can handle challenging green vegetables that defeat most wines.',
    editorial: 'Further east in the Kremstal, the landscape softens into rolling hills of pale yellow loess, where the Benedictine Göttweig Abbey stands on a hill like a silent guardian over the vineyards. Here, the air is warmer, filled with the gentle breeze of the Pannonian plains, creating a welcoming home for Grüner Veltliner — a grape that transforms the glacier\'s ancient sediment into vivid, peppery wines of great character.',
  },
  {
    id: 'golan-heights',
    name: 'Golan Heights',
    country: 'Israel',
    signatureGrapes: ['Cabernet Sauvignon', 'Merlot', 'Syrah', 'Chardonnay'],
    geology: 'Deep basalt clay and volcanic tuff, rich in iron and minerals; high-altitude plateau rising above 900–1200m above sea level',
    climate: 'Cool montane continental; cold, snowy winters and warm summers with large diurnal temperature swings. High altitude creates intense UV-B exposure.',
    structuralProfile: 'High acidity, firm tannins, full body, exceptional aging potential. LODI RULES certified for sustainable winegrowing (Golan Heights Winery, Galil Mountain Winery).',
    winemaking: 'Cold maceration to preserve acidity; aging in French oak barriques. The high diurnal temperature swings allow Cabernet Sauvignon, Merlot, and Syrah to retain high acidity and structure despite warm summer temperatures.',
    tastingNote: 'Golan Heights Syrah: deep purple-black. Aromas of blackberry, black plum, freshly cracked black pepper, smoked meat, iron. Full-bodied, vibrant acidity, firm tannins, long savory finish.',
    blindTastingLogic: 'Golan Heights Cabernet Sauvignon shares the power and intensity of Napa Valley mountain Cabs but can be identified by its higher natural acidity and distinct, iron-like minerality from volcanic soils.',
    foodPairing: 'Golan Heights Syrah with grilled ribeye steak with savory pepper crust. A structured Judean Hills Cabernet blend with slow-cooked lamb shank roasted with rosemary, garlic, and pomegranate molasses.',
    editorial: 'To stand on the volcanic plateau of the Golan Heights is to feel the cool wind blowing off the snow-covered peak of Mount Hermon, carrying the scent of wild herbs and wet stone. The vines grow in deep, dark basalt soils, their green leaves contrasting with the black volcanic rock — producing wines that carry the iron and fire of a living geological frontier.',
  },
]

// ─── TERROIR PROFILES TABLE (from Sommelier Research PDF Chapter 4) ──────────
export const TERROIR_PROFILES = [
  {
    type: 'Volcanic Island',
    geology: 'Basalt, pumice, volcanic ash (aspa)',
    soilChemistry: 'Low CEC, abiotic, zero clay',
    representativeWine: 'Santorini Assyrtiko — laser acid, volcanic salinity',
  },
  {
    type: 'Metamorphic Slopes',
    geology: 'Vertical schist (xisto) — fractures vertically',
    soilChemistry: 'Low CEC, high drainage, deep root penetration',
    representativeWine: 'Douro Tinto — structured, muscular',
  },
  {
    type: 'Crystalline Terraces',
    geology: 'Gföhl gneiss — migmatitic granitic rock',
    soilChemistry: 'Low CEC, low vigor, forces deep roots',
    representativeWine: 'Wachau Riesling — tense acid, stone fruit',
  },
  {
    type: 'Alluvial Terraces',
    geology: 'Glacial loess — wind-blown silt, clay, calcium carbonate',
    soilChemistry: 'High CEC, high nutrient retention',
    representativeWine: 'Kremstal Grüner Veltliner — broad, spicy',
  },
  {
    type: 'High-Altitude Plateau',
    geology: 'Volcanic basalt clay, iron-rich',
    soilChemistry: 'Moderate CEC, iron-rich, intense UV-B exposure',
    representativeWine: 'Golan Heights Syrah — vibrant acid, iron',
  },
  {
    type: 'Limestone & Terra Rossa',
    geology: 'Shallow terra rossa clay-silt over hard limestone bedrock',
    soilChemistry: 'Mineral-rich, free-draining, naturally restricts vine yields',
    representativeWine: 'Judean Hills Cabernet Blend — chalky tannins, cedar',
  },
]

// ─── COMPOUND TABLE (from Sommelier Research PDF Chapter 5) ──────────────────
export const SENSORY_COMPOUNDS = [
  {
    family: 'Pyrazines',
    molecule: '2-Methoxy-3-isobutylpyrazine',
    aromaProfile: 'Green bell pepper, asparagus, grass',
    keyWineIndicator: 'Cool-climate Cabernet Sauvignon / Cabernet Franc',
  },
  {
    family: 'Volatile Thiols',
    molecule: '3-Mercaptohexanol (3MH)',
    aromaProfile: 'Grapefruit, guava, exotic tropical fruit',
    keyWineIndicator: 'Young Sauvignon Blanc (Marlborough, Sancerre)',
  },
  {
    family: 'Sesquiterpenes',
    molecule: 'Rotundone',
    aromaProfile: 'Freshly cracked black pepper',
    keyWineIndicator: 'Syrah (Cornas, Crozes-Hermitage), Grüner Veltliner',
  },
  {
    family: 'Norisoprenoids',
    molecule: 'β-Damascenone',
    aromaProfile: 'Cooked apple, rose, honey, tea',
    keyWineIndicator: 'Aged Riesling, Chardonnay',
  },
  {
    family: 'TDN (Petrol)',
    molecule: '1,1,6-Trimethyl-1,2-dihydronaphthalene',
    aromaProfile: 'Petrol, kerosene, mineral petroleum',
    keyWineIndicator: 'Aged Riesling (Wachau Smaragd, German Auslese)',
  },
  {
    family: 'Diacetyl',
    molecule: 'Diacetyl (2,3-butanedione)',
    aromaProfile: 'Melted butter, butterscotch, cream',
    keyWineIndicator: 'Oaked Chardonnay with malolactic conversion',
  },
  {
    family: 'Oak Lactones',
    molecule: 'cis-β-methyl-γ-octalactone',
    aromaProfile: 'Coconut, fresh oak, dill',
    keyWineIndicator: 'American-oaked Tempranillo, Rioja',
  },
  {
    family: 'Volatile Phenols (Brett)',
    molecule: '4-Ethylphenol (4-EP)',
    aromaProfile: 'Band-aid, barnyard, smoky bacon',
    keyWineIndicator: 'Brettanomyces spoilage — diagnostic fault marker',
  },
]
