export const TEXT = {
  en: {
    app: {
      name: 'HESTIA',
      suffix: 'AI',
      tagline: 'Hospitality Intelligence OS',
      secureAccess: 'Secure Access',
      accessTitle: 'Sign in to your operating system',
      accessBody: 'A role-based hospitality operating system for owners, managers, and service teams.',
      codePlaceholder: 'Username',
      enter: 'Enter Platform',
      invalid: 'Invalid username or password.',
      employee: 'Employee',
      manager: 'Manager',
      owner: 'Owner',
      admin: 'Admin',
      language: 'Language',
      english: 'English',
      hebrew: 'Hebrew',
      logout: 'Logout',
      today: 'Today',
      valueIdentified: 'Value Identified'
    },
    areas: {
      command: 'Owner Command',
      operations: 'Shift Operations',
      employeeWorkflow: 'Employee OS',
      planning: 'Event Planning',
      staffProgression: 'Staff Progression',
      academy: 'Academy',
      barManagement: 'Bar Management',
      ownerIntelligence: 'Business Intelligence',
      system: 'System'
    },
    areaDescriptions: {
      command: 'Owner HQ — approvals, reports, memory, and workspace',
      operations: 'Shift control, events, staff coaching, and handoff',
      employeeWorkflow: 'Personal training, service, and reporting home',
      planning: 'Event CRM, calculators, run-of-show, and pipeline',
      staffProgression: 'Team readiness, practice, incident exposure, and coaching',
      academy: 'Courses, service standards, lessons, and approved knowledge',
      barManagement: 'Cocktail R&D, costing, and menu approval pipeline',
      ownerIntelligence: 'Reports, approvals, business memory, and operational intelligence',
      system: 'Owner workspace'
    },
    pages: {
      commandCenter: 'Owner Dashboard',
      preShiftBriefing: 'Pre-Shift Briefing',
      actionBoard: 'Shift Control',
      managerActionCenter: 'Manager Action Center',
      managerEmployeeRequests: 'Employee Requests',
      eventCRM: 'Events',
      eventOrchestrator: 'Event Finance',
      staffProgression: 'Staff Progression',
      staffReadiness: 'Team Readiness',
      employeeHome: 'Employee Home',
      employeeRequests: 'Employee Requests',
      employeeAchievements: 'Achievements',
      serviceRecovery: 'Report An Issue',
      endOfShiftReview: 'End-of-Shift Review',
      endOfDay: 'Shift Closeout',
      operationalNotes: 'Operational Notes',
      budgetRequest: 'Submit Budget Request',
      simulation: 'Practice Lab',
      courses: 'Courses',
      lessonPlayer: 'Lesson Player',
      sopSheets: 'Service',
      knowledgeLibrary: 'Knowledge Library',
      wineKnowledge: 'Wine Academy',
      cocktailLab: 'Cocktail Lab',
      foodCostTables: 'Food Cost Tables',
      approvedCocktailsBar: 'Approved Cocktails',
      cocktailLibrary: 'Cocktail Bible',
      inventoryOverview: 'Inventory Overview',
      barReports: 'Bar Reports',
      bottlePrices: 'Bottle Prices',
      approvedCocktails: 'Approved Cocktails',
      learningProgress: 'Learning Progress',
      executiveOverview: 'Executive Overview',
      operationalPulse: 'Operational Pulse',
      budgetApprovals: 'Budget Approvals',
      ownerOperationalRequests: 'Operational Requests',
      weeklySummary: 'Weekly Summary',
      businessMRI: 'Business MRI',
      profitLeaks: 'Profit Leaks',
      ownerReport: 'Owner Report',
      businessMemory: 'Business Memory',
      strategicRecommendations: 'Strategic Recommendations',
      settings: 'Settings'
    },
    ui: {
      collapsePanel: 'Collapse panel',
      openPanel: 'Open panel',
      selectSection: 'Current Area',
      submitForm: 'Submit Form',
      submitting: 'Submitting...',
      reportSent: 'End Of Day Report sent successfully.',
      reportError: 'Could not send the report. Check EmailJS settings and try again.',
      continue: 'Continue',
      practice: 'Practice',
      quickQuiz: 'Quick Quiz',
      askCoach: 'Ask Coach',
      save: 'Save Settings'
    },
    fields: {
      shiftDate: 'Shift Date',
      managerName: 'Manager Name',
      shiftSummary: 'Shift Summary',
      complaints: 'Complaints',
      serviceRecovery: 'Service Recovery',
      staffIssues: 'Staff Issues',
      salesNotes: 'Sales Notes',
      urgentItems: 'Urgent Items'
    },
    copy: {
      commandTitle: 'Your venue needs attention in three areas before tonight.',
      commandBody: 'HESTIA turns service signals into operational action before they become revenue loss.',
      ownerTitle: 'Executive business intelligence for hidden leaks.',
      managerTitle: 'Daily execution intelligence for the floor.',
      academyTitle: 'Curated hospitality standards for every role.',
      endOfDayBody: 'Close out the shift — handoff notes, carry-forward items, and archived email report.',
      settingsBody: 'Manage language, access, and local preferences.',
      doctrine: 'Hospitality is not a department. It is a standard of attention.',
      recommendedAction: 'Recommended Action',
      recentSignals: 'Recent Signals',
      aiRecommendations: 'AI Recommendations'
    }
  },
  he: {
    app: {
      name: 'HESTIA',
      suffix: 'AI',
      tagline: '׳׳¢׳¨׳›׳× ׳‘׳™׳ ׳” ׳×׳₪׳¢׳•׳׳™׳× ׳׳¢׳•׳׳ ׳”׳׳™׳¨׳•׳—',
      secureAccess: '׳›׳ ׳™׳¡׳” ׳׳׳•׳‘׳˜׳—׳×',
      accessTitle: '׳”׳–׳ ׳§׳•׳“ ׳’׳™׳©׳”',
      accessBody: '׳׳¢׳¨׳›׳× AI ׳׳₪׳™ ׳”׳¨׳©׳׳•׳× ׳׳‘׳¢׳׳™׳, ׳׳ ׳”׳׳™׳ ׳•׳¦׳•׳•׳×׳™ ׳׳™׳¨׳•׳—.',
      codePlaceholder: '—',
      enter: '׳›׳ ׳™׳¡׳” ׳׳׳¢׳¨׳›׳×',
      invalid: '׳§׳•׳“ ׳’׳™׳©׳” ׳©׳’׳•׳™. ׳ ׳™׳×׳ ׳׳”׳©׳×׳׳©',
      employee: '׳¢׳•׳‘׳“',
      manager: '׳׳ ׳”׳',
      owner: '׳‘׳¢׳׳™׳',
      language: '׳©׳₪׳”',
      english: '׳׳ ׳’׳׳™׳×',
      hebrew: '׳¢׳‘׳¨׳™׳×',
      logout: '׳”׳×׳ ׳×׳§׳•׳×',
      today: '׳”׳™׳•׳',
      valueIdentified: '׳¢׳¨׳ ׳׳–׳•׳”׳”'
    },
    areas: {
      command: '׳׳¨׳›׳– ׳©׳׳™׳˜׳”',
      operations: '׳×׳₪׳¢׳•׳',
      academy: '׳׳§׳“׳׳™׳”',
      ownerIntelligence: '׳׳•׳“׳™׳¢׳™׳ ׳‘׳¢׳׳™׳',
      system: '׳׳¢׳¨׳›׳×'
    },
    areaDescriptions: {
      command: '׳×׳׳•׳ ׳× ׳׳¦׳‘ ׳—׳™׳” ׳©׳ ׳©׳™׳¨׳•׳× ׳•׳¢׳¡׳§',
      operations: '׳‘׳™׳¦׳•׳¢ ׳¨׳¦׳₪׳”, ׳©׳—׳–׳•׳¨ ׳•׳“׳™׳•׳•׳—',
      academy: '׳”׳›׳©׳¨׳”, ׳¡׳˜׳ ׳“׳¨׳˜׳™׳, ׳ ׳”׳׳™׳ ׳•׳™׳“׳¢',
      ownerIntelligence: '׳¨׳•׳•׳—, ׳“׳׳™׳₪׳•׳×, ׳–׳™׳›׳¨׳•׳ ׳•׳׳¡׳˜׳¨׳˜׳’׳™׳”',
      system: '׳©׳₪׳”, ׳’׳™׳©׳” ׳•׳”׳¢׳“׳₪׳•׳×'
    },
    pages: {
      commandCenter: '׳׳¨׳›׳– ׳©׳׳™׳˜׳”',
      actionBoard: '׳׳•׳— ׳₪׳¢׳•׳׳•׳×',
      eventOrchestrator: '׳×׳–׳׳•׳¨ ׳׳™׳¨׳•׳¢׳™׳',
      staffReadiness: '׳׳•׳›׳ ׳•׳× ׳¦׳•׳•׳×',
      serviceRecovery: '׳©׳—׳–׳•׳¨ ׳—׳•׳•׳™׳™׳× ׳׳•׳¨׳—',
      endOfDay: '׳“׳•׳—׳•׳× ׳¡׳•׳£ ׳™׳•׳',
      operationalNotes: '׳”׳¢׳¨׳•׳× ׳×׳₪׳¢׳•׳׳™׳•׳×',
      simulation: '׳¡׳™׳׳•׳׳¦׳™׳™׳× ׳׳•׳¨׳—',
      courses: '׳§׳•׳¨׳¡׳™׳',
      lessonPlayer: '׳ ׳’׳ ׳©׳™׳¢׳•׳¨',
      sopSheets: '׳“׳₪׳™ ׳ ׳”׳׳™׳',
      knowledgeLibrary: '׳¡׳₪׳¨׳™׳™׳× ׳™׳“׳¢',
      learningProgress: '׳”׳×׳§׳“׳׳•׳× ׳׳׳™׳“׳”',
      executiveOverview: '׳¡׳§׳™׳¨׳× ׳‘׳¢׳׳™׳',
      businessMRI: 'MRI ׳¢׳¡׳§׳™',
      profitLeaks: '׳“׳׳™׳₪׳•׳× ׳¨׳•׳•׳—',
      ownerReport: '׳“׳•׳— ׳‘׳¢׳׳™׳',
      businessMemory: '׳–׳™׳›׳¨׳•׳ ׳¢׳¡׳§׳™',
      strategicRecommendations: '׳”׳׳׳¦׳•׳× ׳׳¡׳˜׳¨׳˜׳’׳™׳•׳×',
      settings: '׳”׳’׳“׳¨׳•׳×'
    },
    ui: {
      collapsePanel: '׳¡׳’׳™׳¨׳× ׳×׳₪׳¨׳™׳˜',
      openPanel: '׳₪׳×׳™׳—׳× ׳×׳₪׳¨׳™׳˜',
      selectSection: '׳׳–׳•׳¨ ׳ ׳•׳›׳—׳™',
      submitForm: '׳©׳׳™׳—׳× ׳˜׳•׳₪׳¡',
      submitting: '׳©׳•׳׳—...',
      reportSent: '׳“׳•׳— ׳¡׳•׳£ ׳”׳™׳•׳ ׳ ׳©׳׳— ׳‘׳”׳¦׳׳—׳”.',
      reportError: '׳׳ ׳ ׳™׳×׳ ׳”׳™׳” ׳׳©׳׳•׳— ׳׳× ׳”׳“׳•׳—. ׳‘׳“׳•׳§ ׳׳× ׳”׳’׳“׳¨׳•׳× EmailJS ׳•׳ ׳¡׳” ׳©׳•׳‘.',
      continue: '׳”׳׳©׳',
      practice: '׳×׳¨׳’׳•׳',
      quickQuiz: '׳‘׳•׳—׳ ׳§׳¦׳¨',
      askCoach: '׳©׳׳ ׳׳× ׳”׳׳׳׳',
      save: '׳©׳׳™׳¨׳× ׳”׳’׳“׳¨׳•׳×'
    },
    fields: {
      shiftDate: '׳×׳׳¨׳™׳ ׳׳©׳׳¨׳×',
      managerName: '׳©׳ ׳׳ ׳”׳',
      shiftSummary: '׳¡׳™׳›׳•׳ ׳׳©׳׳¨׳×',
      complaints: '׳×׳׳•׳ ׳•׳×',
      serviceRecovery: '׳©׳—׳–׳•׳¨ ׳©׳™׳¨׳•׳×',
      staffIssues: '׳‘׳¢׳™׳•׳× ׳¦׳•׳•׳×',
      salesNotes: '׳”׳¢׳¨׳•׳× ׳׳›׳™׳¨׳”',
      urgentItems: '׳ ׳•׳©׳׳™׳ ׳“׳—׳•׳₪׳™׳'
    },
    copy: {
      commandTitle: '׳”׳¢׳¡׳§ ׳¦׳¨׳™׳ ׳×׳©׳•׳׳× ׳׳‘ ׳‘׳©׳׳•׳©׳” ׳׳–׳•׳¨׳™׳ ׳׳₪׳ ׳™ ׳”׳¢׳¨׳‘.',
      commandBody: 'HESTIA ׳׳×׳¨׳’׳׳× ׳׳™׳×׳•׳×׳™ ׳©׳™׳¨׳•׳× ׳׳₪׳¢׳•׳׳” ׳×׳₪׳¢׳•׳׳™׳× ׳׳₪׳ ׳™ ׳©׳”׳ ׳”׳•׳₪׳›׳™׳ ׳׳׳•׳‘׳“׳ ׳”׳›׳ ׳¡׳”.',
      ownerTitle: '׳׳•׳“׳™׳¢׳™׳ ׳¢׳¡׳§׳™ ׳׳‘׳¢׳׳™׳ ׳©׳׳–׳”׳” ׳“׳׳™׳₪׳•׳× ׳ ׳¡׳×׳¨׳•׳×.',
      managerTitle: '׳׳•׳“׳™׳¢׳™׳ ׳‘׳™׳¦׳•׳¢ ׳™׳•׳׳™ ׳׳¨׳¦׳₪׳× ׳”׳©׳™׳¨׳•׳×.',
      academyTitle: '׳¡׳˜׳ ׳“׳¨׳˜׳™׳ ׳׳§׳¦׳•׳¢׳™׳™׳ ׳׳›׳ ׳×׳₪׳§׳™׳“ ׳‘׳׳¢׳¨׳›׳×.',
      endOfDayBody: '׳©׳׳™׳—׳× ׳“׳•׳— ׳׳©׳׳¨׳× ׳׳•׳‘׳ ׳” ׳“׳¨׳ EmailJS.',
      settingsBody: '׳ ׳™׳”׳•׳ ׳©׳₪׳”, ׳’׳™׳©׳” ׳•׳”׳¢׳“׳₪׳•׳× ׳׳§׳•׳׳™׳•׳×.',
      doctrine: '׳׳™׳¨׳•׳— ׳׳™׳ ׳• ׳׳—׳׳§׳”. ׳׳™׳¨׳•׳— ׳”׳•׳ ׳¡׳˜׳ ׳“׳¨׳˜ ׳©׳ ׳×׳©׳•׳׳× ׳׳‘.',
      recommendedAction: '׳₪׳¢׳•׳׳” ׳׳•׳׳׳¦׳×',
      recentSignals: '׳׳™׳×׳•׳×׳™׳ ׳׳—׳¨׳•׳ ׳™׳',
      aiRecommendations: '׳”׳׳׳¦׳•׳× AI'
    }
  }
}

