// AI agent candidate map for HESTIA.
// Defines future agent architectures, their inputs, reasoning logic, and outputs.
// This is a planning document only — no agents are implemented, no prompts run, no API calls made.
// All agents are recommendation-first. No autonomous actions should be enabled without human approval.

// ─── Phase legend ──────────────────────────────────────────────────────────────
// MVP      — core to the first usable product
// Phase 2  — next major release after MVP
// Phase 3  — mature product capability
// Future   — long-horizon or dependent on external data

// ─── Risk level legend ─────────────────────────────────────────────────────────
// low    — purely informational recommendations
// medium — recommendations that influence scheduling, assignments, or costs
// high   — recommendations that affect guests directly or involve sensitive data

export const HOSPITALITY_AGENTS = [
  {
    agentName: 'ShiftBrainAgent',
    purpose: 'Real-time operational intelligence during an active shift — surfaces signals, patterns, and priority alerts.',
    inputEntities: ['Shift', 'Reservation', 'VisitOrParty', 'Incident', 'Checklist', 'Note', 'StaffMember', 'Section'],
    inputEvents: ['shift_started', 'guest_arrived', 'table_assigned', 'incident_created', 'checklist_completed', 'manager_note_created'],
    memoryDependencies: ['GuestPreferences', 'VIPHandlingNotes', 'RecurringIncidentPatterns', 'StaffStrengths'],
    reasoningLogic: [
      'Classify incoming signals by severity and type',
      'Detect threshold breaches (wait times, section imbalance, incident density)',
      'Surface the most operationally urgent item for manager attention',
      'Identify patterns across the shift window (e.g. complaints clustering by station)',
      'Generate a shift focus narrative based on open signals',
    ],
    outputs: ['Operational status summary', 'Prioritized alert list', 'Focus recommendation for manager'],
    decisionsSupported: ['staffing', 'serviceRecovery', 'staffCoaching'],
    riskLevel: 'medium',
    complexity: 'high',
    phase: 'MVP',
    moatPotential: 'Very high — real-time shift intelligence is rare in hospitality software.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Shift Brain deterministic intelligence layer is already implemented in shiftBrainService.js. This agent extends it with AI-generated narrative and pattern detection.',
  },
  {
    agentName: 'InventoryIntelligenceAgent',
    purpose: 'Monitor inventory levels, detect variance patterns, and recommend ordering and control actions.',
    inputEntities: ['InventoryItem', 'StockCount', 'WasteLog', 'PurchaseOrder', 'Supplier', 'RecipeVersion', 'Forecast'],
    inputEvents: ['stock_count_completed', 'waste_logged', 'supplier_delivery_delayed'],
    memoryDependencies: ['SupplierReliabilityPatterns', 'VenueDemandPatterns'],
    reasoningLogic: [
      'Calculate theoretical usage from recipe × cover data',
      'Compare theoretical to physical count to compute variance',
      'Categorize variance by likely cause (waste, overpour, count error, unexplained)',
      'Monitor par levels and generate reorder alerts',
      'Detect supplier reliability trends',
    ],
    outputs: ['Variance report with categorized causes', 'Reorder alert with suggested quantities', 'Supplier risk flag'],
    decisionsSupported: ['inventory', 'menu'],
    riskLevel: 'medium',
    complexity: 'high',
    phase: 'Phase 2',
    moatPotential: 'High — linked recipe-to-inventory cost calculation is a deep moat.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Requires POS integration and recipe-to-ingredient cost data before meaningful output.',
  },
  {
    agentName: 'GuestMemoryAgent',
    purpose: 'Distill visit data into structured guest memories and surface them at the right moment.',
    inputEntities: ['Guest', 'VisitOrParty', 'Reservation', 'Incident', 'ServiceRecoveryAction', 'Memory'],
    inputEvents: ['guest_arrived', 'shift_ended', 'recovery_action_taken', 'manager_note_created', 'review_received'],
    memoryDependencies: ['GuestPreferences', 'GuestAllergiesAndDietaryRestrictions', 'ServiceRecoveryHistory', 'VIPHandlingNotes'],
    reasoningLogic: [
      'Extract durable preference signals from visit events',
      'Assign confidence scores based on repetition and explicitness',
      'Flag low-confidence inferences for human review before storing',
      'Trigger memory recall for returning guests with relevant context',
      'Detect pattern of recovery history and elevate care level for next visit',
    ],
    outputs: ['Guest memory brief for upcoming visit', 'New memory records for review', 'VIP alert for arrival'],
    decisionsSupported: ['serviceRecovery', 'staffing'],
    riskLevel: 'high',
    complexity: 'high',
    phase: 'Phase 2',
    moatPotential: 'Extremely high — genuine guest memory is the deepest hospitality moat.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Must be role-gated. Allergy data requires human verification before storage. No inferences about health without explicit declaration.',
  },
  {
    agentName: 'BarManagerAgent',
    purpose: 'Monitor bar performance including throughput, pour cost, comp rates, and recipe consistency.',
    inputEntities: ['Check', 'MenuItem', 'RecipeVersion', 'InventoryItem', 'StaffMember', 'WasteLog', 'StockCount'],
    inputEvents: ['drink_prepared', 'stock_count_completed', 'waste_logged', 'shift_ended'],
    memoryDependencies: ['MenuWinnersAndLosers', 'SupplierReliabilityPatterns'],
    reasoningLogic: [
      'Calculate pour cost by cocktail from recipe × ingredient cost',
      'Compare comp rate by bartender against shift average',
      'Detect throughput bottlenecks by day-part and station',
      'Identify recipe variants (modifier usage, substitutions) that deviate from standard',
    ],
    outputs: ['Bar performance summary', 'Pour cost report', 'Comp anomaly flag', 'Throughput alert'],
    decisionsSupported: ['inventory', 'menu', 'staffCoaching'],
    riskLevel: 'medium',
    complexity: 'high',
    phase: 'Phase 2',
    moatPotential: 'High — bar cost intelligence is typically spreadsheet-based; real-time is rare.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Comp rate analysis must be contextual — high comps may indicate quality control issues, not just generosity.',
  },
  {
    agentName: 'KitchenFlowAgent',
    purpose: 'Monitor ticket times, kitchen load, and allergy modifier accuracy during service.',
    inputEntities: ['Check', 'MenuItem', 'Station', 'PrepBatch', 'Shift'],
    inputEvents: ['item_fired_to_kitchen', 'order_opened', 'shift_started'],
    memoryDependencies: ['RecurringIncidentPatterns'],
    reasoningLogic: [
      'Track ticket times by station and course',
      'Detect load imbalances between stations',
      'Flag allergy modifiers that are not confirmed by the kitchen',
      'Surface pacing delays to expeditor or manager',
    ],
    outputs: ['Ticket time alert', 'Station load alert', 'Allergy modifier risk flag'],
    decisionsSupported: ['staffing', 'serviceRecovery'],
    riskLevel: 'high',
    complexity: 'high',
    phase: 'Phase 3',
    moatPotential: 'High — kitchen intelligence requires deep POS and KDS integration.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Requires KDS or POS integration. Allergy modifier detection is safety-critical and must be human-confirmed.',
  },
  {
    agentName: 'ServiceRecoveryAgent',
    purpose: 'Support managers in selecting and recording the right recovery action when a guest experience fails.',
    inputEntities: ['Incident', 'Guest', 'VIPGuest', 'ServiceRecoveryAction', 'Memory', 'Check'],
    inputEvents: ['complaint_submitted', 'incident_created'],
    memoryDependencies: ['ServiceRecoveryHistory', 'GuestPreferences', 'VIPHandlingNotes'],
    reasoningLogic: [
      'Classify incident type and severity',
      'Check guest memory for prior recovery history',
      'Recommend recovery action based on incident type, severity, and guest profile',
      'Flag if suggested action exceeds manager comp authority',
      'Generate recovery note for guest memory',
    ],
    outputs: ['Recovery action recommendation', 'Comp amount suggestion', 'Manager alert for VIP', 'Memory update request'],
    decisionsSupported: ['serviceRecovery'],
    riskLevel: 'high',
    complexity: 'medium',
    phase: 'Phase 2',
    moatPotential: 'High — contextual, memory-aware recovery is genuinely differentiated.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'The agent recommends; the manager decides. Recovery actions with cost implications always require approval.',
  },
  {
    agentName: 'StaffCoachingAgent',
    purpose: 'Identify staff development needs from operational data and generate coaching recommendations.',
    inputEntities: ['StaffMember', 'Incident', 'CoachingNote', 'SOP', 'TrainingModule', 'ShiftReport'],
    inputEvents: ['incident_created', 'shift_ended', 'staff_coaching_note_created'],
    memoryDependencies: ['StaffStrengths', 'StaffDevelopmentAreas', 'RecurringIncidentPatterns'],
    reasoningLogic: [
      'Detect patterns of repeat incidents attributed to the same staff member',
      'Cross-reference incident type with available training modules',
      'Identify when coaching note exists but no follow-up has been recorded',
      'Surface positive patterns for recognition alongside corrective recommendations',
      'Flag when training completion lags behind required certification timeline',
    ],
    outputs: ['Coaching note recommendation', 'Training module suggestion', 'Recognition highlight', 'Certification expiry alert'],
    decisionsSupported: ['staffCoaching', 'staffing'],
    riskLevel: 'high',
    complexity: 'medium',
    phase: 'Phase 2',
    moatPotential: 'Medium — coaching intelligence is valuable but requires careful handling of performance data.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'All coaching outputs must go through manager review before being shared with staff. Performance data is sensitive.',
  },
  {
    agentName: 'EventPlanningAgent',
    purpose: 'Support event planning from booking to execution with intelligent configuration recommendations.',
    inputEntities: ['EventBooking', 'EventClient', 'Package', 'SeatingPlan', 'StaffMember', 'InventoryItem'],
    inputEvents: ['reservation_created', 'event_started', 'event_ended'],
    memoryDependencies: ['EventClientPreferences', 'VenueDemandPatterns'],
    reasoningLogic: [
      'Generate staffing plan based on guest count and package type',
      'Calculate inventory requirements from package menu',
      'Check accessibility requirements against confirmed space configuration',
      'Surface prior event client preferences for personalization',
      'Flag risk signals in the booking (accessibility gap, short lead time, high guest count)',
    ],
    outputs: ['Event staffing plan suggestion', 'Inventory pull list', 'Accessibility checklist', 'Client personalization brief'],
    decisionsSupported: ['eventPlanning', 'inventory'],
    riskLevel: 'medium',
    complexity: 'medium',
    phase: 'Phase 2',
    moatPotential: 'High — event intelligence with client memory is a strong enterprise hospitality moat.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Staffing ratios and inventory calculations require baseline calibration data before reliable output.',
  },
  {
    agentName: 'AccessibilityPlanningAgent',
    purpose: 'Ensure all accessibility requirements are captured, verified, and communicated before they are needed.',
    inputEntities: ['AccessibilityRequirement', 'Guest', 'Reservation', 'EventBooking', 'Venue', 'GuestRoom'],
    inputEvents: ['accessibility_requirement_added', 'reservation_created', 'guest_arrived'],
    memoryDependencies: ['GuestAccessibilityRequirements'],
    reasoningLogic: [
      'Cross-reference declared requirements with the assigned space configuration',
      'Confirm the accessibility path from entrance to assigned seat or room',
      'Alert the right staff role with the appropriate briefing (host, server, housekeeper)',
      'Flag requirements that have not been verified within 24h of arrival',
    ],
    outputs: ['Accessibility verification checklist', 'Staff briefing for relevant roles', 'Path confirmation alert', 'Requirement gap warning'],
    decisionsSupported: ['hotelReadiness', 'eventPlanning', 'staffing'],
    riskLevel: 'high',
    complexity: 'medium',
    phase: 'Phase 2',
    moatPotential: 'High — very few hospitality systems treat accessibility with operational intelligence.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Accessibility data is protected health information. Strict role-gating required. Agent output must be human-verified before finalizing.',
  },
  {
    agentName: 'SupplierIntelligenceAgent',
    purpose: 'Track supplier performance patterns and surface procurement risks before they affect operations.',
    inputEntities: ['Supplier', 'PurchaseOrder', 'InvoiceLine', 'InventoryItem', 'StockCount'],
    inputEvents: ['supplier_delivery_delayed', 'stock_count_completed'],
    memoryDependencies: ['SupplierReliabilityPatterns'],
    reasoningLogic: [
      'Track delivery accuracy and lead time variance by supplier',
      'Detect cost trend increases across invoice lines',
      'Flag single-source dependencies for critical items',
      'Surface backup supplier qualification recommendations',
    ],
    outputs: ['Supplier reliability report', 'Cost trend alert', 'Single-source risk flag', 'Backup supplier recommendation'],
    decisionsSupported: ['inventory'],
    riskLevel: 'low',
    complexity: 'medium',
    phase: 'Phase 3',
    moatPotential: 'Medium — valuable, but a late-stage capability.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: false,
    notes: 'Recommendations are informational. No supplier-facing actions should be automated.',
  },
  {
    agentName: 'MenuEngineeringAgent',
    purpose: 'Analyze menu performance across revenue, margin, and sales mix and recommend adjustments.',
    inputEntities: ['MenuItem', 'RecipeVersion', 'InventoryItem', 'InvoiceLine', 'Check', 'KPISnapshot'],
    inputEvents: ['shift_ended'],
    memoryDependencies: ['MenuWinnersAndLosers'],
    reasoningLogic: [
      'Calculate contribution margin per item from recipe cost and menu price',
      'Segment items into star, plow horse, puzzle, and dog categories',
      'Identify items with high popularity but low margin that could be repriced',
      'Detect items with low popularity and low margin that could be removed',
      'Surface seasonal substitution opportunities based on ingredient cost trends',
    ],
    outputs: ['Menu engineering matrix', 'Repricing recommendation', 'Seasonal substitution suggestion', 'Item removal candidate list'],
    decisionsSupported: ['menu', 'inventory'],
    riskLevel: 'low',
    complexity: 'high',
    phase: 'Phase 3',
    moatPotential: 'High — menu engineering AI is a significant competitive differentiator.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Menu price changes must always be owner-approved. This agent prepares data; humans make decisions.',
  },
  {
    agentName: 'PostShiftIntelligenceAgent',
    purpose: 'Generate a structured post-shift summary and extract lessons, coaching flags, and memory candidates.',
    inputEntities: ['ShiftReport', 'Incident', 'Note', 'CoachingNote', 'KPISnapshot'],
    inputEvents: ['shift_ended'],
    memoryDependencies: ['OperationalLessonsLearned', 'RecurringIncidentPatterns'],
    reasoningLogic: [
      'Synthesize shift events into a narrative summary',
      'Extract incidents that require a coaching note',
      'Identify patterns that suggest a recurring issue',
      'Suggest memory records for distillation',
      'Generate a briefing entry for the next shift manager',
    ],
    outputs: ['Shift narrative summary', 'Coaching flag list', 'Memory distillation candidates', 'Next-shift briefing note'],
    decisionsSupported: ['staffCoaching'],
    riskLevel: 'low',
    complexity: 'medium',
    phase: 'MVP',
    moatPotential: 'Medium — useful, but the real moat is the memory system it feeds.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: false,
    notes: 'Summaries are informational. Coaching flags require manager review before any action.',
  },
  {
    agentName: 'HotelOperationsBrain',
    purpose: 'Real-time operational intelligence for hotel front office and housekeeping coordination.',
    inputEntities: ['Stay', 'GuestRoom', 'HousekeepingTask', 'MaintenanceTicket', 'Forecast', 'Guest'],
    inputEvents: ['room_status_changed', 'maintenance_ticket_opened', 'service_request_created'],
    memoryDependencies: ['GuestPreferences', 'VIPHandlingNotes', 'RoomAndAssetRecurringIssues'],
    reasoningLogic: [
      'Monitor arrival readiness by cross-referencing arrivals against room status',
      'Alert front desk when an arrival is within 1h and room is not inspected',
      'Flag rooms with open maintenance tickets before assignment',
      'Detect clean-to-inspect lag by floor or housekeeper',
      'Generate VIP arrival brief from guest memory',
    ],
    outputs: ['Arrival readiness alert', 'Room status dashboard signal', 'VIP arrival brief', 'Maintenance risk flag'],
    decisionsSupported: ['hotelReadiness'],
    riskLevel: 'medium',
    complexity: 'high',
    phase: 'Phase 3',
    moatPotential: 'High — hotel operations intelligence is underserved in the mid-market.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'Depends on real-time room status data integration. Not viable without that feed.',
  },
  {
    agentName: 'HospitalityMemoryEngine',
    purpose: 'Long-term memory distillation and retrieval across all memory types for all agents.',
    inputEntities: ['Memory', 'Guest', 'StaffMember', 'Incident', 'EventClient', 'ShiftReport'],
    inputEvents: ['shift_ended', 'event_ended', 'review_received'],
    memoryDependencies: ['All memory types'],
    reasoningLogic: [
      'Aggregate signals from shift-level events into durable memory candidates',
      'Assign confidence scores and flag low-confidence inferences for human review',
      'Detect when a memory should be revoked due to contradicting evidence',
      'Retrieve relevant memory at the right moment for the right role',
      'Maintain provenance — every memory links to its source events',
    ],
    outputs: ['New memory candidates for review', 'Memory recall brief for specific context', 'Memory revocation flag'],
    decisionsSupported: ['serviceRecovery', 'staffing', 'eventPlanning', 'hotelReadiness'],
    riskLevel: 'high',
    complexity: 'very high',
    phase: 'Future',
    moatPotential: 'Extremely high — a genuine, compound, hospitality-aware memory system is rare.',
    shouldBeAutonomousNow: false,
    requiresHumanApproval: true,
    notes: 'The memory engine is the long-term compound moat of HESTIA. It must be built slowly and carefully. Privacy and provenance are non-negotiable.',
  },
]

// ─── Agent index by phase ────────────────────────────────────────────────────────

export const AGENT_PHASES = {
  MVP: HOSPITALITY_AGENTS.filter(a => a.phase === 'MVP').map(a => a.agentName),
  Phase2: HOSPITALITY_AGENTS.filter(a => a.phase === 'Phase 2').map(a => a.agentName),
  Phase3: HOSPITALITY_AGENTS.filter(a => a.phase === 'Phase 3').map(a => a.agentName),
  Future: HOSPITALITY_AGENTS.filter(a => a.phase === 'Future').map(a => a.agentName),
}

export const hospitalityAgentMap = {
  agents: HOSPITALITY_AGENTS,
  phases: AGENT_PHASES,
}
