// Canonical hospitality entity definitions for HESTIA.
// This file defines entity schemas, metadata, and field groups only.
// It does not contain operational records, fake data, or runtime behavior.
// Use this as the source of truth for future database design, AI agents, and memory systems.

// ─── Priority legend ───────────────────────────────────────────────────────────
// P0 — core product, needed on day one
// P1 — needed in first major release
// P2 — planned, not immediately required
// Future — long-horizon capability

// ─── A. Venue / Space ──────────────────────────────────────────────────────────

export const VENUE_ENTITIES = {
  Venue: {
    category: 'venue',
    domain: 'space',
    description: 'Top-level physical or conceptual location that HESTIA operates within.',
    typicalFields: ['id', 'name', 'type', 'timezone', 'operatingHours', 'currency', 'locale', 'contactInfo', 'licenseInfo'],
    relatedEntities: ['Brand', 'Property', 'Department', 'ServiceArea'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  Brand: {
    category: 'venue',
    domain: 'space',
    description: 'The owning brand or hospitality group above the venue level.',
    typicalFields: ['id', 'name', 'standards', 'guidelineDocuments', 'conceptDescriptions'],
    relatedEntities: ['Venue', 'Property', 'Concept'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P1',
  },
  Property: {
    category: 'venue',
    domain: 'space',
    description: 'A physical building or site within a brand that may contain multiple venues or concepts.',
    typicalFields: ['id', 'brandId', 'address', 'accessibilityFeatures', 'parkingInfo', 'units'],
    relatedEntities: ['Brand', 'Venue', 'GuestRoom', 'Ballroom'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  Concept: {
    category: 'venue',
    domain: 'space',
    description: 'A distinct food & beverage or service concept within a property (e.g. rooftop bar, main dining room).',
    typicalFields: ['id', 'propertyId', 'name', 'style', 'targetGuest', 'serviceModel', 'menuIds'],
    relatedEntities: ['Venue', 'Menu', 'ServiceArea'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  Department: {
    category: 'venue',
    domain: 'space',
    description: 'Functional department within the venue (e.g. FOH, BOH, Housekeeping, Events).',
    typicalFields: ['id', 'venueId', 'name', 'managerId', 'staffIds'],
    relatedEntities: ['Venue', 'StaffMember', 'Manager'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P1',
  },
  ServiceArea: {
    category: 'venue',
    domain: 'space',
    description: 'A named area that staff are assigned to serve (e.g. Section A, Bar Top, Patio).',
    typicalFields: ['id', 'venueId', 'name', 'seatCount', 'type', 'accessibilityCompliant'],
    relatedEntities: ['Venue', 'Table', 'BarSeat', 'StaffMember', 'Shift'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  StorageLocation: {
    category: 'venue',
    domain: 'space',
    description: 'Named storage area for inventory (walk-in, dry storage, wine cellar, speed rack).',
    typicalFields: ['id', 'venueId', 'name', 'type', 'temperatureControlled', 'capacity'],
    relatedEntities: ['InventoryItem', 'StockCount'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P1',
  },
  Table: {
    category: 'venue',
    domain: 'space',
    description: 'A dine-in table with position, capacity, and accessibility attributes.',
    typicalFields: ['id', 'serviceAreaId', 'number', 'seatCount', 'isAccessible', 'shape', 'position'],
    relatedEntities: ['ServiceArea', 'Reservation', 'VisitOrParty'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  BarSeat: {
    category: 'venue',
    domain: 'space',
    description: 'An individual seat at the bar counter.',
    typicalFields: ['id', 'serviceAreaId', 'number', 'isAccessible'],
    relatedEntities: ['ServiceArea', 'VisitOrParty'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  CounterSeat: {
    category: 'venue',
    domain: 'space',
    description: 'A seat at a chef counter, raw bar, or tasting counter.',
    typicalFields: ['id', 'serviceAreaId', 'number', 'isAccessible'],
    relatedEntities: ['ServiceArea', 'VisitOrParty'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  PrivateRoom: {
    category: 'venue',
    domain: 'space',
    description: 'A bookable private or semi-private dining room.',
    typicalFields: ['id', 'venueId', 'name', 'minCapacity', 'maxCapacity', 'isAccessible', 'avEquipment', 'minimumSpend'],
    relatedEntities: ['EventBooking', 'Reservation'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  Ballroom: {
    category: 'venue',
    domain: 'space',
    description: 'Large event space within a hotel or event property.',
    typicalFields: ['id', 'propertyId', 'name', 'capacity', 'isAccessible', 'floorPlanOptions', 'avCapabilities'],
    relatedEntities: ['Property', 'EventBooking', 'SeatingPlan'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  GuestRoom: {
    category: 'venue',
    domain: 'space',
    description: 'A hotel or lodging room assignable to a guest stay.',
    typicalFields: ['id', 'propertyId', 'number', 'type', 'floor', 'isAccessible', 'bedConfiguration', 'status'],
    relatedEntities: ['Stay', 'HousekeepingTask', 'MaintenanceTicket'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
}

// ─── B. People ─────────────────────────────────────────────────────────────────

export const PEOPLE_ENTITIES = {
  Guest: {
    category: 'people',
    domain: 'guest',
    description: 'Any person who experiences the hospitality service.',
    typicalFields: ['id', 'name', 'contactInfo', 'language', 'dietaryRestrictions', 'allergies', 'visitCount', 'firstVisit', 'lastVisit'],
    relatedEntities: ['Reservation', 'VisitOrParty', 'Stay', 'ServiceRecoveryAction', 'Memory'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  VIPGuest: {
    category: 'people',
    domain: 'guest',
    description: 'A guest flagged for elevated attention due to spend, influence, loyalty, or recovery sensitivity.',
    typicalFields: ['guestId', 'vipReason', 'handlingNotes', 'preferredServer', 'notifyManagement'],
    relatedEntities: ['Guest', 'Memory', 'Manager'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  RegularGuest: {
    category: 'people',
    domain: 'guest',
    description: 'A guest with a documented pattern of return visits.',
    typicalFields: ['guestId', 'visitFrequency', 'preferredTime', 'preferredSection', 'usualOrder'],
    relatedEntities: ['Guest', 'Memory'],
    databaseCandidate: false,
    memoryCandidate: true,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  FirstTimeGuest: {
    category: 'people',
    domain: 'guest',
    description: 'A guest on their confirmed first visit — triggers first-impression protocols.',
    typicalFields: ['guestId', 'firstVisitDate', 'referralSource'],
    relatedEntities: ['Guest', 'VisitOrParty'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  StaffMember: {
    category: 'people',
    domain: 'staff',
    description: 'An employee with a role, skills, and shift assignment history.',
    typicalFields: ['id', 'name', 'role', 'skills', 'hireDate', 'certifications', 'languagesSpoken', 'performanceNotes'],
    relatedEntities: ['Role', 'Skill', 'Shift', 'CoachingNote', 'ServiceArea'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  Role: {
    category: 'people',
    domain: 'staff',
    description: 'A defined job role with responsibilities and permissions.',
    typicalFields: ['id', 'name', 'department', 'permissions', 'responsibilities', 'requiredCertifications'],
    relatedEntities: ['StaffMember', 'Shift'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P0',
  },
  Skill: {
    category: 'people',
    domain: 'staff',
    description: 'A specific capability a staff member possesses (e.g. wine service, barista, accessible service).',
    typicalFields: ['id', 'name', 'category', 'assessmentMethod'],
    relatedEntities: ['StaffMember', 'TrainingModule'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  Manager: {
    category: 'people',
    domain: 'staff',
    description: 'A staff member with elevated operational authority on shift.',
    typicalFields: ['staffMemberId', 'decisionAuthority', 'compLimit', 'escalationContact'],
    relatedEntities: ['StaffMember', 'Incident', 'ServiceRecoveryAction', 'ShiftReport'],
    databaseCandidate: false,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  SupplierContact: {
    category: 'people',
    domain: 'supply',
    description: 'A named contact at a supplier or distributor.',
    typicalFields: ['id', 'supplierId', 'name', 'phone', 'email', 'role', 'responsePattern'],
    relatedEntities: ['Supplier', 'PurchaseOrder'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  EventPlanner: {
    category: 'people',
    domain: 'events',
    description: 'Internal or external coordinator responsible for an event execution.',
    typicalFields: ['id', 'name', 'contactInfo', 'assignedEvents', 'certifications'],
    relatedEntities: ['EventBooking', 'EventClient'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P2',
  },
  EventClient: {
    category: 'people',
    domain: 'events',
    description: 'The client or organization booking an event.',
    typicalFields: ['id', 'name', 'contactInfo', 'pastEvents', 'preferences', 'budgetRange', 'accessibilityRequirements'],
    relatedEntities: ['EventBooking', 'EventPlanner'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P2',
  },
}

// ─── C. Commercial ─────────────────────────────────────────────────────────────

export const COMMERCIAL_ENTITIES = {
  Reservation: {
    category: 'commercial',
    domain: 'booking',
    description: 'A pre-committed guest promise to occupy a table, room, or space at a specific time.',
    typicalFields: ['id', 'guestId', 'partySize', 'dateTime', 'tableId', 'specialRequests', 'celebrationFlag', 'source', 'status', 'accessibilityRequirements'],
    relatedEntities: ['Guest', 'Table', 'VisitOrParty', 'ServiceArea'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  WaitlistEntry: {
    category: 'commercial',
    domain: 'booking',
    description: 'A guest waiting for availability without a confirmed reservation.',
    typicalFields: ['id', 'guestId', 'partySize', 'quoteTime', 'joinedAt', 'contactMethod', 'accessibilityRequirements', 'status'],
    relatedEntities: ['Guest', 'VisitOrParty'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  Stay: {
    category: 'commercial',
    domain: 'lodging',
    description: 'A hotel or accommodation booking for a guest over one or more nights.',
    typicalFields: ['id', 'guestId', 'roomId', 'checkIn', 'checkOut', 'folio', 'specialRequests', 'accessibilityRequirements', 'ratePlan'],
    relatedEntities: ['Guest', 'GuestRoom', 'Folio', 'HousekeepingTask'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  EventBooking: {
    category: 'commercial',
    domain: 'events',
    description: 'A confirmed commercial event reservation for a group or organization.',
    typicalFields: ['id', 'clientId', 'spaceId', 'date', 'guestCount', 'package', 'minimumRevenue', 'accessibilityRequirements', 'status', 'setupRequirements'],
    relatedEntities: ['EventClient', 'PrivateRoom', 'Ballroom', 'SeatingPlan', 'EventPlanner'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  Menu: {
    category: 'commercial',
    domain: 'food_beverage',
    description: 'A versioned collection of menu items active for a concept during a period.',
    typicalFields: ['id', 'conceptId', 'name', 'activeFrom', 'activeTo', 'version', 'items', 'menuType'],
    relatedEntities: ['MenuItem', 'Concept', 'RecipeVersion'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  MenuItem: {
    category: 'commercial',
    domain: 'food_beverage',
    description: 'A single item on a menu with pricing, recipe linkage, and allergen data.',
    typicalFields: ['id', 'menuId', 'name', 'description', 'price', 'category', 'allergens', 'recipeVersionId', 'isActive', 'costOfGoods'],
    relatedEntities: ['Menu', 'RecipeVersion', 'InventoryItem'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  Package: {
    category: 'commercial',
    domain: 'events',
    description: 'A bundled offering combining space, food, beverage, and services for events or stays.',
    typicalFields: ['id', 'name', 'includedItems', 'pricePerHead', 'minimumGuests', 'duration', 'accessibilityOptions'],
    relatedEntities: ['EventBooking', 'Stay', 'MenuItem'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  Check: {
    category: 'commercial',
    domain: 'finance',
    description: 'The guest-facing bill for a dining visit or bar tab.',
    typicalFields: ['id', 'visitId', 'items', 'subtotal', 'tax', 'gratuity', 'total', 'paymentMethod', 'comps', 'openedAt', 'closedAt'],
    relatedEntities: ['VisitOrParty', 'MenuItem', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  Folio: {
    category: 'commercial',
    domain: 'finance',
    description: 'The consolidated account for a hotel stay covering room charges and incidentals.',
    typicalFields: ['id', 'stayId', 'charges', 'payments', 'balance', 'status'],
    relatedEntities: ['Stay', 'Guest'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  Invoice: {
    category: 'commercial',
    domain: 'finance',
    description: 'A formal post-event or post-stay invoice issued to a client or corporate account.',
    typicalFields: ['id', 'eventBookingId', 'lineItems', 'subtotal', 'tax', 'total', 'issuedAt', 'paidAt', 'status'],
    relatedEntities: ['EventBooking', 'Stay', 'EventClient'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
}

// ─── D. Operational ────────────────────────────────────────────────────────────

export const OPERATIONAL_ENTITIES = {
  Shift: {
    category: 'operational',
    domain: 'scheduling',
    description: 'A defined work period for a staff team with assigned sections and service targets.',
    typicalFields: ['id', 'venueId', 'date', 'startTime', 'endTime', 'staffAssignments', 'coverCount', 'shiftType', 'managerId'],
    relatedEntities: ['StaffMember', 'ServiceArea', 'ShiftReport', 'Manager'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  Section: {
    category: 'operational',
    domain: 'service',
    description: 'A set of tables or seats assigned to a specific server for a shift.',
    typicalFields: ['id', 'shiftId', 'serviceAreaId', 'serverId', 'tableIds'],
    relatedEntities: ['Shift', 'StaffMember', 'ServiceArea', 'Table'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  Station: {
    category: 'operational',
    domain: 'service',
    description: 'A service or production station (bar station, expo, pastry, etc.) staffed during a shift.',
    typicalFields: ['id', 'shiftId', 'name', 'staffIds', 'equipment'],
    relatedEntities: ['Shift', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P1',
  },
  RecipeVersion: {
    category: 'operational',
    domain: 'food_beverage',
    description: 'A versioned specification of a recipe including ingredients, quantities, and method.',
    typicalFields: ['id', 'menuItemId', 'version', 'ingredients', 'method', 'yield', 'cost', 'activeFrom', 'author'],
    relatedEntities: ['MenuItem', 'InventoryItem', 'PrepBatch'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  PrepBatch: {
    category: 'operational',
    domain: 'food_beverage',
    description: 'A recorded production run of a recipe or prep item before service.',
    typicalFields: ['id', 'recipeVersionId', 'quantity', 'unit', 'preparedBy', 'shiftId', 'expiresAt', 'storageLocation'],
    relatedEntities: ['RecipeVersion', 'Shift', 'StaffMember', 'StorageLocation'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: false,
    priority: 'P1',
  },
  MiseEnPlaceTask: {
    category: 'operational',
    domain: 'service',
    description: 'A specific pre-service preparation task (cutting citrus, polishing glasses, setting tables).',
    typicalFields: ['id', 'shiftId', 'assignedTo', 'description', 'completedAt', 'status'],
    relatedEntities: ['Shift', 'StaffMember', 'Checklist'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: false,
    priority: 'P1',
  },
  HousekeepingTask: {
    category: 'operational',
    domain: 'lodging',
    description: 'A room cleaning or turn-down assignment for housekeeping staff.',
    typicalFields: ['id', 'roomId', 'type', 'assignedTo', 'status', 'startedAt', 'completedAt', 'inspectedBy', 'notes'],
    relatedEntities: ['GuestRoom', 'StaffMember', 'Stay'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  MaintenanceTicket: {
    category: 'operational',
    domain: 'facilities',
    description: 'A reported and tracked repair or maintenance need for a space or asset.',
    typicalFields: ['id', 'locationId', 'assetId', 'description', 'priority', 'reportedBy', 'assignedTo', 'status', 'openedAt', 'closedAt', 'recurrenceCount'],
    relatedEntities: ['GuestRoom', 'Venue', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  Checklist: {
    category: 'operational',
    domain: 'service',
    description: 'A structured list of tasks that must be completed before, during, or after a shift or event.',
    typicalFields: ['id', 'name', 'type', 'items', 'assignedTo', 'shiftId', 'completedAt', 'status'],
    relatedEntities: ['Shift', 'StaffMember', 'MiseEnPlaceTask'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: false,
    priority: 'P0',
  },
  Incident: {
    category: 'operational',
    domain: 'service',
    description: 'Any unexpected event that interrupted or degraded the guest experience or operations.',
    typicalFields: ['id', 'shiftId', 'type', 'description', 'severity', 'affectedGuests', 'reportedBy', 'resolvedBy', 'resolution', 'timestamp', 'isResolved'],
    relatedEntities: ['Shift', 'Guest', 'StaffMember', 'ServiceRecoveryAction', 'CoachingNote'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  ServiceRecoveryAction: {
    category: 'operational',
    domain: 'service',
    description: 'A documented action taken to recover a guest experience after a failure.',
    typicalFields: ['id', 'incidentId', 'guestId', 'actionType', 'description', 'takenBy', 'approvedBy', 'cost', 'guestResponse', 'timestamp'],
    relatedEntities: ['Incident', 'Guest', 'StaffMember', 'Manager'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  VisitOrParty: {
    category: 'operational',
    domain: 'service',
    description: 'A single guest or party visit to the venue on a given occasion.',
    typicalFields: ['id', 'reservationId', 'guestId', 'partySize', 'arrivedAt', 'seatedAt', 'departedAt', 'tableId', 'serverId', 'occasion'],
    relatedEntities: ['Guest', 'Reservation', 'Table', 'StaffMember', 'Check'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
}

// ─── E. Resources ──────────────────────────────────────────────────────────────

export const RESOURCE_ENTITIES = {
  InventoryItem: {
    category: 'resources',
    domain: 'inventory',
    description: 'Any trackable ingredient, beverage, supply, or asset held in stock.',
    typicalFields: ['id', 'name', 'category', 'unit', 'parLevel', 'currentStock', 'location', 'supplierId', 'costPerUnit', 'lastCounted'],
    relatedEntities: ['Supplier', 'PurchaseOrder', 'StockCount', 'WasteLog', 'RecipeVersion'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  Ingredient: {
    category: 'resources',
    domain: 'inventory',
    description: 'A food or beverage ingredient used in recipes.',
    typicalFields: ['id', 'inventoryItemId', 'allergenFlags', 'perishable', 'shelfLife'],
    relatedEntities: ['InventoryItem', 'RecipeVersion'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P1',
  },
  SpiritSKU: {
    category: 'resources',
    domain: 'inventory',
    description: 'A specific bottle SKU for a spirit (brand, expression, size).',
    typicalFields: ['id', 'inventoryItemId', 'brand', 'expression', 'abv', 'origin', 'size', 'supplierId'],
    relatedEntities: ['InventoryItem', 'RecipeVersion', 'Supplier'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  WineSKU: {
    category: 'resources',
    domain: 'inventory',
    description: 'A specific wine SKU by producer, vintage, and format.',
    typicalFields: ['id', 'inventoryItemId', 'producer', 'vintage', 'region', 'varietal', 'format', 'supplierId'],
    relatedEntities: ['InventoryItem', 'Supplier'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  BeerSKU: {
    category: 'resources',
    domain: 'inventory',
    description: 'A specific beer SKU by brand, style, and format.',
    typicalFields: ['id', 'inventoryItemId', 'brand', 'style', 'abv', 'format', 'supplierId'],
    relatedEntities: ['InventoryItem', 'Supplier'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  LiqueurSKU: {
    category: 'resources',
    domain: 'inventory',
    description: 'A specific liqueur, amaro, or modifier SKU.',
    typicalFields: ['id', 'inventoryItemId', 'brand', 'style', 'abv', 'supplierId'],
    relatedEntities: ['InventoryItem', 'Supplier'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  Garnish: {
    category: 'resources',
    domain: 'inventory',
    description: 'A garnish item used in cocktail or plate presentation (citrus, herbs, dehydrated fruits).',
    typicalFields: ['id', 'inventoryItemId', 'type', 'perishable', 'prepRequired'],
    relatedEntities: ['InventoryItem', 'RecipeVersion', 'PrepBatch'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'P2',
  },
  IceProgram: {
    category: 'resources',
    domain: 'inventory',
    description: 'The ice specification and program (cubed, sphere, crushed, block, large format).',
    typicalFields: ['id', 'venueId', 'types', 'supplier', 'machineId', 'dailyOutput'],
    relatedEntities: ['Venue', 'RecipeVersion'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  Glassware: {
    category: 'resources',
    domain: 'inventory',
    description: 'A tracked glassware type used in service.',
    typicalFields: ['id', 'name', 'type', 'capacity', 'quantity', 'breakageRate'],
    relatedEntities: ['InventoryItem', 'RecipeVersion'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  Linen: {
    category: 'resources',
    domain: 'inventory',
    description: 'Table linen, napkins, and soft goods tracked in hospitality operations.',
    typicalFields: ['id', 'type', 'quantity', 'condition', 'laundryService'],
    relatedEntities: ['InventoryItem'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  Amenity: {
    category: 'resources',
    domain: 'lodging',
    description: 'A guest room or venue amenity item (toiletries, robes, welcome gifts).',
    typicalFields: ['id', 'name', 'type', 'quantity', 'restockTrigger'],
    relatedEntities: ['GuestRoom', 'InventoryItem'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  CleaningSupply: {
    category: 'resources',
    domain: 'facilities',
    description: 'A tracked cleaning product or supply used in housekeeping or FOH.',
    typicalFields: ['id', 'name', 'type', 'quantity', 'parLevel', 'hazardous'],
    relatedEntities: ['InventoryItem'],
    databaseCandidate: false,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: false,
    priority: 'Future',
  },
  Equipment: {
    category: 'resources',
    domain: 'facilities',
    description: 'A physical piece of operational equipment with a maintenance history.',
    typicalFields: ['id', 'name', 'type', 'purchaseDate', 'warrantyExpiry', 'maintenanceSchedule', 'lastServiced'],
    relatedEntities: ['MaintenanceTicket', 'Venue'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
}

// ─── F. Knowledge ──────────────────────────────────────────────────────────────

export const KNOWLEDGE_ENTITIES = {
  SOP: {
    category: 'knowledge',
    domain: 'standards',
    description: 'A Standard Operating Procedure document defining how a task must be performed.',
    typicalFields: ['id', 'name', 'category', 'version', 'steps', 'author', 'approvedBy', 'lastReviewedAt', 'relatedRoles'],
    relatedEntities: ['TrainingModule', 'CoachingNote', 'Incident'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  Note: {
    category: 'knowledge',
    domain: 'operations',
    description: 'A freeform operational note created by a manager or staff member during or after a shift.',
    typicalFields: ['id', 'shiftId', 'authorId', 'content', 'category', 'timestamp', 'visibility'],
    relatedEntities: ['Shift', 'StaffMember', 'ShiftReport'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P0',
  },
  Memory: {
    category: 'knowledge',
    domain: 'intelligence',
    description: 'A structured, summarized, and confidence-scored record of something HESTIA should remember long-term.',
    typicalFields: ['id', 'subjectType', 'subjectId', 'content', 'confidence', 'sourceEventIds', 'createdAt', 'expiresAt', 'sensitivityTier', 'requiresHumanReview'],
    relatedEntities: ['Guest', 'StaffMember', 'Incident', 'EventClient'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  TrainingModule: {
    category: 'knowledge',
    domain: 'learning',
    description: 'A structured learning unit for staff development (video, quiz, scenario).',
    typicalFields: ['id', 'title', 'category', 'skillIds', 'duration', 'completionCriteria', 'version'],
    relatedEntities: ['Skill', 'SOP', 'CoachingNote', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  CoachingNote: {
    category: 'knowledge',
    domain: 'learning',
    description: 'A documented observation or coaching action from a manager toward a staff member.',
    typicalFields: ['id', 'staffMemberId', 'managerId', 'content', 'type', 'linkedIncidentId', 'timestamp', 'followUpDate', 'acknowledged'],
    relatedEntities: ['StaffMember', 'Manager', 'Incident', 'SOP'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  ConstraintRule: {
    category: 'knowledge',
    domain: 'standards',
    description: 'A hard operational rule the system must respect (e.g. no pork, no alcohol during certain hours).',
    typicalFields: ['id', 'name', 'type', 'scope', 'rule', 'exceptions', 'authority', 'effectiveFrom'],
    relatedEntities: ['Venue', 'Menu', 'AccessibilityRequirement'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  AccessibilityRequirement: {
    category: 'knowledge',
    domain: 'inclusion',
    description: 'A documented accessibility need for a guest, client, or space configuration.',
    typicalFields: ['id', 'subjectType', 'subjectId', 'requirementType', 'description', 'mustBeVerified', 'lastConfirmedAt'],
    relatedEntities: ['Guest', 'Reservation', 'EventBooking', 'Venue'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  KosherRuleSet: {
    category: 'knowledge',
    domain: 'standards',
    description: 'A formal set of kashrut (kosher) operational rules governing a venue or service period.',
    typicalFields: ['id', 'venueId', 'certifyingBody', 'rules', 'supervisorContact', 'certificationExpiry', 'activeFrom'],
    relatedEntities: ['Venue', 'ConstraintRule', 'Menu'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
}

// ─── G. Temporal / Intelligence ────────────────────────────────────────────────

export const INTELLIGENCE_ENTITIES = {
  EventLog: {
    category: 'intelligence',
    domain: 'telemetry',
    description: 'An immutable record of something that happened within HESTIA operations.',
    typicalFields: ['id', 'eventType', 'timestamp', 'actorId', 'actorType', 'entityType', 'entityId', 'payload', 'sensitivityTier'],
    relatedEntities: ['Shift', 'Guest', 'StaffMember', 'Incident'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  ShiftReport: {
    category: 'intelligence',
    domain: 'reporting',
    description: 'A summarized record of a completed shift including signals, incidents, and manager notes.',
    typicalFields: ['id', 'shiftId', 'covers', 'revenue', 'incidentCount', 'recoveryCount', 'compTotal', 'managerNotes', 'aiSummary'],
    relatedEntities: ['Shift', 'Incident', 'Note', 'KPISnapshot'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P0',
  },
  Forecast: {
    category: 'intelligence',
    domain: 'planning',
    description: 'A projection of expected demand, revenue, or operational load for a future period.',
    typicalFields: ['id', 'venueId', 'period', 'forecastedCovers', 'forecastedRevenue', 'confidence', 'method', 'generatedAt'],
    relatedEntities: ['Venue', 'Shift', 'KPISnapshot'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P2',
  },
  KPISnapshot: {
    category: 'intelligence',
    domain: 'reporting',
    description: 'A point-in-time capture of key performance metrics for a venue or shift.',
    typicalFields: ['id', 'venueId', 'period', 'metrics', 'capturedAt'],
    relatedEntities: ['Venue', 'ShiftReport'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  Alert: {
    category: 'intelligence',
    domain: 'operations',
    description: 'A system-generated or agent-generated signal that requires manager attention.',
    typicalFields: ['id', 'type', 'severity', 'message', 'entityType', 'entityId', 'generatedAt', 'acknowledgedAt', 'acknowledgedBy'],
    relatedEntities: ['Incident', 'StockCount', 'MaintenanceTicket'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  Recommendation: {
    category: 'intelligence',
    domain: 'operations',
    description: 'An AI or rules-engine output suggesting an action for a manager or staff member.',
    typicalFields: ['id', 'agentName', 'type', 'content', 'confidence', 'relatedEntityType', 'relatedEntityId', 'generatedAt', 'acceptedAt', 'rejectedAt', 'outcome'],
    relatedEntities: ['Alert', 'Incident', 'Shift'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
}

// ─── Supply chain (referenced in relationships) ────────────────────────────────

export const SUPPLY_ENTITIES = {
  Supplier: {
    category: 'supply',
    domain: 'procurement',
    description: 'A vendor or distributor that provides inventory items to the venue.',
    typicalFields: ['id', 'name', 'category', 'contactInfo', 'paymentTerms', 'deliverySchedule', 'reliabilityScore'],
    relatedEntities: ['InventoryItem', 'PurchaseOrder', 'SupplierContact'],
    databaseCandidate: true,
    memoryCandidate: true,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P1',
  },
  PurchaseOrder: {
    category: 'supply',
    domain: 'procurement',
    description: 'A formal order placed with a supplier for inventory items.',
    typicalFields: ['id', 'supplierId', 'items', 'orderedAt', 'expectedDelivery', 'status', 'totalCost'],
    relatedEntities: ['Supplier', 'InventoryItem', 'InvoiceLine'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P2',
  },
  InvoiceLine: {
    category: 'supply',
    domain: 'procurement',
    description: 'A single line item on a supplier invoice, used for cost tracking and variance detection.',
    typicalFields: ['id', 'purchaseOrderId', 'inventoryItemId', 'quantity', 'unitCost', 'totalCost', 'invoiceDate'],
    relatedEntities: ['PurchaseOrder', 'InventoryItem'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P2',
  },
  StockCount: {
    category: 'supply',
    domain: 'inventory',
    description: 'A recorded physical count of inventory at a point in time.',
    typicalFields: ['id', 'venueId', 'conductedBy', 'timestamp', 'items', 'varianceNotes'],
    relatedEntities: ['InventoryItem', 'StorageLocation', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  WasteLog: {
    category: 'supply',
    domain: 'inventory',
    description: 'A logged record of wasted, spoiled, or discarded inventory.',
    typicalFields: ['id', 'inventoryItemId', 'quantity', 'reason', 'loggedBy', 'shiftId', 'timestamp', 'cost'],
    relatedEntities: ['InventoryItem', 'Shift', 'StaffMember'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: true,
    agentRelevant: true,
    priority: 'P1',
  },
  SeatingPlan: {
    category: 'operational',
    domain: 'events',
    description: 'A defined floor plan and table configuration for an event.',
    typicalFields: ['id', 'eventBookingId', 'layout', 'tableCount', 'seatsPerTable', 'accessibilityPaths', 'specialRequirements'],
    relatedEntities: ['EventBooking', 'Table', 'AccessibilityRequirement'],
    databaseCandidate: true,
    memoryCandidate: false,
    eventLogCandidate: false,
    agentRelevant: true,
    priority: 'P2',
  },
}

// ─── Consolidated export ────────────────────────────────────────────────────────

export const hospitalityEntities = {
  venue: VENUE_ENTITIES,
  people: PEOPLE_ENTITIES,
  commercial: COMMERCIAL_ENTITIES,
  operational: OPERATIONAL_ENTITIES,
  resources: RESOURCE_ENTITIES,
  knowledge: KNOWLEDGE_ENTITIES,
  intelligence: INTELLIGENCE_ENTITIES,
  supply: SUPPLY_ENTITIES,
}
