// Data model map for HESTIA hospitality domain.
// Separates entity concepts into four implementation categories:
//   A. Structured database candidates — normalized relational or document records
//   B. Long-term memory candidates — see hospitalityMemoryMap.js
//   C. Event log candidates — see hospitalityEventTypes.js
//   D. AI agent logic candidates — see hospitalityAgentMap.js
// This file focuses on category A with references to B, C, D.
// No operational records. No fake data. Schema definitions only.

// ─── A. Structured database candidates ────────────────────────────────────────

export const DATABASE_CANDIDATES = [
  {
    entity: 'Venue',
    purpose: 'Master record for the operational venue. All other entities reference it.',
    importantFields: ['id', 'name', 'type', 'timezone', 'operatingHours', 'currency', 'locale'],
    relationships: ['1:N to ServiceArea', '1:N to Department', '1:N to StaffMember'],
    priority: 'P0',
    whyItMatters: 'Every shift, guest, and transaction belongs to a venue. Without this anchor, nothing relates correctly.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'ServiceSpace',
    purpose: 'Unified table of all assignable spaces (tables, bar seats, rooms, event spaces).',
    importantFields: ['id', 'venueId', 'type', 'name', 'capacity', 'isAccessible', 'serviceAreaId'],
    relationships: ['N:1 to Venue', 'N:1 to ServiceArea'],
    priority: 'P0',
    whyItMatters: 'A single space model simplifies queries across dining, bar, and lodging contexts.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'StaffProfile',
    purpose: 'Complete record of a staff member including role, skills, and certifications.',
    importantFields: ['id', 'venueId', 'name', 'roleId', 'skillIds', 'certifications', 'hireDate', 'status'],
    relationships: ['N:1 to Venue', 'N:1 to Role', 'N:M to Skill'],
    priority: 'P0',
    whyItMatters: 'Staff records are the foundation of scheduling, coaching, and compliance tracking.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'Shift',
    purpose: 'Operational container for all activity in a defined service window.',
    importantFields: ['id', 'venueId', 'date', 'startTime', 'endTime', 'managerId', 'shiftType', 'status'],
    relationships: ['N:1 to Venue', 'N:1 to StaffProfile (manager)', 'N:M to StaffProfile (staff)'],
    priority: 'P0',
    whyItMatters: 'All incidents, notes, checks, and assignments must be anchored to a shift for temporal analysis.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'SectionAssignment',
    purpose: 'Records which staff member is responsible for which section during a shift.',
    importantFields: ['id', 'shiftId', 'serverId', 'serviceAreaId', 'tableIds', 'assignedAt'],
    relationships: ['N:1 to Shift', 'N:1 to StaffProfile', 'N:1 to ServiceArea'],
    priority: 'P0',
    whyItMatters: 'Section assignments are required for load-balance analysis and server performance attribution.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'GuestProfile',
    purpose: 'Core identity record for a guest with contact info and visit metadata.',
    importantFields: ['id', 'name', 'contactInfo', 'language', 'visitCount', 'firstVisit', 'lastVisit', 'isVIP'],
    relationships: ['1:N to Reservation', '1:N to VisitOrParty', '1:N to Memory'],
    priority: 'P1',
    whyItMatters: 'A durable guest identity enables memory compounding and return-visit personalization.',
    implementationPhase: 'Phase 2',
    note: 'Guest profiles require consent-aware data collection design before implementation.',
  },
  {
    entity: 'Reservation',
    purpose: 'Pre-committed guest booking with all associated promises.',
    importantFields: ['id', 'guestId', 'venueId', 'dateTime', 'partySize', 'tableId', 'specialRequests', 'celebrationFlag', 'accessibilityRequirements', 'status'],
    relationships: ['N:1 to GuestProfile', 'N:1 to Venue', 'N:1 to ServiceSpace'],
    priority: 'P0',
    whyItMatters: 'Reservation data drives pre-shift briefing, section planning, and VIP identification.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'WaitlistEntry',
    purpose: 'Real-time queue of walk-in guests waiting for availability.',
    importantFields: ['id', 'venueId', 'partySize', 'quoteTime', 'joinedAt', 'status', 'contactMethod'],
    relationships: ['N:1 to Venue', 'N:1 to GuestProfile (optional)'],
    priority: 'P1',
    whyItMatters: 'Waitlist depth and quote accuracy are key host stand performance signals.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'VisitOrParty',
    purpose: 'The live or completed record of a guest visit on a specific occasion.',
    importantFields: ['id', 'reservationId', 'guestId', 'partySize', 'arrivedAt', 'seatedAt', 'departedAt', 'tableId', 'serverId', 'occasion'],
    relationships: ['N:1 to Reservation (optional)', 'N:1 to GuestProfile', 'N:1 to ServiceSpace', 'N:1 to StaffProfile'],
    priority: 'P0',
    whyItMatters: 'The visit record links the guest, their experience, and the resulting check into a single unit.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'Stay',
    purpose: 'A hotel guest booking across one or more nights with room and rate details.',
    importantFields: ['id', 'guestId', 'roomId', 'checkIn', 'checkOut', 'ratePlan', 'specialRequests', 'status'],
    relationships: ['N:1 to GuestProfile', 'N:1 to ServiceSpace (room)', 'N:1 to Folio'],
    priority: 'P2',
    whyItMatters: 'Hotel stays are the lodging equivalent of the visit record — the container for all in-stay events.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'OrderCheckFolio',
    purpose: 'Unified table covering dining checks and hotel folios — the financial record of a visit or stay.',
    importantFields: ['id', 'visitOrPartyId', 'stayId', 'items', 'subtotal', 'tax', 'gratuity', 'comps', 'total', 'paymentMethod', 'openedAt', 'closedAt'],
    relationships: ['N:1 to VisitOrParty or Stay', 'N:M to MenuItem'],
    priority: 'P0',
    whyItMatters: 'Without check data, revenue, comp, and sales mix analysis are impossible.',
    implementationPhase: 'MVP',
    note: 'In MVP, this may be a simplified check record. Full POS integration required for production accuracy.',
  },
  {
    entity: 'MenuItem',
    purpose: 'A single active menu item with pricing, allergens, and recipe linkage.',
    importantFields: ['id', 'menuId', 'name', 'price', 'category', 'allergens', 'recipeVersionId', 'isActive', 'costOfGoods'],
    relationships: ['N:1 to Menu', 'N:1 to RecipeVersion'],
    priority: 'P0',
    whyItMatters: 'Menu items are the unit of revenue, cost, and popularity analysis.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'RecipeVersion',
    purpose: 'A versioned recipe specification for cost tracking and consistency standards.',
    importantFields: ['id', 'menuItemId', 'version', 'ingredients', 'method', 'yield', 'cost', 'activeFrom'],
    relationships: ['N:1 to MenuItem', 'N:M to InventoryItem (ingredients)'],
    priority: 'P1',
    whyItMatters: 'Recipe versions enable cost-of-goods tracking and variance analysis when ingredients change.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'PrepBatch',
    purpose: 'Records of production runs that link kitchen output to inventory consumption.',
    importantFields: ['id', 'recipeVersionId', 'quantity', 'unit', 'preparedBy', 'shiftId', 'expiresAt'],
    relationships: ['N:1 to RecipeVersion', 'N:1 to Shift'],
    priority: 'P1',
    whyItMatters: 'Prep batches bridge the gap between theoretical recipe usage and actual inventory consumption.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'InventoryItem',
    purpose: 'Every trackable ingredient, beverage SKU, or supply with stock levels and cost data.',
    importantFields: ['id', 'name', 'category', 'unit', 'parLevel', 'currentStock', 'supplierId', 'costPerUnit', 'lastCounted'],
    relationships: ['N:1 to Supplier', 'N:M to RecipeVersion', '1:N to StockCount entries'],
    priority: 'P1',
    whyItMatters: 'The inventory record is the foundation of cost control, reorder logic, and waste analysis.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'Supplier',
    purpose: 'Vendor records with reliability and pricing data for procurement decisions.',
    importantFields: ['id', 'name', 'category', 'contactInfo', 'deliverySchedule', 'reliabilityScore', 'paymentTerms'],
    relationships: ['1:N to InventoryItem', '1:N to PurchaseOrder'],
    priority: 'P1',
    whyItMatters: 'Supplier data is the upstream anchor for cost variance and procurement risk.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'PurchaseOrder',
    purpose: 'Formal order records for tracking delivery and matching to invoice.',
    importantFields: ['id', 'supplierId', 'items', 'orderedAt', 'expectedDelivery', 'status', 'totalCost'],
    relationships: ['N:1 to Supplier', 'N:M to InventoryItem'],
    priority: 'P2',
    whyItMatters: 'PO records close the loop between par-level reorder decisions and actual delivery.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'InvoiceLine',
    purpose: 'Line-item cost records from supplier invoices, linked to specific inventory items.',
    importantFields: ['id', 'purchaseOrderId', 'inventoryItemId', 'quantity', 'unitCost', 'totalCost', 'invoiceDate'],
    relationships: ['N:1 to PurchaseOrder', 'N:1 to InventoryItem'],
    priority: 'P2',
    whyItMatters: 'Invoice lines are the source of truth for unit cost trends and recipe margin calculations.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'StockCount',
    purpose: 'Periodic physical inventory counts with variance tracking.',
    importantFields: ['id', 'venueId', 'conductedBy', 'timestamp', 'items', 'varianceNotes'],
    relationships: ['N:1 to Venue', 'N:M to InventoryItem'],
    priority: 'P1',
    whyItMatters: 'Physical counts are the ground truth for detecting inventory loss, waste, and theft.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'WasteLog',
    purpose: 'Categorized waste records that separate known loss from unexplained variance.',
    importantFields: ['id', 'inventoryItemId', 'quantity', 'reason', 'loggedBy', 'shiftId', 'timestamp', 'cost'],
    relationships: ['N:1 to InventoryItem', 'N:1 to Shift'],
    priority: 'P1',
    whyItMatters: 'Waste logging transforms "variance" into actionable data about why inventory is disappearing.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'Incident',
    purpose: 'The formal record of any unexpected event that degraded the guest or operational experience.',
    importantFields: ['id', 'shiftId', 'type', 'description', 'severity', 'reportedBy', 'resolvedBy', 'resolution', 'timestamp', 'isResolved'],
    relationships: ['N:1 to Shift', 'N:1 to GuestProfile (optional)', 'N:1 to StaffProfile (optional)', '1:N to ServiceRecoveryAction'],
    priority: 'P0',
    whyItMatters: 'Incidents are the primary input for recovery, coaching, and SOP improvement loops.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'ServiceRecoveryAction',
    purpose: 'Documented actions taken to recover a guest experience after a failure.',
    importantFields: ['id', 'incidentId', 'guestId', 'actionType', 'description', 'takenBy', 'approvedBy', 'cost', 'guestResponse', 'timestamp'],
    relationships: ['N:1 to Incident', 'N:1 to GuestProfile', 'N:1 to StaffProfile'],
    priority: 'P0',
    whyItMatters: 'Recovery actions must be linked to the guest record to enable future personalization and measure effectiveness.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'ChecklistTask',
    purpose: 'Trackable operational checklist with completion status per shift.',
    importantFields: ['id', 'name', 'type', 'assignedTo', 'shiftId', 'completedAt', 'status'],
    relationships: ['N:1 to Shift', 'N:1 to StaffProfile'],
    priority: 'P0',
    whyItMatters: 'Checklist completion is a measurable readiness signal that correlates with incident rates.',
    implementationPhase: 'MVP',
  },
  {
    entity: 'SOPDocument',
    purpose: 'Versioned Standard Operating Procedure documents.',
    importantFields: ['id', 'name', 'category', 'version', 'steps', 'author', 'approvedBy', 'lastReviewedAt'],
    relationships: ['1:N to CoachingNote (by linked incident)', '1:N to TrainingModule'],
    priority: 'P1',
    whyItMatters: 'SOPs are the formal output of the learning loop and the foundation for training and compliance.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'EventBooking',
    purpose: 'Commercial event records with client, guest count, and package details.',
    importantFields: ['id', 'clientId', 'spaceId', 'date', 'guestCount', 'package', 'minimumRevenue', 'status'],
    relationships: ['N:1 to EventClient', 'N:1 to ServiceSpace', '1:1 to SeatingPlan'],
    priority: 'P2',
    whyItMatters: 'Event bookings drive staffing, inventory, and accessibility planning well in advance.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'SeatingPlan',
    purpose: 'Floor plan configuration for events including accessibility paths.',
    importantFields: ['id', 'eventBookingId', 'layout', 'tableCount', 'seatsPerTable', 'accessibilityPaths'],
    relationships: ['1:1 to EventBooking', 'N:M to ServiceSpace (tables)'],
    priority: 'P2',
    whyItMatters: 'Seating plans must be linked to accessibility requirements to ensure compliance.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'HousekeepingTask',
    purpose: 'Room cleaning and turn-down assignments with status tracking.',
    importantFields: ['id', 'roomId', 'type', 'assignedTo', 'status', 'startedAt', 'completedAt', 'inspectedBy'],
    relationships: ['N:1 to ServiceSpace (room)', 'N:1 to StaffProfile'],
    priority: 'P2',
    whyItMatters: 'Housekeeping task status is the real-time signal for hotel arrival readiness.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'MaintenanceTicket',
    purpose: 'Repair and maintenance records with recurrence tracking for asset health monitoring.',
    importantFields: ['id', 'locationId', 'assetId', 'description', 'priority', 'reportedBy', 'assignedTo', 'status', 'openedAt', 'closedAt', 'recurrenceCount'],
    relationships: ['N:1 to ServiceSpace or Equipment', 'N:1 to StaffProfile'],
    priority: 'P2',
    whyItMatters: 'Recurring tickets on the same asset trigger replace-versus-repair evaluations.',
    implementationPhase: 'Phase 3',
  },
  {
    entity: 'TrainingModule',
    purpose: 'Structured learning content linked to skills, SOPs, and incident categories.',
    importantFields: ['id', 'title', 'category', 'skillIds', 'duration', 'completionCriteria', 'version'],
    relationships: ['N:M to Skill', 'N:1 to SOPDocument'],
    priority: 'P1',
    whyItMatters: 'Training modules are the actionable output of the coaching loop — they close the skill gap.',
    implementationPhase: 'Phase 2',
  },
  {
    entity: 'CoachingNote',
    purpose: 'Manager-to-staff coaching records linked to incidents and development plans.',
    importantFields: ['id', 'staffMemberId', 'managerId', 'content', 'type', 'linkedIncidentId', 'timestamp', 'followUpDate', 'acknowledged'],
    relationships: ['N:1 to StaffProfile', 'N:1 to StaffProfile (manager)', 'N:1 to Incident (optional)'],
    priority: 'P1',
    whyItMatters: 'Coaching notes are the formal link between operational incidents and staff development.',
    implementationPhase: 'Phase 2',
  },
]

// ─── B. Long-term memory candidates (reference only) ──────────────────────────
// Full definitions live in hospitalityMemoryMap.js
export const MEMORY_CANDIDATES_REFERENCE = {
  description: 'Long-term memory candidates are defined in hospitalityMemoryMap.js.',
  categories: ['guest', 'staff', 'operational'],
  keyTypes: [
    'GuestPreferences',
    'GuestAllergiesAndDietaryRestrictions',
    'ServiceRecoveryHistory',
    'VIPHandlingNotes',
    'StaffStrengths',
    'StaffDevelopmentAreas',
    'SupplierReliabilityPatterns',
    'RecurringIncidentPatterns',
  ],
}

// ─── C. Event log candidates (reference only) ─────────────────────────────────
// Full definitions live in hospitalityEventTypes.js
export const EVENT_LOG_CANDIDATES_REFERENCE = {
  description: 'Event log candidates are defined in hospitalityEventTypes.js.',
  categories: ['shift', 'booking', 'guestFlow', 'orderAndService', 'inventory', 'incident', 'operations', 'lodging', 'events', 'accessibility', 'learning'],
  totalEventTypes: 30,
}

// ─── D. AI agent logic candidates (reference only) ────────────────────────────
// Full definitions live in hospitalityAgentMap.js
export const AGENT_LOGIC_CANDIDATES_REFERENCE = {
  description: 'AI agent candidates are defined in hospitalityAgentMap.js.',
  mvpAgents: ['ShiftBrainAgent', 'PostShiftIntelligenceAgent'],
  phase2Agents: ['GuestMemoryAgent', 'BarManagerAgent', 'ServiceRecoveryAgent', 'StaffCoachingAgent', 'EventPlanningAgent', 'AccessibilityPlanningAgent', 'InventoryIntelligenceAgent'],
  phase3AndFuture: ['KitchenFlowAgent', 'SupplierIntelligenceAgent', 'MenuEngineeringAgent', 'HotelOperationsBrain', 'HospitalityMemoryEngine'],
}

export const hospitalityDataModelMap = {
  databaseCandidates: DATABASE_CANDIDATES,
  memoryCandidates: MEMORY_CANDIDATES_REFERENCE,
  eventLogCandidates: EVENT_LOG_CANDIDATES_REFERENCE,
  agentLogicCandidates: AGENT_LOGIC_CANDIDATES_REFERENCE,
}
